CREATE VIEW default.wms_quick_code_master
(
    `wms_code_ou` Nullable(Int32),
    `wms_code_type` Nullable(String),
    `wms_code` Nullable(String),
    `wms_code_desc` Nullable(String),
    `wms_default` Nullable(String),
    `wms_seq_no` Nullable(Int32),
    `wms_status` Nullable(String),
    `wms_category` Nullable(String),
    `wms_user_flag` Nullable(String),
    `wms_timestamp` Nullable(Int32),
    `wms_langid` Nullable(Int32),
    `wms_created_date` Nullable(DateTime64(6)),
    `wms_created_by` Nullable(String),
    `wms_modified_date` Nullable(DateTime64(6)),
    `wms_modified_by` Nullable(String),
    `etlactiveind` Nullable(Int32),
    `etljobname` Nullable(String),
    `envsourcecd` Nullable(String),
    `datasourcecd` Nullable(String),
    `etlcreatedatetime` Nullable(DateTime64(6)),
    `etlupdatedatetime` Nullable(DateTime64(6))
) AS
SELECT
    code_ou AS wms_code_ou,
    code_type AS wms_code_type,
    code AS wms_code,
    code_desc AS wms_code_desc,
    code_default AS wms_default,
    seq_no AS wms_seq_no,
    status AS wms_status,
    category AS wms_category,
    user_flag AS wms_user_flag,
    code_timestamp AS wms_timestamp,
    langid AS wms_langid,
    created_date AS wms_created_date,
    created_by AS wms_created_by,
    modified_date AS wms_modified_date,
    modified_by AS wms_modified_by,
    etlactiveind,
    etljobname,
    envsourcecd,
    datasourcecd,
    etlcreatedatetime,
    etlupdatedatetime
FROM onesource.d_wmsquickcodes