CREATE TABLE stg.stg_tms_vrve_veh_eqp_response_dtl (
    vrve_ouinstance integer NOT NULL,
    vrve_tend_req_no character varying(72) NOT NULL COLLATE public.nocase,
    vrve_line_no character varying(512) NOT NULL COLLATE public.nocase,
    vrve_vendor_id character varying(160) COLLATE public.nocase,
    vrve_resp_status character varying(160) COLLATE public.nocase,
    vrve_resp_for character varying(160) COLLATE public.nocase,
    vrve_type character varying(160) COLLATE public.nocase,
    vrve_req_qty numeric,
    vrve_vend_ref_no character varying(160) COLLATE public.nocase,
    vrve_vend_ref_date timestamp without time zone,
    vrve_contract_id character varying(72) COLLATE public.nocase,
    vrve_confirm_status character varying(160) COLLATE public.nocase,
    vrve_confirm_qty numeric,
    vrve_rate numeric,
    vrve_created_by character varying(120) COLLATE public.nocase,
    vrve_created_date timestamp without time zone,
    vrve_last_modified_by character varying(120) COLLATE public.nocase,
    vrve_last_modified_date timestamp without time zone,
    vrve_timestamp integer,
    vrve_confirm_price numeric,
    vrve_confirm_date timestamp without time zone,
    vrve_rpt_date_time character varying(100) COLLATE public.nocase,
    vrvel_remarks character varying(1020) COLLATE public.nocase,
    vrvel_reject_code character varying(160) COLLATE public.nocase,
    vrve_for_period numeric,
    vrve_period_uom character varying(160) COLLATE public.nocase,
    vrve_from_geo character varying(160) COLLATE public.nocase,
    vrve_from_geo_type character varying(160) COLLATE public.nocase,
    vrve_to_geo character varying(160) COLLATE public.nocase,
    vrve_to_geo_type character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);