CREATE TABLE stg.stg_spy_prepay_vch_hdr (
    ou_id integer NOT NULL,
    voucher_no character varying(72) NOT NULL COLLATE public.nocase,
    tran_type character varying(100) NOT NULL COLLATE public.nocase,
    ptimestamp integer NOT NULL,
    voucher_type character varying(160) COLLATE public.nocase,
    request_date timestamp without time zone,
    fb_id character varying(80) COLLATE public.nocase,
    supp_code character varying(64) COLLATE public.nocase,
    payment_route character varying(40) COLLATE public.nocase,
    pay_mode character varying(100) COLLATE public.nocase,
    priority character varying(48) COLLATE public.nocase,
    pay_currency character varying(20) COLLATE public.nocase,
    exchange_rate numeric,
    dd_charges character varying(40) COLLATE public.nocase,
    pay_amount numeric,
    pay_amt_bef_round numeric,
    roundoff_amt numeric,
    par_exchange_rate numeric,
    pay_date timestamp without time zone,
    bank_cash_code character varying(128) COLLATE public.nocase,
    relpay_ou character varying(64) COLLATE public.nocase,
    reason_code character varying(40) COLLATE public.nocase,
    hld_reason_code character varying(40) COLLATE public.nocase,
    remarks character varying(1020) COLLATE public.nocase,
    hld_remarks character varying(400) COLLATE public.nocase,
    rev_remarks character varying(400) COLLATE public.nocase,
    rev_date timestamp without time zone,
    notype_no character varying(40) COLLATE public.nocase,
    supp_area character varying(64) COLLATE public.nocase,
    supp_doc_no character varying(400) COLLATE public.nocase,
    supp_doc_date timestamp without time zone,
    supp_doc_amt numeric,
    supp_prepay_acct character varying(128) COLLATE public.nocase,
    bank_cash_acct character varying(128) COLLATE public.nocase,
    supp_receipt_no character varying(72) COLLATE public.nocase,
    receipt_date timestamp without time zone,
    status character varying(100) COLLATE public.nocase,
    batch_id character varying(512) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    tcal_exclusive_amt numeric,
    total_tcal_amount numeric,
    tcal_status character varying(48) COLLATE public.nocase,
    voucher_amount numeric,
    ibe_flag character varying(48) COLLATE public.nocase,
    consistency_stamp character varying(48) COLLATE public.nocase,
    lcnumber character varying(120) COLLATE public.nocase,
    refid character varying(480) COLLATE public.nocase,
    workflow_status character varying(80) COLLATE public.nocase,
    tr_flag character varying(4) COLLATE public.nocase,
    tr_percent numeric,
    tr_amount numeric,
    tr_tenure integer,
    tr_duedate timestamp without time zone,
    receipt_no character varying(72) COLLATE public.nocase,
    surnotype_no character varying(40) COLLATE public.nocase,
    bankcurrency character varying(20) COLLATE public.nocase,
    crosscur_erate numeric,
    bank_amount numeric,
    bank_base_amount numeric,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    afe_number character varying(72) COLLATE public.nocase,
    job_number character varying(72) COLLATE public.nocase,
    auto_gen_flag character varying(100) COLLATE public.nocase,
    trnsfr_inv_no character varying(72) COLLATE public.nocase,
    trnsfr_inv_date timestamp without time zone,
    trnsfr_inv_ou integer,
    lgt_invoice_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    lgt_rev_guid character varying(512) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE ONLY stg.stg_spy_prepay_vch_hdr
    ADD CONSTRAINT spy_prepay_vch_hdr_pkey PRIMARY KEY (ou_id, voucher_no, tran_type);