CREATE TABLE stg.stg_cust_comp_info (
    comp_lo character varying(80) NOT NULL COLLATE public.nocase,
    comp_cust_code character varying(72) NOT NULL COLLATE public.nocase,
    comp_comp_code character varying(40) NOT NULL COLLATE public.nocase,
    comp_account_group_code character varying(80) COLLATE public.nocase,
    comp_cust_bank_id character varying(128) COLLATE public.nocase,
    comp_comp_bankacc_no character varying(128) COLLATE public.nocase,
    comp_cust_bankacc_no character varying(128) COLLATE public.nocase,
    comp_tax_exempt_cert_no character varying(72) COLLATE public.nocase,
    comp_bank_esr_code character varying(128) COLLATE public.nocase,
    comp_bank_esr_type character varying(32) NOT NULL COLLATE public.nocase,
    comp_ptt_esr_flag character varying(32) NOT NULL COLLATE public.nocase,
    comp_ptt_acc_no character varying(128) COLLATE public.nocase,
    comp_ptt_esr_code character varying(128) COLLATE public.nocase,
    comp_ptt_esr_type character varying(32) NOT NULL COLLATE public.nocase,
    comp_bank_esr_flag character varying(32) NOT NULL COLLATE public.nocase,
    comp_vat_class character varying(160) COLLATE public.nocase,
    comp_vat_category character varying(160) COLLATE public.nocase,
    comp_euro_vat_id character varying(160) COLLATE public.nocase,
    comp_swiss_vat_id character varying(160) COLLATE public.nocase,
    comp_recpt_mode character varying(32) NOT NULL COLLATE public.nocase,
    comp_created_by character varying(120) NOT NULL COLLATE public.nocase,
    comp_created_date timestamp without time zone NOT NULL,
    comp_modified_by character varying(120) NOT NULL COLLATE public.nocase,
    comp_modified_date timestamp without time zone NOT NULL,
    comp_addnl1 character varying(1020) COLLATE public.nocase,
    comp_addnl2 character varying(1020) COLLATE public.nocase,
    comp_addnl3 integer,
    comp_created_at integer,
    cou_tax_exempt character(20) COLLATE public.nocase,
    comp_chq_bounce_req character(12) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);