CREATE TABLE IF NOT EXISTS stg.stg_si_doc_balance
(
    tran_ou integer NOT NULL,
    tran_type character varying(40) COLLATE public.nocase NOT NULL,
    tran_no character varying(72) COLLATE public.nocase NOT NULL,
    term_no character varying(80) COLLATE public.nocase NOT NULL,
    lo_id character varying(80) COLLATE public.nocase,
    tran_currency character varying(20) COLLATE public.nocase,
    tran_amount numeric,
    exchange_rate numeric,
    base_amount numeric,
    par_exchange_rate numeric,
    par_base_amount numeric,
    doc_status character varying(100) COLLATE public.nocase,
    adjustment_status character varying(100) COLLATE public.nocase,
    discount_amount numeric,
    disc_availed numeric,
    penalty_amount numeric,
    paid_amt numeric,
    requested_amount numeric,
    adjusted_amount numeric,
    batch_id character varying(512) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    due_date timestamp without time zone,
    discount_date timestamp without time zone,
    account_code character varying(128) COLLATE public.nocase,
    account_type character varying(60) COLLATE public.nocase NOT NULL,
    cr_paid_amount numeric,
    supp_code character varying(64) COLLATE public.nocase,
    fb_id character varying(80) COLLATE public.nocase,
    tran_date timestamp without time zone,
    outstanding_amt numeric,
    posting_date timestamp without time zone,
    base_outstanding_amt numeric,
    pbase_outstanding_amt numeric,
    base_adjusted_amount numeric,
    pbase_adjusted_amount numeric,
    base_paid_amt numeric,
    pbase_paid_amt numeric,
    disc_amount_type character varying(160) COLLATE public.nocase,
    disc_percent numeric,
    penalty_percent numeric,
    pdc_flag character varying(48) COLLATE public.nocase,
    pdc_void_flag character varying(48) COLLATE public.nocase,
    instr_no character varying(120) COLLATE public.nocase,
    rev_due_date timestamp without time zone,
    rev_discount_date timestamp without time zone,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now(),
    CONSTRAINT si_doc_balance_pkey PRIMARY KEY (tran_ou, tran_type, tran_no, term_no, account_type)
)