CREATE TABLE stg.stg_tms_pltph_trip_plan_hdr (
    plpth_ouinstance integer NOT NULL,
    plpth_plan_run_no character varying(160) NOT NULL COLLATE public.nocase,
    plpth_plan_run_status character varying(160) COLLATE public.nocase,
    plpth_trip_plan_id character varying(72) NOT NULL COLLATE public.nocase,
    plpth_trip_plan_planning_profile_id character varying(160) COLLATE public.nocase,
    plpth_trip_plan_status character varying(160) COLLATE public.nocase,
    plpth_trip_plan_date timestamp without time zone,
    plpth_trip_plan_end_date timestamp without time zone,
    plpth_trip_plan_from character varying(160) COLLATE public.nocase,
    plpth_trip_plan_to character varying(160) COLLATE public.nocase,
    plpth_vehicle_profile character varying(160) COLLATE public.nocase,
    plpth_vehicle_type character varying(160) COLLATE public.nocase,
    plpth_vehicle_id character varying(160) COLLATE public.nocase,
    plpth_vehicle_resource character varying(160) COLLATE public.nocase,
    plpth_vehicle_cov_weight numeric,
    plpth_vehicle_bal_weight numeric,
    plpth_vehicle_bal_weight_uom character varying(160) COLLATE public.nocase,
    plpth_vehicle_bal_volume integer,
    plpth_vehicle_bal_volume_uom character varying(160) COLLATE public.nocase,
    plpth_equipment_profile character varying(160) COLLATE public.nocase,
    plpth_equipment_type character varying(160) COLLATE public.nocase,
    plpth_equipment_id character varying(160) COLLATE public.nocase,
    plpth_equipment_resource character varying(160) COLLATE public.nocase,
    plpth_equip_cov_weight numeric,
    plpth_equip_bal_weight numeric,
    plpth_equip_bal_weight_uom character varying(160) COLLATE public.nocase,
    plpth_equip_bal_volume integer,
    plpth_equip_bal_volume_uom character varying(160) COLLATE public.nocase,
    plpth_driver_profile character varying(160) COLLATE public.nocase,
    plpth_driver_grade character varying(160) COLLATE public.nocase,
    plpth_driver_id character varying(160) COLLATE public.nocase,
    plpth_driver_resource character varying(160) COLLATE public.nocase,
    plpth_handler_profile character varying(160) COLLATE public.nocase,
    plpth_handler_grade character varying(160) COLLATE public.nocase,
    plpth_handler_id character varying(160) COLLATE public.nocase,
    plpth_handler_resource character varying(160) COLLATE public.nocase,
    plpth_agent_profile character varying(160) COLLATE public.nocase,
    plpth_agent_service character varying(160) COLLATE public.nocase,
    plpth_agent_id character varying(160) COLLATE public.nocase,
    plpth_agent_resource character varying(160) COLLATE public.nocase,
    plpth_rec_trip_id character varying(160) COLLATE public.nocase,
    plpth_schedule_id character varying(160) COLLATE public.nocase,
    plpth_created_by character varying(120) COLLATE public.nocase,
    plpth_created_date timestamp without time zone,
    plpth_last_modified_by character varying(120) COLLATE public.nocase,
    plpth_last_modified_date timestamp without time zone,
    plpth_timestamp integer,
    plpth_location character varying(160) COLLATE public.nocase,
    plpth_actual_start_time character varying(100) COLLATE public.nocase,
    plpth_actual_end_time character varying(100) COLLATE public.nocase,
    agent_status character varying(160) COLLATE public.nocase,
    plpth_schedule_profile character varying(160) COLLATE public.nocase,
    plpth_plan_run_type character varying(160) COLLATE public.nocase,
    plpth_vehicle_cov_volume integer,
    plpth_driver2_profile character varying(160) COLLATE public.nocase,
    plpth_driver2_grade character varying(160) COLLATE public.nocase,
    plpth_driver2_id character varying(160) COLLATE public.nocase,
    plpth_driver2_resource character varying(160) COLLATE public.nocase,
    plpth_handler2_profile character varying(160) COLLATE public.nocase,
    plpth_handler2_grade character varying(160) COLLATE public.nocase,
    plpth_handler2_id character varying(160) COLLATE public.nocase,
    plpth_handler2_resource character varying(160) COLLATE public.nocase,
    plpth_schedule_resource character varying(160) COLLATE public.nocase,
    plpth_gps_ref_no character varying(160) COLLATE public.nocase,
    plpth_mobile_gps_ref_no character varying(160) COLLATE public.nocase,
    plpth_from_date_time character varying(100) COLLATE public.nocase,
    plpth_to_date_time character varying(100) COLLATE public.nocase,
    plpth_equipment2_id character varying(160) COLLATE public.nocase,
    plpth_plan_mode character varying(160) COLLATE public.nocase,
    plpth_amend_status character(8) COLLATE public.nocase,
    plpth_trip_plan_backtohub character varying(160) COLLATE public.nocase,
    plpth_trip_plan_rsncd character varying(160) COLLATE public.nocase,
    plpth_trip_plan_remarks character varying(1020) COLLATE public.nocase,
    plpth_vehicle_weight numeric,
    plpth_vehicle_volume numeric,
    pltph_booking_request_weight numeric,
    pltph_booking_request_volume numeric,
    pltph_expected_revenue numeric,
    pltph_expected_cost numeric,
    pltph_covered_qty numeric,
    pltph_booking_request character varying(160) COLLATE public.nocase,
    pltph_equipment_type_2 character varying(160) COLLATE public.nocase,
    pltph_equipment_status_2 character varying(160) COLLATE public.nocase,
    pltph_trip_thu_utilization numeric,
    pltph_execution_plan character varying(160) COLLATE public.nocase,
    pltph_trip_pallet_space integer,
    plpth_trip_plan_from_type character varying(160) COLLATE public.nocase,
    plpth_trip_plan_to_type character varying(160) COLLATE public.nocase,
    pltph_confirmation_date timestamp without time zone,
    pltph_release_date timestamp without time zone,
    pltph_unique_guid character varying(512) NOT NULL COLLATE public.nocase,
    pltph_error_id integer,
    pltph_error_desc character varying(16000) COLLATE public.nocase,
    pltph_mobile_remarks character varying(16000) COLLATE public.nocase,
    pltph_desktop_mobile_flag character(4) COLLATE public.nocase,
    pltph_vehicle_reg_num character varying(160) COLLATE public.nocase,
    pltph_trip_sht_cls_date timestamp without time zone,
    plpth_ship_point_id character varying(160) COLLATE public.nocase,
    plpth_prime_mover_chkflg character varying(160) COLLATE public.nocase,
    pltph_recurring_flag character(4) COLLATE public.nocase,
    plpth_consol_eway_bill_no character varying(160) COLLATE public.nocase,
    pltph_trip_calculated_chargeable_weight numeric,
    pltph_trip_applied_chargeable_weight numeric,
    plpth_trip_preload integer,
    tms_trip_plan_workflow_status character varying(160) COLLATE public.nocase,
    plpth_plan_accrual_jv_no character varying(80) COLLATE public.nocase,
    plpth_plan_reversal_jv_no character varying(80) COLLATE public.nocase,
    plpth_plan_accrual_jv_date timestamp without time zone,
    plpth_plan_accrual_jv_amount numeric,
    plpth_plan_reversal_jv_date timestamp without time zone,
    plpth_plan_reversal_jv_amount numeric,
    tms_trip_log_worklfow_status character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);