CREATE TABLE stg.stg_sdin_expense_dtl (
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    line_no integer NOT NULL,
    "timestamp" integer NOT NULL,
    expense character varying(160) COLLATE public.nocase,
    usage character varying(160) COLLATE public.nocase,
    uom character varying(60) COLLATE public.nocase,
    item_qty numeric,
    item_rate numeric,
    rate_per numeric,
    item_amount numeric,
    remarks character varying(1020) COLLATE public.nocase,
    cost_center character varying(40) COLLATE public.nocase,
    analysis_code character varying(20) COLLATE public.nocase,
    subanalysis_code character varying(20) COLLATE public.nocase,
    base_value numeric,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    accountcode character varying(128) COLLATE public.nocase,
    destou character varying(80) COLLATE public.nocase,
    destfb character varying(80) COLLATE public.nocase,
    destusageid character varying(80) COLLATE public.nocase,
    interfbjvno character varying(80) COLLATE public.nocase,
    accountcode_destusage character varying(128) COLLATE public.nocase,
    accountcode_interfb character varying(128) COLLATE public.nocase,
    analysis_code_dest character varying(20) COLLATE public.nocase,
    sub_analysis_code_dest character varying(20) COLLATE public.nocase,
    costcenter_dest character varying(128) COLLATE public.nocase,
    analysis_code_interfb character varying(20) COLLATE public.nocase,
    sub_analysis_code_interfb character varying(20) COLLATE public.nocase,
    costcenter_interfb character varying(128) COLLATE public.nocase,
    accountcode_sdin character varying(128) COLLATE public.nocase,
    visible_line_no integer,
    dest_comp character varying(40) COLLATE public.nocase,
    cfs_refdoc_ou integer,
    cfs_refdoc_no character varying(72) COLLATE public.nocase,
    cfs_refdoc_type character varying(160) COLLATE public.nocase,
    retentionml numeric,
    holdml numeric,
    trnsfr_invoice_no character varying(72) COLLATE public.nocase,
    trnsfr_inv_no character varying(72) COLLATE public.nocase,
    trnsfr_inv_date timestamp without time zone,
    trnsfr_inv_ou integer,
    draft_bill_lineno integer,
    draft_bill_no character varying(72) COLLATE public.nocase,
    trnsfr_bill_date timestamp without time zone,
    draft_bill_ou integer,
    draft_bill_line_no integer,
    trnsfr_bill_lineno integer,
    location character varying(160) COLLATE public.nocase,
    region character varying(160) COLLATE public.nocase,
    partytype character varying(24) COLLATE public.nocase,
    partycode character varying(80) COLLATE public.nocase,
    line_of_business character varying(160) COLLATE public.nocase,
    department character varying(160) COLLATE public.nocase,
    product character varying(160) COLLATE public.nocase,
    equip_type character varying(160) COLLATE public.nocase,
    service_type character varying(160) COLLATE public.nocase,
    order_type character varying(160) COLLATE public.nocase,
    vehicle_type character varying(160) COLLATE public.nocase,
    activity_type character varying(160) COLLATE public.nocase,
    party_group character varying(160) COLLATE public.nocase,
    nature character varying(160) COLLATE public.nocase,
    currency character varying(20) COLLATE public.nocase,
    owner_type character varying(24) COLLATE public.nocase,
    tariff_type character varying(48) COLLATE public.nocase,
    reimburs character varying(1020) COLLATE public.nocase,
    ifb_recon_jvno character varying(72) COLLATE public.nocase,
    own_tax_region character varying(40) COLLATE public.nocase,
    party_tax_region character varying(40) COLLATE public.nocase,
    decl_tax_region character varying(40) COLLATE public.nocase,
    subservice_type character varying(160) COLLATE public.nocase,
    leg_behaviour character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);