CREATE TABLE IF NOT EXISTS stg.stg_sin_tcd_dtl
(
    tran_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tran_ou integer NOT NULL,
    tran_no character varying(36) COLLATE pg_catalog."default" NOT NULL,
    line_no integer NOT NULL,
    item_tcd_code character varying(64) COLLATE pg_catalog."default" NOT NULL,
    tcd_version integer NOT NULL,
    item_tcd_var character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" integer,
    item_type character varying(10) COLLATE pg_catalog."default",
    tcd_level character varying(10) COLLATE pg_catalog."default",
    tcd_rate numeric(20,2),
    taxable_amount numeric(20,2),
    tcd_amount numeric(20,2),
    tcd_currency character varying(10) COLLATE pg_catalog."default",
    base_amount numeric(20,2),
    par_base_amount numeric(20,2),
    cost_center character varying(20) COLLATE pg_catalog."default",
    analysis_code character varying(10) COLLATE pg_catalog."default",
    subanalysis_code character varying(10) COLLATE pg_catalog."default",
    remarks character varying(1000) COLLATE pg_catalog."default",
    proposed_amount numeric(20,2),
    original_proposed_amt numeric(20,2),
    createdby character varying(60) COLLATE pg_catalog."default",
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE pg_catalog."default",
    modifieddate timestamp without time zone,
    tms_flag character varying(10) COLLATE pg_catalog."default",
    etlcreateddatetime timestamp(3) without time zone,
    CONSTRAINT sin_tcd_dtl_pkey PRIMARY KEY (tran_no, line_no, item_tcd_code, item_tcd_var, tcd_version, tran_ou, tran_type)
)