CREATE TABLE stg.stg_tms_trh_tender_req_header (
    trh_ouinstance integer NOT NULL,
    trh_tender_req_no character varying(72) NOT NULL COLLATE public.nocase,
    trh_numtype character varying(80) COLLATE public.nocase,
    trh_tender_req_status character varying(160) COLLATE public.nocase,
    trh_tender_req_date timestamp without time zone,
    trh_req_type character varying(160) COLLATE public.nocase,
    trh_req_id character varying(120) COLLATE public.nocase,
    trh_resp_time_limit integer,
    trh_resp_time_limit_uom character varying(160) COLLATE public.nocase,
    trh_tender_inst character varying(2000) COLLATE public.nocase,
    trh_transport_mode character varying(160) COLLATE public.nocase,
    trh_created_by character varying(120) COLLATE public.nocase,
    trh_created_date timestamp without time zone,
    trh_last_modified_by character varying(120) COLLATE public.nocase,
    trh_lst_modified_date timestamp without time zone,
    trh_timestamp integer,
    trh_tender_confirm_status character varying(160) COLLATE public.nocase,
    trh_resp_before timestamp without time zone,
    trh_tender_req_status_old character varying(160) COLLATE public.nocase,
    trh_tender_req_prevstatus character varying(100) COLLATE public.nocase,
    trh_workflow_status character varying(100) COLLATE public.nocase,
    trh_workflow_error character varying(72) COLLATE public.nocase,
    trh_wf_guid character varying(512) COLLATE public.nocase,
    trh_multi_del_ins_flag character(12) COLLATE public.nocase,
    trh_multi_del_ins character varying(1020) COLLATE public.nocase,
    trh_request_cost_currency character varying(160) COLLATE public.nocase,
    trh_requested_ext_cost numeric,
    trh_reason_rejection_mtr character varying(2000) COLLATE public.nocase,
    trh_workflow_status_mtr character varying(1020) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE ONLY stg.stg_tms_trh_tender_req_header
    ADD CONSTRAINT pk_tms_trh_tender_req_header PRIMARY KEY (trh_ouinstance, trh_tender_req_no);