CREATE TABLE stg.stg_wms_loc_location_hdr (
    wms_loc_ou bigint,
    wms_loc_code text COLLATE public.nocase,
    wms_loc_desc text COLLATE public.nocase,
    wms_loc_status text COLLATE public.nocase,
    wms_loc_type text COLLATE public.nocase,
    wms_reason_code text COLLATE public.nocase,
    wms_finance_book text COLLATE public.nocase,
    wms_costcenter text COLLATE public.nocase,
    wms_account_code bigint,
    wms_address1 text COLLATE public.nocase,
    wms_address2 text COLLATE public.nocase,
    wms_country text COLLATE public.nocase,
    wms_state text COLLATE public.nocase,
    wms_city text COLLATE public.nocase,
    wms_zip_code text COLLATE public.nocase,
    wms_contperson text COLLATE public.nocase,
    wms_contact_no text COLLATE public.nocase,
    wms_email bigint,
    wms_fax bigint,
    wms_time_zone_id text COLLATE public.nocase,
    wms_loc_lat double precision,
    wms_loc_long double precision,
    wms_user_def1 bigint,
    wms_user_def2 bigint,
    wms_user_def3 bigint,
    wms_timestamp bigint,
    wms_created_by text COLLATE public.nocase,
    wms_created_dt timestamp without time zone,
    wms_modified_by text COLLATE public.nocase,
    wms_modified_dt timestamp without time zone,
    wms_def_plan_mode text COLLATE public.nocase,
    wms_loc_shp_point text COLLATE public.nocase,
    wms_loc_warhouse bigint,
    wms_loc_yard bigint,
    wms_loc_veh_id bigint,
    wms_loc_veh_type bigint,
    wms_loc_auto_cr_tug_trip bigint,
    wms_loc_cubing bigint,
    wms_loc_default_thu_id bigint,
    wms_blanket_count_sa bigint,
    wms_enable_uid_prof bigint,
    wms_loc_linked_hub text COLLATE public.nocase,
    wms_bank_code bigint,
    wms_cash_code bigint,
    wms_loc_default_ethu bigint,
    wms_loc_enable_bin_chkbit bigint,
    etlcreateddatetime timestamp without time zone
);