CREATE TABLE stg.stg_tms_vrsc_schedule_response_dtl (
    vrsc_ouinstance integer,
    vrsc_tend_req_no character varying(72) COLLATE public.nocase,
    vrsc_line_no character varying(512) COLLATE public.nocase,
    vrsc_sch_req_line_no character varying(512) COLLATE public.nocase,
    vrsc_vendor_id character varying(160) COLLATE public.nocase,
    vrsc_contract_id character varying(160) COLLATE public.nocase,
    vrsc_resp_status character varying(160) COLLATE public.nocase,
    vrsc_voyage character varying(160) COLLATE public.nocase,
    vrsc_off_thu character varying(160) COLLATE public.nocase,
    vrsc_off_thu_qty numeric,
    vrsc_thu_uom character varying(160) COLLATE public.nocase,
    vrsc_created_by character varying(120) COLLATE public.nocase,
    vrsc_created_date timestamp without time zone,
    vrsc_last_modified_by character varying(120) COLLATE public.nocase,
    vrsc_last_modified_date timestamp without time zone,
    vrsc_timestamp integer,
    vrsc_reqdate character varying(160) COLLATE public.nocase,
    vrsc_reqqty numeric,
    vrsc_deptdatetime character varying(100) COLLATE public.nocase,
    vrsc_destdatetime character varying(100) COLLATE public.nocase,
    vrsc_vendrefno character varying(160) COLLATE public.nocase,
    vrsc_vendrefdate timestamp without time zone,
    vrsc_uom character varying(160) COLLATE public.nocase,
    vrsc_currency character varying(160) COLLATE public.nocase,
    vrsc_quoted_price character varying(160) COLLATE public.nocase,
    vrsc_carrier_type character varying(160) COLLATE public.nocase,
    vrsc_acceptd_thu_qty integer,
    vrsc_acceptd_price integer,
    vrsc_acceptd_thu integer,
    vrsc_confirmed_status character varying(160) COLLATE public.nocase,
    vrsc_remarks character varying(1020) COLLATE public.nocase,
    vrsc_reject_code character varying(160) COLLATE public.nocase,
    vrsc_off_wght numeric,
    vrsc_off_wght_uom character varying(60) COLLATE public.nocase,
    vrsc_tariff_id character varying(160) COLLATE public.nocase,
    vrsc_conf_thu character varying(160) COLLATE public.nocase,
    vrsc_conf_thu_qty numeric,
    vrsc_vessel_flight character varying(160) COLLATE public.nocase,
    vrsc_req_volume numeric,
    vrsc_volume_uom character varying(160) COLLATE public.nocase,
    vrsc_confirmed_volume numeric,
    vrsc_confirmed_weight numeric,
    vrsc_from_geo character varying(160) COLLATE public.nocase,
    vrsc_from_geo_type character varying(160) COLLATE public.nocase,
    vrsc_to_geo character varying(160) COLLATE public.nocase,
    vrsc_to_geo_type character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);