CREATE TABLE stg.stg_fbp_posted_trn_dtl (
    "timestamp" integer,
    batch_id character varying(512) COLLATE public.nocase,
    company_code character varying(40) COLLATE public.nocase,
    component_name character varying(80) COLLATE public.nocase,
    bu_id character varying(80) COLLATE public.nocase,
    fb_id character varying(80) COLLATE public.nocase,
    tran_ou integer,
    fb_voucher_no character varying(72) COLLATE public.nocase,
    fb_voucher_date timestamp without time zone,
    recon_flag character varying(48) COLLATE public.nocase,
    con_ref_voucherno character varying(72) COLLATE public.nocase,
    document_no character varying(72) COLLATE public.nocase,
    tran_type character varying(160) COLLATE public.nocase,
    tran_date timestamp without time zone,
    entry_date timestamp without time zone,
    auth_date timestamp without time zone,
    posting_date timestamp without time zone,
    ou_id integer,
    account_code character varying(128) COLLATE public.nocase,
    drcr_flag character varying(24) COLLATE public.nocase,
    currency_code character varying(20) COLLATE public.nocase,
    tran_amount numeric,
    base_amount numeric,
    par_base_amount numeric,
    exchange_rate numeric,
    par_exchange_rate numeric,
    narration character varying(1020) COLLATE public.nocase,
    bank_code character varying(128) COLLATE public.nocase,
    analysis_code character varying(20) COLLATE public.nocase,
    subanalysis_code character varying(20) COLLATE public.nocase,
    cost_center character varying(40) COLLATE public.nocase,
    item_code character varying(128) COLLATE public.nocase,
    item_variant character varying(280) COLLATE public.nocase,
    quantity numeric,
    tax_post_flag character varying(4) COLLATE public.nocase,
    mac_post_flag character varying(4) COLLATE public.nocase,
    reftran_fbid character varying(80) COLLATE public.nocase,
    reftran_no character varying(72) COLLATE public.nocase,
    reftran_ou integer,
    ref_tran_type character varying(160) COLLATE public.nocase,
    supcust_code character varying(72) COLLATE public.nocase,
    uom character varying(60) COLLATE public.nocase,
    mac_inc_flag character varying(48) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    fin_year_code character varying(60) COLLATE public.nocase,
    fin_period_code character varying(60) COLLATE public.nocase,
    updated_flag character varying(48) COLLATE public.nocase,
    recon_date timestamp without time zone,
    hdrremarks character varying(1024) COLLATE public.nocase,
    mlremarks character varying(1024) COLLATE public.nocase,
    isrepupdated character varying(48) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    afe_number character varying(72) COLLATE public.nocase,
    job_number character varying(72) COLLATE public.nocase,
    old_batch_id character varying(512) COLLATE public.nocase,
    line_no integer,
    item_tcd_type character varying(48) COLLATE public.nocase,
    consolidated character varying(48) COLLATE public.nocase,
    source_comp character varying(64) COLLATE public.nocase,
    defermentamount numeric DEFAULT 0,
    ari_upd_flag character varying(48) DEFAULT 'N'::character varying COLLATE public.nocase,
    rowtype character varying(100) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);