CREATE TABLE stg.stg_tms_plpph_planning_profile_hdr (
    plpph_ouinstance integer NOT NULL,
    plpph_profile_id character varying(160) NOT NULL COLLATE public.nocase,
    plpph_profile_desc character varying(1020) COLLATE public.nocase,
    plpph_profile_status character varying(160) COLLATE public.nocase,
    plpph_default_profile character(4) COLLATE public.nocase,
    plpph_effective_from timestamp without time zone,
    plpph_effective_to timestamp without time zone,
    plpph_behaviour character varying(160) COLLATE public.nocase,
    plpph_active_thu character(4) COLLATE public.nocase,
    plpph_bk_profile_id character varying(160) COLLATE public.nocase,
    plpph_vehicle_profile_id character varying(160) COLLATE public.nocase,
    plpph_equipment_profile_id character varying(160) COLLATE public.nocase,
    plpph_rec_trip_profile_id character varying(160) COLLATE public.nocase,
    plpph_driver_profile_id character varying(160) COLLATE public.nocase,
    plpph_handler_profile_id character varying(160) COLLATE public.nocase,
    plpph_agent_profile_id character varying(160) COLLATE public.nocase,
    plpph_schedule_profile_id character varying(160) COLLATE public.nocase,
    plpph_break_consignment character(4) COLLATE public.nocase,
    plpph_break_booking_request character(4) COLLATE public.nocase,
    plpph_vehicle_pref_with_drivers character(4) COLLATE public.nocase,
    plpph_vehicle_pref_with_equipment character(4) COLLATE public.nocase,
    plpph_start_trip_after character varying(48) COLLATE public.nocase,
    plpph_start_trip_uom character varying(32) COLLATE public.nocase,
    plpph_trip_time_cal_rule character varying(160) COLLATE public.nocase,
    plpph_avg_speed integer,
    plpph_avg_speed_uom character varying(80) COLLATE public.nocase,
    plpph_circuity_factor character varying(48) COLLATE public.nocase,
    plpph_stand_time character varying(48) COLLATE public.nocase,
    plpph_stand_time_uom character varying(80) COLLATE public.nocase,
    plpph_pr_loading_time character varying(48) COLLATE public.nocase,
    plpph_uom character varying(80) COLLATE public.nocase,
    plpph_time character varying(48) COLLATE public.nocase,
    plpph_time_small character varying(48) COLLATE public.nocase,
    plpph_time_medium character varying(48) COLLATE public.nocase,
    plpph_time_large character varying(48) COLLATE public.nocase,
    plpph_trip_delay_tol character varying(48) COLLATE public.nocase,
    plpph_trip_delay_tol_uom character varying(80) COLLATE public.nocase,
    plpph_pr_trip_delay_tol character varying(48) COLLATE public.nocase,
    plpph_pr_trip_delay_tol_uom character varying(80) COLLATE public.nocase,
    plpph_timeslot_confl_res character varying(48) COLLATE public.nocase,
    plpph_created_by character varying(120) COLLATE public.nocase,
    plpph_created_date timestamp without time zone,
    plpph_last_modified_by character varying(120) COLLATE public.nocase,
    plpph_last_modified_date timestamp without time zone,
    plpph_timestamp integer,
    plpph_constraint_vehicle character varying(160) COLLATE public.nocase,
    plpph_constraint_equipment character varying(160) COLLATE public.nocase,
    plpph_constraint_recurring_trip character varying(160) COLLATE public.nocase,
    plpph_constraint_driver character varying(160) COLLATE public.nocase,
    plpph_constraint_handler character varying(160) COLLATE public.nocase,
    plpph_constraint_agent character varying(160) COLLATE public.nocase,
    plpph_constraint_schedule character varying(160) COLLATE public.nocase,
    plpph_constraint_route character varying(160) COLLATE public.nocase,
    plpph_constraint_cost character varying(160) COLLATE public.nocase,
    plpph_constraint_service character varying(160) COLLATE public.nocase,
    plpph_constraint_capacity character varying(160) COLLATE public.nocase,
    plpph_constraint_gene_planning character varying(160) COLLATE public.nocase,
    plpph_pre_load_start character varying(48) COLLATE public.nocase,
    plpph_pre_load_start_uom character varying(160) COLLATE public.nocase,
    plpph_sort_partial_shipments character varying(160) COLLATE public.nocase,
    plpph_thrshold_volume_uti character varying(160) COLLATE public.nocase,
    plpph_thrshold_weight_uti character varying(160) COLLATE public.nocase,
    plpph_un_loading_time character varying(80) COLLATE public.nocase,
    plpph_un_uom character varying(80) COLLATE public.nocase,
    plpph_un_time character varying(48) COLLATE public.nocase,
    plpph_un_time_small character varying(48) COLLATE public.nocase,
    plpph_un_time_medium character varying(48) COLLATE public.nocase,
    plpph_un_time_large character varying(48) COLLATE public.nocase,
    plpph_threshold_time numeric,
    plpph_threshold_time_uom character varying(80) COLLATE public.nocase,
    plpph_create_trip_pick_up character(4) COLLATE public.nocase,
    plpph_chk_dock_door_avl character(4) COLLATE public.nocase,
    plpph_drvy_date_thrhold numeric,
    plpph_drvy_date_thrhold_uom character varying(80) COLLATE public.nocase,
    plpph_planning_mode character varying(160) COLLATE public.nocase,
    plpph_use_ven_rout_verdhas character(4) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE ONLY stg.stg_tms_plpph_planning_profile_hdr
    ADD CONSTRAINT pk_tms_plpph_planning_profile_hdr PRIMARY KEY (plpph_ouinstance, plpph_profile_id);