CREATE TABLE stg.stg_fact_outbound_obd (
    surrogatekey character varying(400) NOT NULL COLLATE public.nocase,
    tran_type character varying(100) NOT NULL COLLATE public.nocase,
    refkey character varying(400) NOT NULL COLLATE public.nocase,
    oub_ou integer NOT NULL,
    oub_loc_code character varying(40) NOT NULL COLLATE public.nocase,
    oub_outbound_ord character varying(72) COLLATE public.nocase,
    oub_prim_rf_dc_typ character varying(1020) COLLATE public.nocase,
    oub_prim_rf_dc_no character varying(72) COLLATE public.nocase,
    oub_prim_rf_dc_date timestamp without time zone,
    oub_orderdate timestamp without time zone,
    oub_ob_status character varying(32) COLLATE public.nocase,
    oub_order_type character varying(160) COLLATE public.nocase,
    oub_order_priority character varying(160) COLLATE public.nocase,
    oub_cust_code character varying(72) COLLATE public.nocase,
    oub_end_cust_ref_doc character varying(72) COLLATE public.nocase,
    oub_refdoctype character varying(32) COLLATE public.nocase,
    oub_refdocno character varying(72) COLLATE public.nocase,
    oub_refdocdate timestamp without time zone,
    oub_itm_lineno integer,
    oub_item_code character varying(128) COLLATE public.nocase,
    oub_itm_order_qty numeric,
    oub_itm_masteruom character varying(40) COLLATE public.nocase,
    oub_itm_deliverydate timestamp without time zone,
    oub_itm_pack_remarks character varying(1020) COLLATE public.nocase,
    oub_itm_cust_itm_code character varying(128) COLLATE public.nocase,
    oub_itm_refdocno1 character varying(72) COLLATE public.nocase,
    oub_itm_refdocno2 character varying(72) COLLATE public.nocase,
    oub_itm_inst character varying(160) COLLATE public.nocase,
    oub_itm_user_def_1 character varying(1020) COLLATE public.nocase,
    oub_itm_user_def_2 numeric,
    oub_itm_user_def_3 character varying(1020) COLLATE public.nocase,
    oub_itm_shelflife numeric,
    oub_itm_stock_sts character varying(160) COLLATE public.nocase,
    oub_itm_arribute1 character varying(200) COLLATE public.nocase,
    oub_itm_arribute2 character varying(200) COLLATE public.nocase,
    oub_itm_arribute3 character varying(200) COLLATE public.nocase,
    oub_itm_arribute4 character varying(200) COLLATE public.nocase,
    oub_itm_arribute5 character varying(200) COLLATE public.nocase,
    oub_itm_kit_lineno integer,
    oub_secrefdoctype1 character varying(160) COLLATE public.nocase,
    oub_secrefdoctype2 character varying(160) COLLATE public.nocase,
    oub_secrefdoctype3 character varying(160) COLLATE public.nocase,
    oub_secrefdocno1 character varying(72) COLLATE public.nocase,
    oub_secrefdocno2 character varying(72) COLLATE public.nocase,
    oub_secrefdocno3 character varying(72) COLLATE public.nocase,
    oub_secrefdocdate1 timestamp without time zone,
    oub_secrefdocdate2 timestamp without time zone,
    oub_secrefdocdate3 timestamp without time zone,
    oub_carriername character varying(160) COLLATE public.nocase,
    oub_shipment_mode character varying(160) COLLATE public.nocase,
    oub_shipment_type character varying(1020) COLLATE public.nocase,
    oub_cnsgn_code_shpto character varying(72) COLLATE public.nocase,
    oub_ship_point_id character varying(72) COLLATE public.nocase,
    oub_address1 character varying(400) COLLATE public.nocase,
    oub_address2 character varying(400) COLLATE public.nocase,
    oub_address3 character varying(400) COLLATE public.nocase,
    oub_unqaddress character varying(160) COLLATE public.nocase,
    oub_postcode character varying(160) COLLATE public.nocase,
    oub_country character varying(160) COLLATE public.nocase,
    oub_state character varying(160) COLLATE public.nocase,
    oub_city character varying(160) COLLATE public.nocase,
    oub_phoneno character varying(80) COLLATE public.nocase,
    oub_delivery_date timestamp without time zone,
    oub_service_from timestamp without time zone,
    oub_service_to timestamp without time zone,
    oub_itm_plan_gd_iss_dt timestamp without time zone,
    oub_itm_plan_dt_iss timestamp without time zone,
    oub_created_by character varying(120) COLLATE public.nocase,
    oub_created_date timestamp without time zone,
    oub_modified_by character varying(120) COLLATE public.nocase,
    oub_modified_date timestamp without time zone,
    oub_userdefined1 character varying(1020) COLLATE public.nocase,
    oub_userdefined2 character varying(1020) COLLATE public.nocase,
    oub_userdefined3 character varying(1020) COLLATE public.nocase,
    oub_operation_status character varying(32) COLLATE public.nocase,
    oub_subservice_type character varying(1020) COLLATE public.nocase,
    oub_shp_name character varying(80) COLLATE public.nocase,
    oub_consolidation_no character varying(160) COLLATE public.nocase,
    oub_bill_to_name character varying(240) COLLATE public.nocase,
    oub_bill_det_addr_line1 character varying(400) COLLATE public.nocase,
    oub_bill_det_addr_line2 character varying(400) COLLATE public.nocase,
    oub_bill_det_post_code character varying(160) COLLATE public.nocase,
    oub_bill_det_country character varying(160) COLLATE public.nocase,
    oub_bill_det_city character varying(160) COLLATE public.nocase,
    oub_bill_det_state character varying(160) COLLATE public.nocase,
    oub_bill_det_phone character varying(80) COLLATE public.nocase,
    oub_bill_det_ship_addr integer,
    oub_consgn_name character varying(600) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE ONLY stg.stg_fact_outbound_obd
    ADD CONSTRAINT pk__fact_out__4cd9458ea53ab33a PRIMARY KEY (refkey);