CREATE TABLE stg.stg_tms_fphm_hub_management_details (
    fphm_ou_instance integer,
    fphm_hub_id character varying(160) COLLATE public.nocase,
    fphm_hub_description character varying(1020) COLLATE public.nocase,
    fphm_hub_status character varying(160) COLLATE public.nocase,
    fphm_timestamp integer,
    fphm_created_by character varying(120) COLLATE public.nocase,
    fphm_created_date timestamp without time zone,
    fphm_last_modified_by character varying(120) COLLATE public.nocase,
    fphm_last_modified_date timestamp without time zone,
    fphm_allow_hub_rec_without character varying(160) COLLATE public.nocase,
    fphm_default_arrival_dock_id character varying(160) COLLATE public.nocase,
    fphm_default_arrival_staging_id character varying(160) COLLATE public.nocase,
    fphm_default_loading_dock_id character varying(160) COLLATE public.nocase,
    fphm_default_loading_staging_id character varying(160) COLLATE public.nocase,
    fphm_default_excess_bay_id character varying(160) COLLATE public.nocase,
    fphm_auto_confirm_br character varying(160) COLLATE public.nocase,
    fphm_create_trip_load_confm character varying(160) COLLATE public.nocase,
    fphm_default_docu_hub_receipt character varying(160) COLLATE public.nocase,
    fphm_default_docu_hub_loading character varying(160) COLLATE public.nocase,
    fphm_auto_conf_hub_tran_trip character varying(160) COLLATE public.nocase,
    fphm_auto_conf_trip_tran character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);