CREATE TABLE stg.stg_tcal_tran_hdr (
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    tax_type character varying(100) NOT NULL COLLATE public.nocase,
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tax_community character varying(100) NOT NULL COLLATE public.nocase,
    tran_date timestamp without time zone NOT NULL,
    applicable_flag character(4) NOT NULL COLLATE public.nocase,
    company_code character varying(40) NOT NULL COLLATE public.nocase,
    buid character varying(80) NOT NULL COLLATE public.nocase,
    fbid character varying(80) NOT NULL COLLATE public.nocase,
    tran_curr character(20) NOT NULL COLLATE public.nocase,
    incl_option character varying(32) NOT NULL COLLATE public.nocase,
    tax_excl_amt numeric NOT NULL,
    tax_incl_amt numeric NOT NULL,
    tran_amt numeric,
    comp_tax_amt numeric NOT NULL,
    corr_tax_amt numeric NOT NULL,
    party_type character varying(32) COLLATE public.nocase,
    supp_cust_code character varying(72) COLLATE public.nocase,
    assessee_type character varying(160) COLLATE public.nocase,
    cap_deduct_charge character varying(32) NOT NULL COLLATE public.nocase,
    bas_exch_rate numeric NOT NULL,
    pbas_exch_rate numeric,
    comp_tax_amt_bascurr numeric NOT NULL,
    corr_tax_amt_bascurr numeric NOT NULL,
    nontax_tc_amt numeric NOT NULL,
    nontax_disc_amt numeric NOT NULL,
    component_name character varying(160) NOT NULL COLLATE public.nocase,
    original_tran_no character varying(72) COLLATE public.nocase,
    reversed_tran_no character varying(72) COLLATE public.nocase,
    doc_status character varying(32) NOT NULL COLLATE public.nocase,
    tax_status character varying(32) NOT NULL COLLATE public.nocase,
    tax_adj_status character varying(32) COLLATE public.nocase,
    cert_recd_status character varying(32) NOT NULL COLLATE public.nocase,
    dr_cr_flag character varying(32) COLLATE public.nocase,
    usage_id character varying(128) COLLATE public.nocase,
    trade_type character varying(32) COLLATE public.nocase,
    tax_on character varying(32) COLLATE public.nocase,
    addnl_param1 integer,
    addnl_param2 numeric,
    addnl_param3 character varying(160) COLLATE public.nocase,
    addnl_param4 character varying(1020) COLLATE public.nocase,
    created_at integer NOT NULL,
    created_by character varying(120) NOT NULL COLLATE public.nocase,
    created_date timestamp without time zone NOT NULL,
    modified_by character varying(120) NOT NULL COLLATE public.nocase,
    modified_date timestamp without time zone NOT NULL,
    "timestamp" integer NOT NULL,
    receipt_type character varying(4) COLLATE public.nocase,
    tax_amt_invoiced numeric,
    threshold_flag character varying(48) COLLATE public.nocase,
    capital_flag character varying(160) COLLATE public.nocase,
    ttran_taxable_amt numeric,
    ttran_tax_amt numeric,
    post_date timestamp without time zone,
    tcal_pdc_flag character varying(48) COLLATE public.nocase,
    prop_wht_amt numeric,
    app_wht_amt numeric,
    supp_inv_no character varying(400) COLLATE public.nocase,
    supp_inv_date timestamp without time zone,
    supp_inv_amount numeric,
    ack_no character varying(1000) COLLATE public.nocase,
    nature_of_reason character varying COLLATE public.nocase,
    sec_heading character varying(100) COLLATE public.nocase,
    sub_heading character varying(100) COLLATE public.nocase,
    eway_bill_no character varying(1020) COLLATE public.nocase,
    valid_upto character varying(1020) COLLATE public.nocase,
    eway_bill_date character varying(1020) COLLATE public.nocase,
    original_supp_inv_no character varying(400) COLLATE public.nocase,
    recon_sup_tax_inv_flag character(4) DEFAULT 'N'::bpchar NOT NULL COLLATE public.nocase,
    gstr2a_classification character varying(160) COLLATE public.nocase,
    aadhaar_no character varying(160) COLLATE public.nocase,
    pan_no character varying(160) COLLATE public.nocase,
    einv_qrcode character varying(2000) COLLATE public.nocase,
    invrefnum character varying(64) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);