CREATE TABLE stg.stg_wms_customer_hdr (
    wms_customer_id character varying(72) NOT NULL COLLATE public.nocase,
    wms_customer_ou integer NOT NULL,
    wms_customer_name character varying(160) COLLATE public.nocase,
    wms_customer_status character varying(32) COLLATE public.nocase,
    wms_customer_type character varying(32) COLLATE public.nocase,
    wms_customer_description character varying(1020) COLLATE public.nocase,
    wms_customer_credit_term character varying(80) COLLATE public.nocase,
    wms_customer_pay_term character varying(60) COLLATE public.nocase,
    wms_customer_currency character(20) COLLATE public.nocase,
    wms_customer_reason_code character varying(160) COLLATE public.nocase,
    wms_customer_address1 character varying(600) COLLATE public.nocase,
    wms_customer_address2 character varying(600) COLLATE public.nocase,
    wms_customer_address3 character varying(600) COLLATE public.nocase,
    wms_customer_unique_address character varying(160) COLLATE public.nocase,
    wms_customer_city character varying(160) COLLATE public.nocase,
    wms_customer_state character varying(160) COLLATE public.nocase,
    wms_customer_country character varying(160) COLLATE public.nocase,
    wms_customer_postal_code character varying(160) COLLATE public.nocase,
    wms_customer_timezone character varying(160) COLLATE public.nocase,
    wms_customer_contact_person character varying(180) COLLATE public.nocase,
    wms_customer_phone1 character varying(72) COLLATE public.nocase,
    wms_customer_phone2 character varying(72) COLLATE public.nocase,
    wms_customer_fax character varying(160) COLLATE public.nocase,
    wms_customer_email character varying(240) COLLATE public.nocase,
    wms_customer_bill_same_as_customer integer,
    wms_customer_bill_address1 character varying(600) COLLATE public.nocase,
    wms_customer_bill_address2 character varying(600) COLLATE public.nocase,
    wns_customer_bill_address3 character varying(600) COLLATE public.nocase,
    wms_customer_bill_unique_address character varying(160) COLLATE public.nocase,
    wms_customer_bill_city character varying(160) COLLATE public.nocase,
    wms_customer_bill_state character varying(160) COLLATE public.nocase,
    wms_customer_bill_country character varying(160) COLLATE public.nocase,
    wms_customer_bill_postal_code character varying(160) COLLATE public.nocase,
    wms_customer_bill_contact_person character varying(180) COLLATE public.nocase,
    wms_customer_bill_phone character varying(72) COLLATE public.nocase,
    wms_customer_bill_fax character varying(160) COLLATE public.nocase,
    wms_customer_ret_undelivered character varying(32) COLLATE public.nocase,
    wms_customer_ret_same_as_customer integer,
    wms_customer_ret_address1 character varying(600) COLLATE public.nocase,
    wms_customer_ret_address2 character varying(600) COLLATE public.nocase,
    wms_customer_ret_address3 character varying(600) COLLATE public.nocase,
    wms_customer_ret_unique_address character varying(160) COLLATE public.nocase,
    wms_customer_ret_city character varying(160) COLLATE public.nocase,
    wms_customer_ret_state character varying(160) COLLATE public.nocase,
    wms_customer_ret_country character varying(160) COLLATE public.nocase,
    wms_customer_ret_postal_code character varying(160) COLLATE public.nocase,
    wms_customer_ret_contact_person character varying(180) COLLATE public.nocase,
    wms_customer_ret_phone1 character varying(72) COLLATE public.nocase,
    wms_customer_ret_fax character varying(160) COLLATE public.nocase,
    wms_customer_timestamp integer,
    wms_customer_userdefined1 character varying(1020) COLLATE public.nocase,
    wms_customer_userdefined2 character varying(1020) COLLATE public.nocase,
    wms_customer_userdefined3 character varying(1020) COLLATE public.nocase,
    wms_customer_created_by character varying(120) COLLATE public.nocase,
    wms_customer_created_dt timestamp without time zone,
    wms_customer_modified_by character varying(120) COLLATE public.nocase,
    wms_customer_modified_dt timestamp without time zone,
    wms_customer_route character varying(72) COLLATE public.nocase,
    wms_customer_br_valid_prof_id character varying(160) COLLATE public.nocase,
    wms_customer_payment_typ character varying(1020) COLLATE public.nocase,
    wms_customer_geo_fence numeric,
    wms_customer_longtitude numeric,
    wms_customer_latitude numeric,
    wms_customer_zone character varying(160) COLLATE public.nocase,
    wms_customer_sub_zone character varying(160) COLLATE public.nocase,
    wms_customer_region character varying(160) COLLATE public.nocase,
    wms_customer_bill_geo_fence numeric,
    wms_customer_bill_longtitude numeric,
    wms_customer_bill_latitude numeric,
    wms_customer_bill_zone character varying(160) COLLATE public.nocase,
    wms_customer_bill_sub_zone character varying(160) COLLATE public.nocase,
    wms_customer_bill_region character varying(160) COLLATE public.nocase,
    wms_customer_bill_timezone character varying(160) COLLATE public.nocase,
    wms_customer_ret_geo_fence numeric,
    wms_customer_ret_longtitude numeric,
    wms_customer_ret_latitude numeric,
    wms_customer_ret_zone character varying(160) COLLATE public.nocase,
    wms_customer_ret_sub_zone character varying(160) COLLATE public.nocase,
    wms_customer_ret_region character varying(160) COLLATE public.nocase,
    wms_customer_ret_timezone character varying(160) COLLATE public.nocase,
    wms_customer_customer_grp character varying(160) COLLATE public.nocase,
    wms_customer_industry_typ character varying(160) COLLATE public.nocase,
    wms_customer_lsp character varying(64) COLLATE public.nocase,
    wms_customer_url character varying(1020) COLLATE public.nocase,
    wms_customer_reg character varying(160) COLLATE public.nocase,
    wms_customer_dept character varying(160) COLLATE public.nocase,
    wms_customer_ln_business character varying(160) COLLATE public.nocase,
    wms_allow_rev_protection integer,
    wms_customer_invrep character varying(1020) COLLATE public.nocase,
    wms_customer_lspemail character varying(240) COLLATE public.nocase,
    wms_customer_lspname character varying(160) COLLATE public.nocase,
    wms_customer_packing_bay character varying(72) COLLATE public.nocase,
    wms_customer_route_no character varying(72) COLLATE public.nocase,
    wms_customer_lspid character varying(64) COLLATE public.nocase,
    wms_customer_finance_grp character varying(160) COLLATE public.nocase,
    wms_customer_rcti integer,
    wms_customer_gen_from character varying(100) COLLATE public.nocase,
    wms_customer_cont_derivation character varying(160) COLLATE public.nocase,
    wms_customer_bill_hrchy1 character varying(160) COLLATE public.nocase,
    wms_customer_bill_hrchy2 character varying(160) COLLATE public.nocase,
    wms_customer_bill_hrchy3 character varying(160) COLLATE public.nocase,
    wms_customer_chnl_type character varying(160) COLLATE public.nocase,
    wms_customer_seller_type character varying(160) COLLATE public.nocase,
    wms_customer_profile_id character varying(160) COLLATE public.nocase,
    wms_customer_new_customer integer,
    wms_customer_final_bill_stage character varying(160) COLLATE public.nocase,
    wms_bank_name character varying(160) COLLATE public.nocase,
    wms_bank_acc_no character varying(160) COLLATE public.nocase,
    wms_bank_ifsc_code character varying(160) COLLATE public.nocase,
    wms_prospect_customer_yn character(4) COLLATE public.nocase,
    wms_customer_allwdb_billto character varying(1020) COLLATE public.nocase,
    wms_customer_suburb character varying(1020) COLLATE public.nocase,
    wms_customer_contact_person2 character varying(180) COLLATE public.nocase,
    wms_cus_contact_person2_phone1 character varying(72) COLLATE public.nocase,
    wms_cus_contact_person2_phone2 character varying(72) COLLATE public.nocase,
    wms_cus_contact_person2_fax character varying(160) COLLATE public.nocase,
    wms_cus_contact_person2_email character varying(240) COLLATE public.nocase,
    wms_cus_contact_person2_url character varying(160) COLLATE public.nocase,
    wms_customer_tempid character varying(72) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);