CREATE TABLE stg.stg_tms_brrd_br_recurring_details (
    brrd_ouinstance integer NOT NULL,
    brrd_br_id character varying(72) NOT NULL COLLATE public.nocase,
    brrd_pick_up_point_id character varying(72) COLLATE public.nocase,
    brrd_pick_up_point_name character varying(160) COLLATE public.nocase,
    brrd_contact_person character varying(180) COLLATE public.nocase,
    brrd_address_line1 character varying(160) COLLATE public.nocase,
    brrd_address_line2 character varying(160) COLLATE public.nocase,
    brrd_address_line3 character varying(160) COLLATE public.nocase,
    brrd_postal_code character varying(160) COLLATE public.nocase,
    brrd_subzone character varying(160) COLLATE public.nocase,
    brrd_city character varying(160) COLLATE public.nocase,
    brrd_zone character varying(160) COLLATE public.nocase,
    brrd_state character varying(160) COLLATE public.nocase,
    brrd_region character varying(160) COLLATE public.nocase,
    brrd_country character varying(160) COLLATE public.nocase,
    brrd_primary_phone character varying(160) COLLATE public.nocase,
    brrd_secondary_phone character varying(160) COLLATE public.nocase,
    brrd_picktime_slot_from timestamp without time zone,
    brrd_picktime_slot_to timestamp without time zone,
    brrd_recurring_from_date timestamp without time zone,
    brrd_recurring_to_date timestamp without time zone,
    brrd_monday character(4) COLLATE public.nocase,
    brrd_tuesday character(4) COLLATE public.nocase,
    brrd_wednesday character(4) COLLATE public.nocase,
    brrd_thursday character(4) COLLATE public.nocase,
    brrd_friday character(4) COLLATE public.nocase,
    brrd_saturday character(4) COLLATE public.nocase,
    brrd_sunday character(4) COLLATE public.nocase,
    brrd_last_modified_date timestamp without time zone,
    brrd_last_modified_by character varying(120) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);