CREATE TABLE stg.stg_wms_item_hdr (
    wms_itm_ou integer NOT NULL,
    wms_itm_code character varying(128) NOT NULL COLLATE public.nocase,
    wms_itm_short_desc character varying(2000) COLLATE public.nocase,
    wms_itm_long_desc character varying(3000) COLLATE public.nocase,
    wms_itm_mas_unit character varying(40) COLLATE public.nocase,
    wms_itm_customer character varying(72) COLLATE public.nocase,
    wms_itm_class character varying(160) COLLATE public.nocase,
    wms_itm_status character(8) COLLATE public.nocase,
    wms_itm_ref_no character varying(128) COLLATE public.nocase,
    wms_itm_subs_item1 character varying(128) COLLATE public.nocase,
    wms_itm_subs_item2 character varying(128) COLLATE public.nocase,
    wms_itm_hs_code character varying(60) COLLATE public.nocase,
    wms_itm_price numeric,
    wms_itm_currency character(20) COLLATE public.nocase,
    wms_itm_tracking character varying(80) COLLATE public.nocase,
    wms_itm_lot_numbering character varying(40) COLLATE public.nocase,
    wms_itm_serial_numbering character varying(40) COLLATE public.nocase,
    wms_itm_remarks character varying(4000) COLLATE public.nocase,
    wms_itm_instructions character varying(4000) COLLATE public.nocase,
    wms_itm_hazardous integer,
    wms_itm_hazmat_no character varying(280) COLLATE public.nocase,
    wms_itm_hazard_class character varying(160) COLLATE public.nocase,
    wms_itm_length numeric,
    wms_itm_breadth numeric,
    wms_itm_height numeric,
    wms_itm_uom character varying(40) COLLATE public.nocase,
    wms_itm_volume numeric,
    wms_itm_volume_uom character varying(40) COLLATE public.nocase,
    wms_itm_weight numeric,
    wms_itm_weight_uom character varying(40) COLLATE public.nocase,
    wms_itm_storage_from_temp integer,
    wms_itm_storage_to_temp integer,
    wms_itm_storage_temp_uom character varying(32) COLLATE public.nocase,
    wms_itm_shelf_life integer,
    wms_itm_shelf_life_uom character varying(40) COLLATE public.nocase,
    wms_itm_timestamp integer,
    wms_itm_created_by character varying(120) COLLATE public.nocase,
    wms_itm_created_dt timestamp without time zone,
    wms_itm_modified_by character varying(120) COLLATE public.nocase,
    wms_itm_modified_dt timestamp without time zone,
    wms_itm_reason_code character varying(160) COLLATE public.nocase,
    wms_itm_type character varying(160) COLLATE public.nocase,
    wms_itm_user_defined1 character varying(1020) COLLATE public.nocase,
    wms_itm_user_defined2 character varying(1020) COLLATE public.nocase,
    wms_itm_user_defined3 character varying(1020) COLLATE public.nocase,
    wms_itm_itemgroup character varying(160) COLLATE public.nocase,
    wms_itm_criticaldays integer,
    wms_itm_criticaldays_uom character varying(40) COLLATE public.nocase,
    wms_itm_movement_type character varying(160) COLLATE public.nocase,
    wms_itm_volume_factor numeric,
    wms_itm_volume_weight numeric,
    wms_itm_item_url character varying COLLATE public.nocase,
    wms_itm_compilance character varying(160) COLLATE public.nocase,
    wms_itm_operation_type character varying(160) COLLATE public.nocase,
    wms_itm_new_item integer,
    wms_itm_customer_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_warranty_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_gift_card_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_oe_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_oub_customer_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_oub_warranty_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_oub_gift_card_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_oub_oe_serial_no character varying(1020) COLLATE public.nocase,
    wms_itm_inbound character varying(1020) COLLATE public.nocase,
    wms_itm_outbound character varying(1020) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);