CREATE TABLE stg.stg_snp_voucher_hdr (
    ou_id integer NOT NULL,
    voucher_no character varying(72) NOT NULL COLLATE public.nocase,
    voucher_type character varying(16) NOT NULL COLLATE public.nocase,
    tran_type character varying(160) NOT NULL COLLATE public.nocase,
    vtimestamp integer NOT NULL,
    fb_id character varying(80) COLLATE public.nocase,
    notype_no character varying(40) COLLATE public.nocase,
    request_date timestamp without time zone,
    payee_name character varying(640) COLLATE public.nocase,
    pay_date timestamp without time zone,
    elec_payment character varying(16) COLLATE public.nocase,
    pay_currency character varying(20) COLLATE public.nocase,
    exchange_rate numeric,
    pay_amount_bef_roff numeric,
    pay_amount numeric,
    roundoff_amount numeric,
    pay_method character varying(120) COLLATE public.nocase,
    payment_route character varying(16) COLLATE public.nocase,
    pay_mode character varying(100) COLLATE public.nocase,
    bank_cash_code character varying(128) COLLATE public.nocase,
    relpay_ou integer,
    instr_charge character varying(16) COLLATE public.nocase,
    priority character varying(16) COLLATE public.nocase,
    remarks character varying(1020) COLLATE public.nocase,
    hr_reason_code character varying(40) COLLATE public.nocase,
    hr_remarks character varying(1020) COLLATE public.nocase,
    reversal_reason_code character varying(40) COLLATE public.nocase,
    reversal_date timestamp without time zone,
    reversal_remarks character varying(1020) COLLATE public.nocase,
    address1 character varying(160) COLLATE public.nocase,
    address2 character varying(160) COLLATE public.nocase,
    address3 character varying(160) COLLATE public.nocase,
    city character varying(160) COLLATE public.nocase,
    state character varying(160) COLLATE public.nocase,
    country character varying(160) COLLATE public.nocase,
    zip_code character varying(80) COLLATE public.nocase,
    contact character varying(160) COLLATE public.nocase,
    url character varying(200) COLLATE public.nocase,
    mail_stop character varying(80) COLLATE public.nocase,
    pager_no character varying(80) COLLATE public.nocase,
    email_id character varying(240) COLLATE public.nocase,
    telex character varying(80) COLLATE public.nocase,
    phone_no character varying(80) COLLATE public.nocase,
    mobile_no character varying(80) COLLATE public.nocase,
    fax_no character varying(80) COLLATE public.nocase,
    lsv_id character varying(120) COLLATE public.nocase,
    lsv_reference character varying(160) COLLATE public.nocase,
    bank_code character varying(128) COLLATE public.nocase,
    partid_digits character varying(120) COLLATE public.nocase,
    esr_id character varying(120) COLLATE public.nocase,
    refno_digits integer,
    esr_reference character varying(120) COLLATE public.nocase,
    esr_amount numeric,
    esr_code_line character varying(512) COLLATE public.nocase,
    payee_accountin character varying(80) COLLATE public.nocase,
    payee_bankrefno character varying(80) COLLATE public.nocase,
    payee_accountcode character varying(128) COLLATE public.nocase,
    comp_accountin character varying(80) COLLATE public.nocase,
    comp_bankref character varying(80) COLLATE public.nocase,
    comp_accountcode character varying(128) COLLATE public.nocase,
    template_no character varying(72) COLLATE public.nocase,
    cap_charge character varying(16) COLLATE public.nocase,
    batch_id character varying(512) COLLATE public.nocase,
    voucher_status character varying(8) COLLATE public.nocase,
    refdoc_no character varying(72) COLLATE public.nocase,
    refdoc_type character varying(160) COLLATE public.nocase,
    pbcexchrate numeric,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    doc_status character varying(48) COLLATE public.nocase,
    contract_ref character varying(160) COLLATE public.nocase,
    elec_applied character varying(48) COLLATE public.nocase,
    iban_no character varying(80) COLLATE public.nocase,
    tcal_status character varying(48) COLLATE public.nocase,
    total_tcal_amount numeric,
    tcal_exclusive_amt numeric,
    receipt_route character varying(16) COLLATE public.nocase,
    auto_gen_flag character varying(48) COLLATE public.nocase,
    consistency_stamp character varying(48) COLLATE public.nocase,
    receipt_ou integer,
    workflow_status character varying(80) COLLATE public.nocase,
    recon_reqflg character varying(48) COLLATE public.nocase,
    afe_number character varying(72) COLLATE public.nocase,
    job_number character varying(72) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    costcenter_hdr character varying(40) COLLATE public.nocase,
    workflow_error character varying(72) COLLATE public.nocase,
    ifb_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);