CREATE TABLE stg.stg_tms_vdeph_equipment_profile_hdr (
    vdeph_ouinstance integer NOT NULL,
    vdeph_profile_id character varying(160) NOT NULL COLLATE public.nocase,
    vdeph_active_profile_run_no character varying(72) COLLATE public.nocase,
    vdeph_active_profile_run_date timestamp without time zone,
    vdeph_default_profile character(4) COLLATE public.nocase,
    vdeph_profile_desc character varying(1020) COLLATE public.nocase,
    vdeph_status character varying(160) COLLATE public.nocase,
    vdeph_home_location character varying(160) COLLATE public.nocase,
    vdeph_attached_to_location character(4) COLLATE public.nocase,
    vdeph_cd_from_home_loc_uom character varying(160) COLLATE public.nocase,
    vdeph_min_cd_from_home_loc integer,
    vdeph_max_cd_from_home_loc integer,
    vdeph_cd_from_planning_loc_uom character varying(160) COLLATE public.nocase,
    vdeph_min_cd_from_planning_loc integer,
    vdeph_max_cd_from_planning_loc integer,
    vdeph_attached_to_vehicle character(4) COLLATE public.nocase,
    vdeph_likely_ava_on_date timestamp without time zone,
    vdeph_likely_ava_from_date timestamp without time zone,
    vdeph_likely_ava_to_date timestamp without time zone,
    vdeph_equipment_reg_no character varying(160) COLLATE public.nocase,
    vdeph_allowed_weight_uom character varying(160) COLLATE public.nocase,
    vdeph_min_allowed_weight integer,
    vdeph_max_allowed_weight integer,
    vdeph_profile_division character varying(40) COLLATE public.nocase,
    vdeph_profile_location character varying(80) COLLATE public.nocase,
    vdeph_created_by character varying(120) COLLATE public.nocase,
    vdeph_created_date timestamp without time zone,
    vdeph_last_modified_by character varying(120) COLLATE public.nocase,
    vdeph_last_modified_date timestamp without time zone,
    vdeph_timestamp integer,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);