CREATE TABLE stg.stg_tms_ffhd_freight_forwarding_hub_dtl (
    ffhub_ouinstance integer,
    ffhd_unique_line_no character varying(512) COLLATE public.nocase,
    ffhub_br_id character varying(160) COLLATE public.nocase,
    ffhub_trip_id character varying(160) COLLATE public.nocase,
    ffhub_trip_guid character varying(512) COLLATE public.nocase,
    ffhub_ld_leg_id character varying(160) COLLATE public.nocase,
    ffhub_ld_beh_hdn character varying(160) COLLATE public.nocase,
    ffhub_ld_beh character varying(1020) COLLATE public.nocase,
    ffhub_ld_fr_hdr character varying(1020) COLLATE public.nocase,
    ffhub_ld_to_hdr character varying(1020) COLLATE public.nocase,
    ffhub_ld_fr_dtl character varying(1020) COLLATE public.nocase,
    ffhub_ld_to_dtl character varying(1020) COLLATE public.nocase,
    ffhub_ld_dist character varying(160) COLLATE public.nocase,
    ffhub_ld_time character varying(160) COLLATE public.nocase,
    ffhub_sd_sch_id character varying(160) COLLATE public.nocase,
    ffhub_sd_rail_car character varying(160) COLLATE public.nocase,
    ffhub_sd_rc_dtl character varying(1020) COLLATE public.nocase,
    ffhub_sd_from character varying(1020) COLLATE public.nocase,
    ffhub_sd_from_time character varying(160) COLLATE public.nocase,
    ffhub_sd_to character varying(1020) COLLATE public.nocase,
    ffhub_sd_to_time character varying(160) COLLATE public.nocase,
    ffhub_td_tp_id character varying(160) COLLATE public.nocase,
    ffhub_td_status character varying(160) COLLATE public.nocase,
    ffhub_td_pl_cost character varying(160) COLLATE public.nocase,
    ffhub_td_start_date character varying(160) COLLATE public.nocase,
    ffhub_td_start_time character varying(160) COLLATE public.nocase,
    ffhub_td_end_date character varying(160) COLLATE public.nocase,
    ffhub_td_end_time character varying(160) COLLATE public.nocase,
    ffhub_cd_tariff character varying(160) COLLATE public.nocase,
    ffhub_cd_tar_cost character varying(160) COLLATE public.nocase,
    ffhub_cd_spot_cost numeric,
    ffhub_vd_ven_id character varying(160) COLLATE public.nocase,
    ffhub_ven_cap character varying(160) COLLATE public.nocase,
    ffhub_bk_req_cap character varying(160) COLLATE public.nocase,
    ffhub_remain_cap character varying(160) COLLATE public.nocase,
    ffhub_created_by character varying(120) COLLATE public.nocase,
    ffhub_created_date timestamp without time zone,
    ffhub_last_modified_by character varying(120) COLLATE public.nocase,
    ffhub_last_modified_date timestamp without time zone,
    ffhub_timestamp integer,
    ffhub_thu_serialno character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);