CREATE TABLE stg.stg_tms_brctdh_br_thu_wise_contract_tariff_dtls_history (
    brctdh_ou integer NOT NULL,
    brctdh_br_id character varying(72) NOT NULL COLLATE public.nocase,
    brctdh_thu_line_no character varying(512) COLLATE public.nocase,
    brctdh_contract_id character varying(72) COLLATE public.nocase,
    brctdh_cont_type character varying(32) COLLATE public.nocase,
    brctdh_cont_service_type character varying(160) COLLATE public.nocase,
    brctdh_cont_valid_from timestamp without time zone,
    brctdh_cont_valid_to timestamp without time zone,
    brctdh_tariff_id character varying(72) COLLATE public.nocase,
    brctdh_tf_tp_type_code character varying(32) COLLATE public.nocase,
    brctdh_tf_tp_division character varying(64) COLLATE public.nocase,
    brctdh_tf_tp_location character varying(64) COLLATE public.nocase,
    brctdh_tf_tp_validity_id character varying(72) COLLATE public.nocase,
    brctdh_tf_tp_frm_ship_point character varying(72) COLLATE public.nocase,
    brctdh_tf_tp_to_ship_point character varying(72) COLLATE public.nocase,
    brctdh_tf_tp_frm_geo_type character varying(32) COLLATE public.nocase,
    brctdh_tf_tp_frm_geo character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_to_geo_type character varying(32) COLLATE public.nocase,
    brctdh_tf_tp_to_geo character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_dist_check integer,
    brctdh_tf_tp_dist_min numeric,
    brctdh_tf_tp_dist_max numeric,
    brctdh_tf_tp_dist_uom character varying(40) COLLATE public.nocase,
    brctdh_tf_tp_wt integer,
    brctdh_tf_tp_wt_min numeric,
    brctdh_tf_tp_wt_max numeric,
    brctdh_tf_tp_wt_uom character varying(40) COLLATE public.nocase,
    brctdh_tf_tp_vol integer,
    brctdh_tf_tp_vol_min numeric,
    brctdh_tf_tp_vol_max numeric,
    brctdh_tf_tp_vol_uom character varying(40) COLLATE public.nocase,
    brctdh_tf_tp_trip_time integer,
    brctdh_tf_tp_trip_time_min numeric,
    brctdh_tf_tp_trip_time_max numeric,
    brctdh_tf_tp_trip_time_uom character varying(40) COLLATE public.nocase,
    brctdh_tf_tp_vol_conversion numeric,
    brctdh_tf_tp_service character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_sub_service character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_thu_type character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_min_no_thu numeric,
    brctdh_tf_tp_max_no_thu numeric,
    brctdh_tf_tp_class_of_stores character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_thu_space_frm numeric,
    brctdh_tf_tp_thu_space_to numeric,
    brctdh_tf_tp_equip_type character varying(160) COLLATE public.nocase,
    brctdh_tf_tp_veh_type character varying(160) COLLATE public.nocase,
    brctdh_billable_weight numeric,
    brctdh_rate_for_billable_weight numeric,
    brctdh_stage_of_tariff_derivation character varying(160) COLLATE public.nocase,
    brctdh_staging_ref_document character varying(72) COLLATE public.nocase,
    brctdh_created_by character varying(120) COLLATE public.nocase,
    brctdh_created_date timestamp without time zone,
    brctdh_last_modified_by character varying(120) COLLATE public.nocase,
    brctdh_last_modified_date timestamp without time zone,
    brctdh_timestamp integer,
    brctdh_cont_amend_no integer,
    brctdh_billable_quantity numeric,
    brctdh_dd_br_volume numeric,
    brctdh_no_of_pallet numeric,
    brctdh_actual_weight numeric,
    brctdh_actual_weight_uom character varying(60) COLLATE public.nocase,
    brctdh_actual_volume numeric,
    brctdh_actual_volume_uom character varying(60) COLLATE public.nocase,
    brctdh_basic_charge numeric,
    brctdh_cont_min_charge numeric,
    brctdh_leg_behaviour_id character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);