CREATE TABLE stg.stg_wms_inbound_item_detail (
    wms_inb_loc_code character varying(160) NOT NULL COLLATE public.nocase,
    wms_inb_orderno character varying(1020) NOT NULL COLLATE public.nocase,
    wms_inb_lineno integer NOT NULL,
    wms_inb_ou integer NOT NULL,
    wms_inb_item_code character varying(128) COLLATE public.nocase,
    wms_inb_order_qty numeric,
    wms_inb_alt_uom character varying(40) COLLATE public.nocase,
    wms_inb_sch_type character varying(1020) COLLATE public.nocase,
    wms_inb_receipt_date timestamp without time zone,
    wms_inb_item_inst character varying(1020) COLLATE public.nocase,
    wms_inb_supp_code character varying(64) COLLATE public.nocase,
    wms_inb_addressid character varying(24) COLLATE public.nocase,
    wms_inb_balqty numeric,
    wms_inb_linestatus character varying(1020) COLLATE public.nocase,
    wms_inb_recdqty numeric,
    wms_inb_accpdqty numeric,
    wms_inb_returnedqty numeric,
    wms_inb_itm_grrejdqty numeric,
    wms_inb_itm_grmovdqty numeric,
    wms_inb_operation_status character varying(32) COLLATE public.nocase,
    wms_inb_cust_item_code character varying(128) COLLATE public.nocase,
    wms_inb_master_uom_qty numeric,
    wms_inb_stock_status character varying(160) COLLATE public.nocase,
    wms_inb_itm_cust character varying(72) COLLATE public.nocase,
    wms_inb_cust_po_lineno integer,
    wms_inb_batch_no character varying(112) COLLATE public.nocase,
    wms_inb_oe_serial_no character varying(112) COLLATE public.nocase,
    wms_inb_wr_serial_no character varying(112) COLLATE public.nocase,
    wms_inb_expiry_date timestamp without time zone,
    wms_inb_manu_date timestamp without time zone,
    wms_inb_best_before_date timestamp without time zone,
    wms_inb_thu_id character varying(160) COLLATE public.nocase,
    wms_inb_thu_desc character varying(1020) COLLATE public.nocase,
    wms_inb_thu_qty numeric,
    wms_inb_user_def_1 character varying(1020) COLLATE public.nocase,
    wms_inb_user_def_2 character varying(1020) COLLATE public.nocase,
    wms_inb_user_def_3 character varying(1020) COLLATE public.nocase,
    wms_inb_lottable1 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable2 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable3 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable4 timestamp without time zone,
    wms_inb_lottable5 timestamp without time zone,
    wms_inb_lottable6 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable7 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable8 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable9 character varying(1024) COLLATE public.nocase,
    wms_inb_lottable10 character varying(1024) COLLATE public.nocase,
    wms_inb_component integer,
    wms_inb_retnlabl_bil_status character varying(32) COLLATE public.nocase,
    wms_inb_retnhand_bil_status character varying(32) COLLATE public.nocase,
    wms_asn_kit_item_lineno integer,
    wms_asn_lineno integer,
    wms_asn_item_po_lineno integer,
    wms_inb_su1 character varying(40) COLLATE public.nocase,
    wms_inb_uid1 character varying(112) COLLATE public.nocase,
    wms_inb_su2 character varying(40) COLLATE public.nocase,
    wms_inb_uid2 character varying(112) COLLATE public.nocase,
    wms_inb_hilnitgr_bil_status character varying(32) COLLATE public.nocase,
    wms_inb_item_attribute1 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute2 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute3 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute4 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute5 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute6 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute7 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute8 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute9 character varying(1020) COLLATE public.nocase,
    wms_inb_item_attribute10 character varying(1020) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);