CREATE TABLE IF NOT EXISTS stg.stg_tcal_tax_dtl
(
    tax_type character varying(50) COLLATE public.nocase,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    tran_ou integer,
    tran_line_no integer,
    tax_line_no integer,
    tax_code character varying(20) COLLATE public.nocase,
    code_type character varying(20) COLLATE public.nocase,
    tax_rate numeric(20,2),
    tax_basis character varying(10) COLLATE public.nocase,
    taxable_amt numeric(20,2),
    comp_tax_amt numeric(20,2),
    corr_tax_amt numeric(20,2),
    comp_tax_amt_bascurr numeric(20,2),
    corr_tax_amt_bascurr numeric(20,2),
    addnl_param1 integer,
    addnl_param2 numeric(20,2),
    addnl_param3 character varying(40) COLLATE pg_catalog."default",
    addnl_param4 character varying(255) COLLATE pg_catalog."default",
    created_by character varying(60) COLLATE public.nocase,
    created_date timestamp without time zone,
    modified_by character varying(60) COLLATE public.nocase,
    modified_date timestamp without time zone,
    tax_group character varying(20) COLLATE public.nocase,
    ref_doc_line_no integer,
    taxable_amt_base numeric(20,2),
    tax_community character varying(50) COLLATE public.nocase,
    ttran_taxable_amt numeric(20,2),
    ttran_tax_amt numeric(20,2),
    ttran_tax_code character varying(20) COLLATE pg_catalog."default",
    ttran_tax_rate numeric(20,2),
    ttran_taxable_amt_bascur numeric(20,2),
    ttran_tax_amt_bascur numeric(20,2),
    prop_wht_amt numeric(20,2),
    app_wht_amt numeric(20,2),
    commodity_code character varying(80) COLLATE public.nocase,
    original_tax_code character varying(20) COLLATE public.nocase,
    original_tax_rate numeric(13,2),
    threshold_flag character varying(24) COLLATE public.nocase,
    taxable_amt_stcess numeric(20,2),
    etlcreatedatetime timestamp(3) without time zone
)
