CREATE TABLE stg.stg_sdin_invoice_hdr (
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    "timestamp" integer NOT NULL,
    tran_status character varying(12) COLLATE public.nocase,
    tran_date timestamp without time zone,
    anchor_date timestamp without time zone,
    fb_id character varying(80) COLLATE public.nocase,
    auto_adjust character varying(4) COLLATE public.nocase,
    tran_currency character varying(20) COLLATE public.nocase,
    exchange_rate numeric,
    pay_term character varying(60) COLLATE public.nocase,
    payterm_version integer,
    elec_pay character varying(4) COLLATE public.nocase,
    pay_method character varying(120) COLLATE public.nocase,
    pay_to_supp character varying(64) COLLATE public.nocase,
    pay_mode character varying(100) COLLATE public.nocase,
    pay_priority character varying(48) COLLATE public.nocase,
    payment_ou integer,
    supp_code character varying(64) COLLATE public.nocase,
    supp_invoice_no character varying(400) COLLATE public.nocase,
    supp_invoice_date timestamp without time zone,
    supp_invoice_amount numeric,
    supp_ou integer,
    comments character varying(1024) COLLATE public.nocase,
    address1 character varying(160) COLLATE public.nocase,
    address2 character varying(160) COLLATE public.nocase,
    address3 character varying(160) COLLATE public.nocase,
    city character varying(160) COLLATE public.nocase,
    state character varying(160) COLLATE public.nocase,
    country character varying(160) COLLATE public.nocase,
    zip character varying(80) COLLATE public.nocase,
    phone character varying(80) COLLATE public.nocase,
    telex character varying(80) COLLATE public.nocase,
    fax character varying(80) COLLATE public.nocase,
    pager character varying(80) COLLATE public.nocase,
    mobile character varying(80) COLLATE public.nocase,
    mailstop character varying(80) COLLATE public.nocase,
    email character varying(240) COLLATE public.nocase,
    url character varying(200) COLLATE public.nocase,
    contact character varying(160) COLLATE public.nocase,
    tran_amount numeric,
    par_exchange_rate numeric,
    item_amount numeric,
    tax_amount numeric,
    disc_amount numeric,
    base_amount numeric,
    par_base_amount numeric,
    rev_doc_no character varying(72) COLLATE public.nocase,
    rev_doc_ou integer,
    rev_date timestamp without time zone,
    ref_doc_no character varying(72) COLLATE public.nocase,
    ref_doc_ou integer,
    rev_reason_code character varying(40) COLLATE public.nocase,
    rev_remarks character varying(400) COLLATE public.nocase,
    hld_date timestamp without time zone,
    hld_reason_code character varying(40) COLLATE public.nocase,
    hld_remarks character varying(400) COLLATE public.nocase,
    auth_date timestamp without time zone,
    posting_date timestamp without time zone,
    posting_status character varying(12) COLLATE public.nocase,
    disc_comp_basis character varying(4) COLLATE public.nocase,
    discount_proportional character varying(4) COLLATE public.nocase,
    comp_bp_code character varying(128) COLLATE public.nocase,
    bank_code character varying(128) COLLATE public.nocase,
    lsv_id character varying(120) COLLATE public.nocase,
    comp_acct_in character varying(40) COLLATE public.nocase,
    comp_bp_ref character varying(80) COLLATE public.nocase,
    comp_bp_acc_no character varying(128) COLLATE public.nocase,
    esr_id character varying(120) COLLATE public.nocase,
    partid_digits integer,
    refno_digits integer,
    supp_acct_in character varying(40) COLLATE public.nocase,
    supp_bp_ref character varying(80) COLLATE public.nocase,
    supp_bp_acc_no character varying(128) COLLATE public.nocase,
    vat_applicable character varying(4) COLLATE public.nocase,
    vat_exchange_rate numeric,
    vat_charge numeric,
    non_vat_charge numeric,
    doc_level_disc numeric,
    vat_incl character varying(4) COLLATE public.nocase,
    retain_init_distbn character varying(4) COLLATE public.nocase,
    cap_non_ded_charge character varying(4) COLLATE public.nocase,
    average_vat_rate numeric,
    vat_excl_amount numeric,
    vat_amount numeric,
    vat_incl_amount numeric,
    pre_round_off_amount numeric,
    rounded_off_amount numeric,
    batch_id character varying(512) COLLATE public.nocase,
    doc_status character varying(48) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    tcal_status character varying(48) COLLATE public.nocase,
    total_tcal_amount numeric,
    tcal_exclusive_amt numeric,
    supp_companycode character varying(40) COLLATE public.nocase,
    supp_comppttname character varying(160) COLLATE public.nocase,
    supp_suplbank character varying(128) COLLATE public.nocase,
    supp_suplbankname character varying(240) COLLATE public.nocase,
    supp_swiftid character varying(80) COLLATE public.nocase,
    supp_ibanno character varying(160) COLLATE public.nocase,
    supp_lsvcontractid character varying(120) COLLATE public.nocase,
    supp_contractref character varying(160) COLLATE public.nocase,
    supp_lsvfromdate timestamp without time zone,
    supp_lsvtodate timestamp without time zone,
    supp_contallowed character(8) COLLATE public.nocase,
    supp_contactperson character varying(180) COLLATE public.nocase,
    supp_bankclearno character varying(128) COLLATE public.nocase,
    account_code character varying(128) COLLATE public.nocase,
    proposal_no character varying(80) COLLATE public.nocase,
    ibe_flag character varying(48) COLLATE public.nocase,
    billofladingno character varying(280) COLLATE public.nocase,
    bookingno character varying(280) COLLATE public.nocase,
    masterbillofladingno character varying(280) COLLATE public.nocase,
    autogen_flag character varying(48) COLLATE public.nocase,
    autogen_comp_id character varying(64) COLLATE public.nocase,
    consistency_stamp character varying(48) COLLATE public.nocase,
    workflow_status character varying(80) COLLATE public.nocase,
    prev_trnamt numeric,
    lc_number character varying(120) COLLATE public.nocase,
    lc_refid character varying(480) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    afe_number character varying(72) COLLATE public.nocase,
    job_number character varying(72) COLLATE public.nocase,
    costcenter_hdr character varying(40) COLLATE public.nocase,
    inter_compflag character varying(48) COLLATE public.nocase,
    invoice_num_ims character varying(600) COLLATE public.nocase,
    invoice_id_ims numeric,
    vendor_id_ims character varying(80) COLLATE public.nocase,
    vendor_site_id_ims character varying(80) COLLATE public.nocase,
    accts_pay_code_combination_id_ims character varying(80) COLLATE public.nocase,
    doc_sequence_id_ims character varying(80) COLLATE public.nocase,
    doc_sequence_value_ims character varying(80) COLLATE public.nocase,
    cash_code character varying(128) COLLATE public.nocase,
    payment_type character varying(24) DEFAULT 'CR'::character varying NOT NULL COLLATE public.nocase,
    workflow_error character varying(72) COLLATE public.nocase,
    corr_roff numeric,
    dervied_roff numeric,
    hold_amt numeric,
    holdaccount character varying(128) COLLATE public.nocase,
    retaccount character varying(128) COLLATE public.nocase,
    retamount numeric,
    holdpayterm character varying(60) COLLATE public.nocase,
    retpayterm character varying(60) COLLATE public.nocase,
    template_no character varying(72) COLLATE public.nocase,
    ict_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    num_series character varying(160) COLLATE public.nocase,
    ales_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    supplieraddress character varying(80) COLLATE public.nocase,
    lgt_invoice character varying(4) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    trnsfr_bill_no character varying(72) COLLATE public.nocase,
    trnsfr_bill_date timestamp without time zone,
    rcti_flag integer,
    trnsfr_bill_ou integer,
    mail_sent character varying(100) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    own_taxregion character varying(40) COLLATE public.nocase,
    allow_auto_cap character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);