CREATE TABLE stg.stg_tms_tdtbd_driver_trip_br_dtl (
    tdtbd_ouinstance integer NOT NULL,
    tdtbd_trip_id character varying(160) NOT NULL COLLATE public.nocase,
    tdtbd_br_id character varying(160) COLLATE public.nocase,
    tdtbd_trip_line_status character varying(100) COLLATE public.nocase,
    tdtbd_plan_date character varying(100) COLLATE public.nocase,
    tdtbd_br_customer character varying(160) COLLATE public.nocase,
    tdtbd_dispatch_doc character varying(160) COLLATE public.nocase,
    tdtbd_seqno integer,
    tdtbd_from_loc character varying(160) COLLATE public.nocase,
    tdtbd_to_loc character varying(160) COLLATE public.nocase,
    tdtbd_br_addr1 character varying(1020) COLLATE public.nocase,
    tdtbd_br_addr2 character varying(1020) COLLATE public.nocase,
    tdtbd_br_addr3 character varying(1020) COLLATE public.nocase,
    tdtbd_contact_person character varying(180) COLLATE public.nocase,
    tdtbd_contact_phone character varying(72) COLLATE public.nocase,
    tdtbd_reason_code character varying(160) COLLATE public.nocase,
    tdtbd_remarks character varying(1020) COLLATE public.nocase,
    tdtbd_event_status character varying(100) COLLATE public.nocase,
    tdtbd_arrived_date timestamp without time zone,
    tdtbd_handed_over_date timestamp without time zone,
    tdtbd_departed_date timestamp without time zone,
    tdtbd_feedback_level integer,
    tdtbd_signature character varying COLLATE public.nocase,
    tdtbd_created_date character varying(100) COLLATE public.nocase,
    tdtbd_guid character varying(512) COLLATE public.nocase,
    tdtbd_leg_beh character varying(160) COLLATE public.nocase,
    tdtbd_dispdoc_remarks character varying(1020) COLLATE public.nocase,
    tdtbd_person_name character varying(160) COLLATE public.nocase,
    tdtbd_signature_status character varying(120) COLLATE public.nocase,
    tdtbd_arrived_reason_code character varying(160) COLLATE public.nocase,
    tdtbd_arrived_reason_remarks character varying(1020) COLLATE public.nocase,
    tdtbd_departed_reason_code character varying(160) COLLATE public.nocase,
    tdtbd_departed_reason_remarks character varying(1020) COLLATE public.nocase,
    tdtbd_free_time character varying(160) COLLATE public.nocase,
    tdtbd_timestamp integer,
    tdtbd_created_by character varying(120) COLLATE public.nocase,
    tdtbd_last_modified_by character varying(120) COLLATE public.nocase,
    tdtbd_last_modified_date character varying(100) COLLATE public.nocase,
    tdtbd_nod_no character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);