CREATE TABLE stg.stg_tms_trip_plan_resource_details (
    tprd_ouinstance integer,
    tprd_trip character varying(160) COLLATE public.nocase,
    tprd_resource_type character varying(160) COLLATE public.nocase,
    tprd_resource_id character varying(1020) COLLATE public.nocase,
    tprd_resource_status character varying(160) COLLATE public.nocase,
    tprd_resource_seq integer,
    tprd_start_date timestamp without time zone,
    tprd_end_date timestamp without time zone,
    tprd_from_point character varying(1020) COLLATE public.nocase,
    tprd_to_point character varying(1020) COLLATE public.nocase,
    trpd_date_updated_by character varying(1020) COLLATE public.nocase,
    tprd_vendor_id character varying(1020) COLLATE public.nocase,
    trpd_updated_by character varying(1020) COLLATE public.nocase,
    tprd_created_by character varying(120) COLLATE public.nocase,
    tprd_created_date timestamp without time zone,
    tprd_modified_by character varying(120) COLLATE public.nocase,
    tprd_modified_date timestamp without time zone,
    tprd_timestamp integer,
    tprd_unique_id character varying(512) COLLATE public.nocase,
    tprd_resource_display_seq integer,
    tprd_actual_start_date timestamp without time zone,
    tprd_actual_end_date timestamp without time zone,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);