CREATE TABLE stg.stg_wms_asn_detail (
    wms_asn_ou integer NOT NULL,
    wms_asn_location character varying(40) NOT NULL COLLATE public.nocase,
    wms_asn_no character varying(72) NOT NULL COLLATE public.nocase,
    wms_asn_lineno integer NOT NULL,
    wms_asn_line_status character varying(100) COLLATE public.nocase,
    wms_asn_itm_code character varying(128) COLLATE public.nocase,
    wms_asn_qty numeric,
    wms_asn_batch_no character varying(112) COLLATE public.nocase,
    wms_asn_srl_no character varying(112) COLLATE public.nocase,
    wms_asn_manfct_date timestamp without time zone,
    wms_asn_exp_date timestamp without time zone,
    wms_asn_thu_id character varying(160) COLLATE public.nocase,
    wms_asn_thu_desc character varying(1020) COLLATE public.nocase,
    wms_asn_thu_qty numeric,
    wms_po_lineno integer,
    wms_gr_flag character(8) COLLATE public.nocase,
    wms_asn_rec_qty numeric,
    wms_asn_acc_qty numeric,
    wms_asn_rej_qty numeric,
    wms_asn_thu_srl_no character varying(112) COLLATE public.nocase,
    wms_asn_uid character varying(160) COLLATE public.nocase,
    wms_asn_rem character varying(1020) COLLATE public.nocase,
    wms_asn_itm_height numeric,
    wms_asn_itm_volume numeric,
    wms_asn_itm_weight numeric,
    wms_asn_customer_item_code character varying(128) COLLATE public.nocase,
    wms_asn_order_uom character varying(40) COLLATE public.nocase,
    wms_asn_master_uom_qty numeric,
    wms_asn_cust_sl_no character varying(112) COLLATE public.nocase,
    wms_asn_ref_doc_no1 character varying(72) COLLATE public.nocase,
    wms_asn_outboundorder_no character varying(72) COLLATE public.nocase,
    wms_asn_outboundorder_qty numeric,
    wms_asn_consignee character varying(72) COLLATE public.nocase,
    wms_asn_outboundorder_lineno integer,
    wms_asn_bestbeforedate timestamp without time zone,
    wms_asn_itm_length numeric,
    wms_asn_itm_breadth numeric,
    wms_asn_heightuom character varying(40) COLLATE public.nocase,
    wms_asn_weightuom character varying(40) COLLATE public.nocase,
    wms_asn_volumeuom character varying(40) COLLATE public.nocase,
    wms_asn_user_def_1 character varying(1020) COLLATE public.nocase,
    wms_asn_user_def_2 numeric,
    wms_asn_user_def_3 character varying(1020) COLLATE public.nocase,
    wms_asn_hold integer,
    wms_asn_stock_status character varying(160) COLLATE public.nocase,
    wms_asn_inv_type character varying(160) COLLATE public.nocase,
    wms_asn_product_status character varying(160) COLLATE public.nocase,
    wms_asn_coo character varying(200) COLLATE public.nocase,
    wms_asn_item_attribute1 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute2 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute3 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute4 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute5 character varying(1020) COLLATE public.nocase,
    wms_asn_itm_cust character varying(72) COLLATE public.nocase,
    wms_asn_cust_po_lineno integer,
    wms_inb_wr_serial_no character varying(112) COLLATE public.nocase,
    wms_asn_item_lineno integer,
    wms_asn_ratio integer,
    wms_asn_lottable1 character varying(1024) COLLATE public.nocase,
    wms_asn_lottable2 character varying(1024) COLLATE public.nocase,
    wms_asn_lottable3 character varying(1024) COLLATE public.nocase,
    wms_asn_lottable4 timestamp without time zone,
    wms_asn_lottable5 timestamp without time zone,
    wms_asn_item_attribute6 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute7 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute8 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute9 character varying(1020) COLLATE public.nocase,
    wms_asn_item_attribute10 character varying(1020) COLLATE public.nocase,
    wms_asn_component integer,
    wms_asn_uid2 character varying(112) COLLATE public.nocase,
    wms_asn_su1 character varying(40) COLLATE public.nocase,
    wms_asn_su2 character varying(40) COLLATE public.nocase,
    wms_asn_lottable10 character varying(1020) COLLATE public.nocase,
    wms_asn_lottable9 character varying(1020) COLLATE public.nocase,
    wms_asn_lottable8 character varying(1020) COLLATE public.nocase,
    wms_asn_lottable7 character varying(1020) COLLATE public.nocase,
    wms_asn_lottable6 character varying(1020) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);