CREATE TABLE stg.stg_cdi_item_dtl (
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    line_no integer NOT NULL,
    ctimestamp integer,
    visible_line_no integer,
    item_tcd_code character varying(128) COLLATE public.nocase,
    item_tcd_var character varying(128) COLLATE public.nocase,
    usage_id character varying(80) COLLATE public.nocase,
    item_type character varying(100) COLLATE public.nocase,
    uom character varying(60) COLLATE public.nocase,
    item_qty numeric,
    unit_price numeric,
    base_value numeric,
    item_amount numeric,
    tax_amount numeric,
    disc_amount numeric,
    line_amount numeric,
    base_amount numeric,
    par_base_amount numeric,
    sale_purpose character varying(160) COLLATE public.nocase,
    warehouse_code character varying(40) COLLATE public.nocase,
    alloc_method character varying(160) COLLATE public.nocase,
    attr_alloc character varying(4) COLLATE public.nocase,
    proposal_no character varying(72) COLLATE public.nocase,
    shipping_ou integer,
    ship_to_cust character varying(72) COLLATE public.nocase,
    ship_to_id character varying(24) COLLATE public.nocase,
    packslip_no character varying(72) COLLATE public.nocase,
    packslip_ou integer,
    packslip_line_no integer,
    remarks character varying(1020) COLLATE public.nocase,
    cost_center character varying(40) COLLATE public.nocase,
    analysis_code character varying(20) COLLATE public.nocase,
    subanalysis_code character varying(20) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    item_desc character varying(600) COLLATE public.nocase,
    cdi_sales_person character varying(72) COLLATE public.nocase,
    cdi_sales_team character varying(72) COLLATE public.nocase,
    alt_uom character varying(60) COLLATE public.nocase,
    alt_tran_qty numeric,
    usage_desc character varying(1020) COLLATE public.nocase,
    cfs_refdoc_ou integer,
    cfs_refdoc_no character varying(72) COLLATE public.nocase,
    cfs_refdoc_type character varying(160) COLLATE public.nocase,
    draft_bill_date timestamp without time zone,
    draft_bill_line_no integer,
    trnsfr_bill_lineno integer,
    location character varying(160) COLLATE public.nocase,
    region character varying(160) COLLATE public.nocase,
    partytype character varying(24) COLLATE public.nocase,
    partycode character varying(80) COLLATE public.nocase,
    line_of_business character varying(160) COLLATE public.nocase,
    department character varying(160) COLLATE public.nocase,
    product character varying(160) COLLATE public.nocase,
    equip_type character varying(160) COLLATE public.nocase,
    service_type character varying(160) COLLATE public.nocase,
    order_type character varying(160) COLLATE public.nocase,
    vehicle_type character varying(160) COLLATE public.nocase,
    activity_type character varying(160) COLLATE public.nocase,
    party_group character varying(160) COLLATE public.nocase,
    nature character varying(160) COLLATE public.nocase,
    currency character varying(20) COLLATE public.nocase,
    draft_bill_no character varying(72) COLLATE public.nocase,
    draft_bill_ref_docno character varying(72) COLLATE public.nocase,
    dest_comp character varying(40) COLLATE public.nocase,
    dest_ou integer,
    dest_fbid character varying(80) COLLATE public.nocase,
    dest_costcenter character varying(128) COLLATE public.nocase,
    dest_analysis_code character varying(20) COLLATE public.nocase,
    dest_sub_analysis_code character varying(20) COLLATE public.nocase,
    dest_usageid character varying(80) COLLATE public.nocase,
    intrfb_jv_no character varying(72) COLLATE public.nocase,
    accountcode_destusage character varying(128) COLLATE public.nocase,
    accountcode_interfb character varying(128) COLLATE public.nocase,
    accountcode_cdi character varying(128) COLLATE public.nocase,
    line_account character varying(128) COLLATE public.nocase,
    fbidml character varying(80) COLLATE public.nocase,
    zoneml character varying(40) COLLATE public.nocase,
    binml character varying(40) COLLATE public.nocase,
    dpi_agreedprice numeric,
    orginal_item_value numeric,
    serviceitem character varying(128) COLLATE public.nocase,
    ifb_recon_jvno character varying(72) COLLATE public.nocase,
    own_tax_region character varying(40) COLLATE public.nocase,
    decl_tax_region character varying(40) COLLATE public.nocase,
    party_tax_region character varying(40) COLLATE public.nocase,
    billingprdfrom timestamp without time zone,
    billingprdto timestamp without time zone,
    billingmilestone character varying(600) COLLATE public.nocase,
    milestonedesc character varying(1020) COLLATE public.nocase,
    orderbook_currency character varying(60) COLLATE public.nocase,
    bill_line_no integer,
    bill_sch_slno integer,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);