-- Table: stg.stg_itm_iou_itemvarhdr

-- DROP TABLE IF EXISTS stg.stg_itm_iou_itemvarhdr;

CREATE TABLE IF NOT EXISTS stg.stg_itm_iou_itemvarhdr
(
    iou_itemcode character varying(128) COLLATE public.nocase NOT NULL,
    iou_variantcode character varying(32) COLLATE public.nocase NOT NULL,
    iou_ou integer NOT NULL,
    iou_bu character varying(80) COLLATE public.nocase NOT NULL,
    iou_lo character varying(80) COLLATE public.nocase NOT NULL,
    iou_num_type character varying(72) COLLATE public.nocase NOT NULL,
    iou_effectivefrom timestamp without time zone,
    iou_effectiveto timestamp without time zone,
    iou_status character varying(32) COLLATE public.nocase NOT NULL,
    iou_stdwhcode character varying(40) COLLATE public.nocase,
    iou_minissueqty numeric,
    iou_stdcost numeric,
    iou_stdcostperqty numeric,
    iou_stdcostuom character varying(40) COLLATE public.nocase,
    iou_allocationmtd character varying(32) COLLATE public.nocase,
    iou_allocationhorizon integer,
    iou_sales_usage integer NOT NULL,
    iou_mfg_source integer NOT NULL,
    iou_production_usage integer NOT NULL,
    iou_purchase_source integer NOT NULL,
    iou_maintenance_usage integer NOT NULL,
    iou_subcntract_source integer NOT NULL,
    iou_stktransfer_source integer NOT NULL,
    iou_others_usage integer NOT NULL,
    iou_returnable integer NOT NULL,
    iou_hazardous integer NOT NULL,
    iou_backflushreqd integer NOT NULL,
    iou_storagealloc integer NOT NULL,
    iou_qcclearence integer NOT NULL,
    iou_planningtype character varying(32) COLLATE public.nocase NOT NULL,
    iou_xyz character varying(32) COLLATE public.nocase,
    iou_abc character varying(32) COLLATE public.nocase,
    iou_fsn character varying(32) COLLATE public.nocase,
    iou_ved character varying(32) COLLATE public.nocase,
    iou_minqty numeric,
    iou_maxqty numeric,
    iou_safetystock numeric,
    iou_disposition integer,
    iou_receipthorizon integer,
    iou_reserhorizon integer,
    iou_reorderactat character varying(32) COLLATE public.nocase,
    iou_reorderactby character varying(32) COLLATE public.nocase,
    iou_reorderlevel numeric,
    iou_reorderqty numeric,
    iou_stockableflg integer NOT NULL,
    iou_lotnotypeno character varying(40) COLLATE public.nocase,
    iou_slnotypeno character varying(40) COLLATE public.nocase,
    iou_mainref1 character varying(160) COLLATE public.nocase,
    iou_mainref2 character varying(160) COLLATE public.nocase,
    iou_mainref3 character varying(160) COLLATE public.nocase,
    iou_mainref4 character varying(160) COLLATE public.nocase,
    iou_basref1 character varying(160) COLLATE public.nocase,
    iou_basref2 character varying(160) COLLATE public.nocase,
    iou_basref3 character varying(160) COLLATE public.nocase,
    iou_basref4 character varying(160) COLLATE public.nocase,
    iou_planref1 character varying(160) COLLATE public.nocase,
    iou_planref2 character varying(160) COLLATE public.nocase,
    iou_planref3 character varying(160) COLLATE public.nocase,
    iou_planref4 character varying(160) COLLATE public.nocase,
    iou_created_by character varying(120) COLLATE public.nocase NOT NULL,
    iou_created_date timestamp without time zone NOT NULL,
    iou_modified_by character varying(120) COLLATE public.nocase NOT NULL,
    iou_modified_date timestamp without time zone NOT NULL,
    iou_plan_created_by character varying(120) COLLATE public.nocase,
    iou_plan_created_date timestamp without time zone,
    iou_plan_modified_by character varying(120) COLLATE public.nocase,
    iou_plan_modified_date timestamp without time zone,
    iou_timestamp integer NOT NULL,
    iou_manufact_source_pri integer,
    iou_purchase_source_pri integer,
    iou_subcon_source_pri integer,
    iou_stktran_source_pri integer,
    iou_catwght_ntol integer,
    iou_catwght_ptol integer,
    iou_hardallocationrqd integer,
    iou_qcproduction integer,
    iou_sublotnotypeno character varying(32) COLLATE public.nocase,
    iou_testlevel character varying(32) COLLATE public.nocase,
    iou_tariffno character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now(),
    CONSTRAINT pk_itm_iou_itemvarhdr PRIMARY KEY (iou_itemcode, iou_variantcode, iou_ou, iou_bu, iou_lo)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS stg.stg_itm_iou_itemvarhdr
    OWNER to proconnect;