CREATE TABLE stg.stg_tms_tarcd_tariff_rev_cost_cont_tariff_dtl (
    tarcd_ouinstance integer NOT NULL,
    tarcd_trip_plan_id character varying(160) NOT NULL COLLATE public.nocase,
    tarcd_booking_request character varying(160) NOT NULL COLLATE public.nocase,
    tarcd_unique_id character varying(512) NOT NULL COLLATE public.nocase,
    tarcd_leg_id character varying(160) COLLATE public.nocase,
    tarcd_buy_sell_type character varying(160) COLLATE public.nocase,
    tarcd_stage_of_derivation character varying(160) COLLATE public.nocase,
    tarcd_date_of_stage timestamp without time zone,
    tarcd_contract_id character varying(160) COLLATE public.nocase,
    tarcd_tariff_id character varying(160) COLLATE public.nocase,
    tarcd_tariff_type character varying(160) COLLATE public.nocase,
    tarcd_rate numeric,
    tarcd_remarks character varying(1020) COLLATE public.nocase,
    tarcd_trip_rev_cost_sk character varying(512) COLLATE public.nocase,
    tarcd_trip_plan_hdr_sk character varying(512) COLLATE public.nocase,
    tarcd_created_by character varying(160) COLLATE public.nocase,
    tarcd_created_date character varying(160) COLLATE public.nocase,
    tarcd_modified_by character varying(160) COLLATE public.nocase,
    tarcd_modified_date timestamp without time zone,
    tarcd_time_stamp integer,
    tarcd_resource_type character varying(160) COLLATE public.nocase,
    tarcd_weight numeric,
    tarcd_weight_uom character varying(40) COLLATE public.nocase,
    tarcd_pallet numeric,
    tarcd_vendor_flag character(4) COLLATE public.nocase,
    tarcd_resource_id character varying(160) COLLATE public.nocase,
    tarcd_amendment_no integer,
    tarcd_ct_resource_type character varying(160) COLLATE public.nocase,
    tarcd_ct_resource_id character varying(160) COLLATE public.nocase,
    tarcd_guid character varying(512) COLLATE public.nocase,
    tarcd_vedha_id character varying(160) COLLATE public.nocase,
    tarcd_vedha_type character varying(160) COLLATE public.nocase,
    tarcd_cont_rate numeric,
    tarcd_multiple_flag character(4) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);