CREATE TABLE stg.stg_dim_dest_tran_dtl (
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tran_type character varying(160) NOT NULL COLLATE public.nocase,
    tran_fb character varying(80) COLLATE public.nocase,
    tran_date timestamp without time zone,
    line_no integer NOT NULL,
    account_code character varying(128) COLLATE public.nocase,
    usage_code character varying(128) COLLATE public.nocase,
    dest_company character varying(80) COLLATE public.nocase,
    dest_ou character varying(80) COLLATE public.nocase,
    dest_fb character varying(80) COLLATE public.nocase,
    ref_doc_ou integer,
    ref_doc_no character varying(72) COLLATE public.nocase,
    ref_doc_trantype character varying(160) COLLATE public.nocase,
    tran_amount numeric,
    tran_currency character varying(20) COLLATE public.nocase,
    drcr_flag character varying(48) COLLATE public.nocase,
    cost_center character varying(40) COLLATE public.nocase,
    analysis_code character varying(20) COLLATE public.nocase,
    sub_analysiscode character varying(20) COLLATE public.nocase,
    base_amount numeric,
    account_desc character varying(1020) COLLATE public.nocase,
    d1 character varying(1020) COLLATE public.nocase,
    d2 character varying(1020) COLLATE public.nocase,
    d3 character varying(1020) COLLATE public.nocase,
    d4 character varying(1020) COLLATE public.nocase,
    d5 character varying(1020) COLLATE public.nocase,
    d6 character varying(1020) COLLATE public.nocase,
    d7 character varying(1020) COLLATE public.nocase,
    d8 character varying(1020) COLLATE public.nocase,
    d9 character varying(1020) COLLATE public.nocase,
    d10 character varying(1020) COLLATE public.nocase,
    d11 character varying(1020) COLLATE public.nocase,
    d12 character varying(1020) COLLATE public.nocase,
    d13 character varying(1020) COLLATE public.nocase,
    d14 character varying(1020) COLLATE public.nocase,
    d15 character varying(1020) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    ref_doc_lineno integer,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);