CREATE TABLE stg.stg_pcsit_mis_warehouse_sla_details_ibd (
    customercode character varying(10) COLLATE public.nocase,
    locationcode character varying(10) COLLATE public.nocase,
    locationdesc character varying(250) COLLATE public.nocase,
    ordernumber character varying(100) COLLATE public.nocase,
    ordertype character varying(50) COLLATE public.nocase,
    createddt character varying(20) COLLATE public.nocase,
    actualdt character varying(20) COLLATE public.nocase,
    agreedtat integer,
    grexpdt character varying(20) COLLATE public.nocase,
    grdt character varying(20) COLLATE public.nocase,
    grtat integer,
    paexpdt character varying(20) COLLATE public.nocase,
    padt character varying(20) COLLATE public.nocase,
    patat integer,
    pastatus character varying(50) COLLATE public.nocase,
    ibtat integer,
    slastatus character varying(100) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);