CREATE TABLE dwh.d_date (
    datekey integer NOT NULL,
    dateactual date NOT NULL,
    epoch bigint NOT NULL,
    daysuffix character varying(4) NOT NULL COLLATE public.nocase,
    dayname character varying(9) NOT NULL COLLATE public.nocase,
    dayofweek integer NOT NULL,
    dayofmonth integer NOT NULL,
    dayofquarter integer NOT NULL,
    dayofyear integer NOT NULL,
    weekofmonth integer NOT NULL,
    weekofyear integer NOT NULL,
    weekofyeariso character(10) NOT NULL COLLATE public.nocase,
    monthactual integer NOT NULL,
    monthname character varying(9) NOT NULL COLLATE public.nocase,
    monthnameabbreviated character(3) NOT NULL COLLATE public.nocase,
    quarteractual integer NOT NULL,
    quartername character varying(9) NOT NULL COLLATE public.nocase,
    yearactual integer NOT NULL,
    firstdayofweek date NOT NULL,
    lastdayofweek date NOT NULL,
    firstdayofmonth date NOT NULL,
    lastdayofmonth date NOT NULL,
    firstdayofquarter date NOT NULL,
    lastdayofquarter date NOT NULL,
    firstdayofyear date NOT NULL,
    lastdayofyear date NOT NULL,
    rolling12monthind bit(1),
    priorrolling12monthind bit(1),
    priorpriorrolling12monthind bit(1),
    rolling24monthind bit(1),
    rolling36monthind bit(1),
    rolling2yearind bit(1),
    rolling3yearind bit(1),
    rolling6monthind bit(1),
    roling3monthind bit(1),
    currentmonthind bit(1),
    prioryearcurrentmonthind bit(1),
    future6monthind bit(1),
    future5monthind bit(1),
    future4monthind bit(1),
    future3monthind bit(1),
    future12monthind bit(1),
    yeartolastcompletedmonthind bit(1),
    prioryeartolastcompletedmonthind bit(1),
    priorprioryeartolastcompletedmonthind bit(1),
    fullyearind bit(1),
    priorfullyearind bit(1),
    monthtodateind bit(1),
    prioryearmonthtodateind bit(1),
    yeartodateind bit(1),
    currentyearind bit(1),
    prioryearind bit(1),
    priormonthind bit(1),
    prioryeartodateind bit(1),
    priorprioryeartodateind bit(1),
    priorprioryearmonthtodateind bit(1),
    priorprioryearind bit(1),
    rolling365daysind bit(1),
    finacialyearind bit(1),
    prioryearfinancialyearind bit(1),
    etlactiveind bit(1),
    mmyyyy character(6) NOT NULL COLLATE public.nocase,
    mmddyyyy character(10) NOT NULL COLLATE public.nocase,
    weekendindr boolean NOT NULL
);

ALTER TABLE ONLY dwh.d_date
    ADD CONSTRAINT d_date_date_key_pk PRIMARY KEY (datekey);

ALTER TABLE ONLY dwh.d_date
    ADD CONSTRAINT d_date_ukey UNIQUE (dateactual);

CREATE INDEX d_date_date_actual_idx ON dwh.d_date USING btree (datekey, dateactual);