-- Table: dwh.d_itmiouitemvarhdr

-- DROP TABLE IF EXISTS dwh.d_itmiouitemvarhdr;

CREATE TABLE IF NOT EXISTS dwh.d_itmiouitemvarhdr
(
    itmiouitemvarhdr_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    iou_itemcode character varying(64) COLLATE public.nocase,
    iou_variantcode character varying(16) COLLATE public.nocase,
    iou_ou integer,
    iou_bu character varying(40) COLLATE public.nocase,
    iou_lo character varying(40) COLLATE public.nocase,
    iou_num_type character varying(36) COLLATE public.nocase,
    iou_effectivefrom timestamp without time zone,
    iou_effectiveto timestamp without time zone,
    iou_status character varying(16) COLLATE public.nocase,
    iou_stdwhcode character varying(20) COLLATE public.nocase,
    iou_minissueqty numeric(20,3),
    iou_stdcost numeric(20,3),
    iou_stdcostperqty numeric(20,3),
    iou_stdcostuom character varying(20) COLLATE public.nocase,
    iou_allocationmtd character varying(16) COLLATE public.nocase,
    iou_allocationhorizon integer,
    iou_sales_usage integer,
    iou_mfg_source integer,
    iou_production_usage integer,
    iou_purchase_source integer,
    iou_maintenance_usage integer,
    iou_subcntract_source integer,
    iou_stktransfer_source integer,
    iou_others_usage integer,
    iou_returnable integer,
    iou_hazardous integer,
    iou_backflushreqd integer,
    iou_storagealloc integer,
    iou_qcclearence integer,
    iou_planningtype character varying(16) COLLATE public.nocase,
    iou_abc character varying(16) COLLATE public.nocase,
    iou_disposition integer,
    iou_stockableflg integer,
    iou_lotnotypeno character varying(20) COLLATE public.nocase,
    iou_slnotypeno character varying(20) COLLATE public.nocase,
    iou_mainref4 character varying(80) COLLATE public.nocase,
    iou_basref1 character varying(80) COLLATE public.nocase,
    iou_basref4 character varying(80) COLLATE public.nocase,
    iou_planref4 character varying(80) COLLATE public.nocase,
    iou_created_by character varying(60) COLLATE public.nocase,
    iou_created_date timestamp without time zone,
    iou_modified_by character varying(60) COLLATE public.nocase,
    iou_modified_date timestamp without time zone,
    iou_plan_created_by character varying(60) COLLATE public.nocase,
    iou_plan_created_date timestamp without time zone,
    iou_plan_modified_by character varying(60) COLLATE public.nocase,
    iou_plan_modified_date timestamp without time zone,
    iou_timestamp integer,
    iou_manufact_source_pri integer,
    iou_purchase_source_pri integer,
    iou_catwght_ntol integer,
    iou_catwght_ptol integer,
    iou_hardallocationrqd integer,
    iou_qcproduction integer,
    iou_testlevel character varying(16) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT d_itmiouitemvarhdr_pkey PRIMARY KEY (itmiouitemvarhdr_key),
    CONSTRAINT d_itmiouitemvarhdr_ukey UNIQUE (iou_itemcode, iou_variantcode, iou_ou, iou_bu, iou_lo)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dwh.d_itmiouitemvarhdr
    OWNER to proconnect;