CREATE TABLE dwh.f_asndetailhistory (
    asn_dtl_hst_key bigint NOT NULL,
    asn_hdr_hst_key bigint NOT NULL,
    asn_dtl_hst_loc_key bigint NOT NULL,
    asn_dtl_hst_itm_hdr_key bigint NOT NULL,
    asn_dtl_hst_thu_key bigint NOT NULL,
    asn_ou integer,
    asn_location character varying(20) COLLATE public.nocase,
    asn_no character varying(40) COLLATE public.nocase,
    asn_amendno integer,
    asn_lineno integer,
    asn_itm_code character varying(80) COLLATE public.nocase,
    asn_qty numeric(25,2),
    asn_batch_no character varying(60) COLLATE public.nocase,
    asn_srl_no character varying(60) COLLATE public.nocase,
    asn_exp_date timestamp without time zone,
    asn_thu_id character varying(80) COLLATE public.nocase,
    asn_thu_desc character varying(510) COLLATE public.nocase,
    asn_thu_qty numeric(25,2),
    po_lineno integer,
    asn_rem character varying(510) COLLATE public.nocase,
    asn_itm_height numeric(25,2),
    asn_itm_volume numeric(25,2),
    asn_itm_weight numeric(25,2),
    asn_outboundorder_qty numeric(25,2),
    asn_bestbeforedate timestamp without time zone,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);