CREATE TABLE dwh.f_asnadditionaldetail (
    asn_add_dl_key bigint NOT NULL,
    asn_hr_key bigint NOT NULL,
    asn_pop_loc_key bigint NOT NULL,
    asn_pop_asn_no character varying(40) COLLATE public.nocase,
    asn_pop_loc character varying(20) COLLATE public.nocase,
    asn_pop_ou integer,
    asn_pop_line_no integer,
    asn_pop_date_1 timestamp without time zone,
    asn_pop_date_2 timestamp without time zone,
    asn_pop_ud_1 character varying(510) COLLATE public.nocase,
    asn_pop_ud_2 character varying(510) COLLATE public.nocase,
    asn_pop_ud_3 character varying(510) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);