CREATE TABLE dwh.f_binexecitemdetail (
    bin_itm_dtl_key bigint NOT NULL,
    bin_hdr_key bigint NOT NULL,
    bin_loc_key bigint NOT NULL,
    bin_itm_hdr_key bigint NOT NULL,
    bin_thu_key bigint NOT NULL,
    bin_loc_code character varying(20) COLLATE public.nocase,
    bin_exec_no character varying(40) COLLATE public.nocase,
    bin_exec_lineno integer,
    bin_ref_lineno integer,
    bin_exec_ou integer,
    bin_item character varying(80) COLLATE public.nocase,
    bin_src_bin character varying(20) COLLATE public.nocase,
    bin_src_zone character varying(20) COLLATE public.nocase,
    bin_src_staging_id character varying(40) COLLATE public.nocase,
    bin_stk_avial_qty numeric(20,2),
    bin_trn_out_qty numeric(20,2),
    bin_tar_bin character varying(20) COLLATE public.nocase,
    bin_tar_zone character varying(20) COLLATE public.nocase,
    bin_trgt_staging_id character varying(40) COLLATE public.nocase,
    bin_lot_no character varying(60) COLLATE public.nocase,
    bin_item_sr_no character varying(60) COLLATE public.nocase,
    bin_item_batch_no character varying(60) COLLATE public.nocase,
    bin_su_slno character varying(60) COLLATE public.nocase,
    bin_su_type character varying(20) COLLATE public.nocase,
    bin_stk_line_no integer,
    bin_stk_status character varying(20) COLLATE public.nocase,
    bin_src_status character varying(20) COLLATE public.nocase,
    bin_from_thu_sl_no character varying(60) COLLATE public.nocase,
    bin_target_thu_sl_no character varying(60) COLLATE public.nocase,
    bin_su character varying(20) COLLATE public.nocase,
    bin_thu_id character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);