CREATE TABLE dwh.f_brplanningprofiledetail (
    brppd_key bigint NOT NULL,
    brppd_cust_key bigint NOT NULL,
    brppd_loc_key bigint NOT NULL,
    brppd_ouinstance integer,
    brppd_profile_id character varying(80) COLLATE public.nocase,
    brppd_br_id character varying(80) COLLATE public.nocase,
    brppd_direct_entry character varying(10) COLLATE public.nocase,
    brppd_auto_entry character varying(10) COLLATE public.nocase,
    brppd_created_by character varying(60) COLLATE public.nocase,
    brppd_created_date timestamp without time zone,
    brppd_priority integer,
    brppd_param_priority character varying(80) COLLATE public.nocase,
    brppd_customer_id character varying(80) COLLATE public.nocase,
    brppd_customer_name character varying(510) COLLATE public.nocase,
    brppd_execution_plan character varying(80) COLLATE public.nocase,
    brppd_ship_from_id character varying(80) COLLATE public.nocase,
    brppd_ship_from_desc character varying(510) COLLATE public.nocase,
    brppd_ship_from_postal character varying(80) COLLATE public.nocase,
    brppd_ship_from_suburb character varying(80) COLLATE public.nocase,
    brppd_ship_to_id character varying(80) COLLATE public.nocase,
    brppd_ship_to_desc character varying(510) COLLATE public.nocase,
    brppd_ship_to_postal character varying(80) COLLATE public.nocase,
    brppd_ship_to_suburb character varying(80) COLLATE public.nocase,
    brppd_pickup_date timestamp without time zone,
    brppd_pickup_timeslot character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);