CREATE TABLE dwh.f_brewaybilldetail (
    ewbd_key bigint NOT NULL,
    br_key bigint NOT NULL,
    ewbd_br_no character varying(40) COLLATE public.nocase,
    ewbd_ouinstance integer,
    ewbd_bill_no character varying(80) COLLATE public.nocase,
    ewbd_ewaybl_guid character varying(300) COLLATE public.nocase,
    ewbd_remarks character varying(510) COLLATE public.nocase,
    ewbd_created_date timestamp without time zone,
    ewbd_created_by character varying(60) COLLATE public.nocase,
    ewbd_modified_date timestamp without time zone,
    ewbd_modified_by character varying(60) COLLATE public.nocase,
    ewbd_timestamp integer,
    ewbd_expiry_date timestamp without time zone,
    ewbd_shipper_invoice_date timestamp without time zone,
    ewbd_shipper_invoice_value numeric(13,2),
    ewbd_shipper_invoice_no character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);