CREATE TABLE dwh.f_brconsignmentthuserialdetail (
    ctsd_thu_key bigint NOT NULL,
    ctsd_br_key bigint NOT NULL,
    ctsd_ouinstance integer,
    ctsd_br_id character varying(40) COLLATE public.nocase,
    ctsd_thu_line_no character varying(300) COLLATE public.nocase,
    ctsd_thu_serial_line_no character varying(300) COLLATE public.nocase,
    ctsd_serial_no character varying(80) COLLATE public.nocase,
    ctsd_hazmat_code character varying(80) COLLATE public.nocase,
    ctsd_length numeric(25,2),
    ctsd_breadth numeric(25,2),
    ctsd_height numeric(25,2),
    ctsd_lbh_uom character varying(30) COLLATE public.nocase,
    ctsd_gross_weight numeric(25,2),
    ctsd_gross_weight_uom character varying(30) COLLATE public.nocase,
    ctsd_created_date timestamp without time zone,
    ctsd_created_by character varying(60) COLLATE public.nocase,
    ctsd_last_modified_by character varying(60) COLLATE public.nocase,
    ctsd_last_modified_date timestamp without time zone,
    ctsd_altqty numeric(25,2),
    ctsd_altqty_uom character varying(30) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);