CREATE TABLE dwh.f_deliverydelayreason (
    f_deliverydelayreason_key bigint NOT NULL,
    wms_loc_key bigint NOT NULL,
    locationcode character varying(10) COLLATE public.nocase,
    invoiceno character varying(100) COLLATE public.nocase,
    invoicedate date,
    invoiceholdtype character varying(100) COLLATE public.nocase,
    remarks character varying(500) COLLATE public.nocase,
    createdby character varying(50) COLLATE public.nocase,
    createddate timestamp without time zone,
    guid character varying(255) COLLATE public.nocase,
    tranou integer,
    type character varying(100) COLLATE public.nocase,
    activity character varying(100) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);