CREATE TABLE dwh.f_divisionareadetail (
    div_dtl_key bigint NOT NULL,
    div_key bigint NOT NULL,
    div_code character varying(20) COLLATE public.nocase,
    div_ou integer,
    div_length numeric(20,2),
    div_breath numeric(20,2),
    div_height numeric(20,2),
    div_uom character varying(20) COLLATE public.nocase,
    div_area_uom character varying(20) COLLATE public.nocase,
    div_tot_area numeric(20,2),
    div_tot_stag_area numeric(20,2),
    div_storg_area numeric(20,2),
    div_tot_docks numeric(20,2),
    div_other_area numeric(20,2),
    div_office_area numeric(20,2),
    div_outbound_area numeric(20,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);