CREATE TABLE dwh.f_draftbilltariffdetail (
    draft_bill_key bigint NOT NULL,
    draft_bill_ou integer,
    draft_bill_line_no integer,
    draft_bill_location character varying(20) COLLATE public.nocase,
    draft_bill_division character varying(20) COLLATE public.nocase,
    draft_bill_tran_type character varying(50) COLLATE public.nocase,
    draft_bill_ref_doc_no character varying(40) COLLATE public.nocase,
    draft_bill_ref_doc_type character varying(20) COLLATE public.nocase,
    draft_bill_trigger_doc_no character varying(40) COLLATE public.nocase,
    draft_bill_trigger_doc_line_no character varying(300) COLLATE public.nocase,
    draft_bill_trigger_doc_type character varying(20) COLLATE public.nocase,
    draft_bill_trip_leg character varying(300) COLLATE public.nocase,
    draft_bill_contract_id character varying(40) COLLATE public.nocase,
    draft_bill_tariff_id character varying(40) COLLATE public.nocase,
    draft_bill_acc_tariff_type character varying(20) COLLATE public.nocase,
    draft_bill_billable_hours numeric(13,2),
    draft_bill_value numeric(13,2),
    draft_bill_su_count numeric(13,2),
    draft_bill_consumables_count numeric(13,2),
    draft_bill_created_by character varying(60) COLLATE public.nocase,
    draft_bill_created_date timestamp without time zone,
    draft_bill_trip_thu_line_no character varying(300) COLLATE public.nocase,
    draft_bill_contract_amend_no integer,
    draft_bill_thu_id character varying(80) COLLATE public.nocase,
    draft_bill_equipment character varying(60) COLLATE public.nocase,
    draft_bill_vehicle character varying(60) COLLATE public.nocase,
    draft_bill_employee character varying(40) COLLATE public.nocase,
    draft_bill_equipment_type character varying(80) COLLATE public.nocase,
    draft_bill_vehicle_type character varying(80) COLLATE public.nocase,
    draft_bill_su character varying(20) COLLATE public.nocase,
    draft_bill_item_code character varying(80) COLLATE public.nocase,
    draft_bill_item_qty numeric(13,2),
    draft_bill_master_uom character varying(20) COLLATE public.nocase,
    draft_bill_item_wt numeric(13,2),
    draft_bill_item_wt_uom character varying(20) COLLATE public.nocase,
    draft_bill_no_of_weeks integer,
    draft_bill_weight numeric(13,2),
    draft_bill_vendorid character varying(40) COLLATE public.nocase,
    draft_bill_thu_space numeric(13,2),
    draft_bill_pickup_wt numeric(13,2),
    draft_bill_delivery_wt numeric(13,2),
    draft_bill_transit_time numeric(13,2),
    draft_bill_loading_time numeric(13,2),
    draft_bill_unloading_time numeric(13,2),
    draft_bill_est_return_time numeric(13,2),
    draft_bill_no_of_empl numeric(13,2),
    draft_bill_billable_intervals numeric(13,2),
    draft_bill_billing_status character varying(20) COLLATE public.nocase,
    draft_bill_customer_id character varying(40) COLLATE public.nocase,
    draft_bill_booking_location character varying(20) COLLATE public.nocase,
    draft_bill_db_no character varying(40) COLLATE public.nocase,
    draft_bill_db_ln_no integer,
    draft_bill_no_of_containers numeric(13,2),
    draft_bill_supp_bat_no character varying(60) COLLATE public.nocase,
    draft_bill_item_class character varying(510) COLLATE public.nocase,
    draft_bill_periodfrom timestamp without time zone,
    draft_bill_periodto timestamp without time zone,
    draft_bill_item_group character varying(80) COLLATE public.nocase,
    draft_bill_ref_doc_line_no integer,
    draft_bill_thu_qty numeric(13,2),
    draft_bill_volume numeric(13,2),
    draft_bill_distance numeric(13,2),
    draft_bill_resourcetype character varying(510) COLLATE public.nocase,
    draft_bill_total_storage_cost numeric(13,2),
    draft_bill_gross_vol_sales numeric(13,2),
    draft_bill_calc_basis character varying(20) COLLATE public.nocase,
    draft_bill_channel_type character varying(510) COLLATE public.nocase,
    draft_bill_in_ord_lineno integer,
    draft_bill_in_ord_cust_id character varying(40) COLLATE public.nocase,
    draft_bill_int_ord_cust_id character varying(40) COLLATE public.nocase,
    draft_bill_exch_rate numeric(13,2),
    draft_bill_margin numeric(13,2),
    draft_bill_min_charge numeric(13,2),
    draft_bill_max_charge numeric(13,2),
    draft_bill_min_charge_added character varying(20) COLLATE public.nocase,
    draft_bill_discount numeric(13,2),
    draft_bill_cont_rate numeric(13,2),
    draft_bill_value_currency character varying(20) COLLATE public.nocase,
    draft_bill_alt_bill_currency character varying(20) COLLATE public.nocase,
    draft_bill_seq_no integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);

ALTER TABLE dwh.f_draftbilltariffdetail ALTER COLUMN draft_bill_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh.f_draftbilltariffdetail_draft_bill_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY dwh.f_draftbilltariffdetail
    ADD CONSTRAINT f_draftbilltariffdetail_pkey PRIMARY KEY (draft_bill_key);

ALTER TABLE ONLY dwh.f_draftbilltariffdetail
    ADD CONSTRAINT f_draftbilltariffdetail_ukey UNIQUE (draft_bill_ou, draft_bill_line_no, draft_bill_tran_type);

CREATE INDEX f_draftbilltariffdetail_key_idx ON dwh.f_draftbilltariffdetail USING btree (draft_bill_ou, draft_bill_line_no, draft_bill_tran_type);