CREATE TABLE dwh.f_draftbillexecdetail (
    draft_bill_exec_dtl_key bigint NOT NULL,
    draft_bill_loc_key bigint NOT NULL,
    draft_bill_customer_key bigint NOT NULL,
    draft_bill_thu_key bigint NOT NULL,
    draft_bill_itm_hdr_key bigint NOT NULL,
    draft_bill_stg_mas_key bigint NOT NULL,
    exec_loc_code character varying(20) COLLATE public.nocase,
    exec_ou integer,
    exec_no character varying(40) COLLATE public.nocase,
    exec_stage character varying(50) COLLATE public.nocase,
    exec_line_no integer,
    exec_executed_on timestamp without time zone,
    exec_customer_id character varying(40) COLLATE public.nocase,
    exec_ref_doc_type character varying(20) COLLATE public.nocase,
    exec_ref_doc_no character varying(40) COLLATE public.nocase,
    exec_ref_doc_line_no integer,
    exec_ref_doc_sch_no integer,
    exec_tran_qty numeric(20,2),
    exec_item_lot_no character varying(60) COLLATE public.nocase,
    exec_item_batch_no character varying(60) COLLATE public.nocase,
    exec_item_serial_no character varying(60) COLLATE public.nocase,
    exec_thu_id character varying(80) COLLATE public.nocase,
    exec_thu_ser_no character varying(60) COLLATE public.nocase,
    exec_uid_ser_no character varying(60) COLLATE public.nocase,
    exec_item_code character varying(80) COLLATE public.nocase,
    exec_su character varying(20) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);