CREATE TABLE dwh.f_draftbilldetail (
    draft_bill_dtl_key bigint NOT NULL,
    draft_bill_hdr_key bigint NOT NULL,
    draft_bill_no character varying(40) COLLATE public.nocase,
    draft_bill_ou integer,
    draft_bill_lineno integer,
    draft_bill_ref_doc_no character varying(40) COLLATE public.nocase,
    draft_bill_ref_doc_typ character varying(20) COLLATE public.nocase,
    draft_bill_triggerring_no character varying(40) COLLATE public.nocase,
    draft_bill_triggerring_type character varying(20) COLLATE public.nocase,
    draft_bill_triggerring_date timestamp without time zone,
    draft_bill_tariff_id character varying(40) COLLATE public.nocase,
    draft_bill_uom character varying(20) COLLATE public.nocase,
    draft_bill_qty numeric(25,2),
    draft_bill_rate numeric(25,2),
    draft_bill_value numeric(25,2),
    draft_bill_discount numeric(25,2),
    draft_bill_total_value numeric(25,2),
    draft_bill_br_wt numeric(25,2),
    draft_bill_cn_weight numeric(25,2),
    draft_bill_rev_prot_wt numeric(25,2),
    draft_bill_billable_wt numeric(25,2),
    draft_bill_volume numeric(25,2),
    draft_bill_hours numeric(25,2),
    draft_bill_no_of_pallet numeric(25,2),
    draft_bill_br_vol numeric(25,2),
    draft_bill_cn_vol numeric(25,2),
    draft_bill_rev_prot_vol numeric(25,2),
    draft_bill_no_of_su numeric(25,2),
    draft_bill_count_of_consumables numeric(25,2),
    draft_bill_thu_id character varying(80) COLLATE public.nocase,
    draft_bill_ref_doc_date timestamp without time zone,
    draft_bill_equipment character varying(80) COLLATE public.nocase,
    draft_bill_vehicle character varying(60) COLLATE public.nocase,
    draft_bill_employee character varying(40) COLLATE public.nocase,
    draft_bill_equipment_type character varying(80) COLLATE public.nocase,
    draft_bill_vehicle_type character varying(60) COLLATE public.nocase,
    invoice_flag character varying(20) COLLATE public.nocase,
    draft_bill_exec_dt_from timestamp without time zone,
    draft_bill_exec_dt_to timestamp without time zone,
    draft_bill_calc_value numeric(25,2),
    draft_bill_margin numeric(25,2),
    draft_bill_invoice_no character varying(40) COLLATE public.nocase,
    draft_bill_invoice_ou integer,
    draft_bill_invoice_trantype character varying(50) COLLATE public.nocase,
    draft_bill_note_no character varying(40) COLLATE public.nocase,
    draft_bill_note_ou integer,
    draft_bill_note_trantype character varying(50) COLLATE public.nocase,
    draft_bill_su character varying(20) COLLATE public.nocase,
    draft_bill_item_code character varying(80) COLLATE public.nocase,
    draft_bill_item_qty numeric(25,2),
    draft_bill_master_uom character varying(20) COLLATE public.nocase,
    draft_bill_item_wt numeric(25,2),
    draft_bill_item_wt_uom character varying(20) COLLATE public.nocase,
    draft_bill_no_of_weeks integer,
    draft_bill_distance numeric(25,2),
    draft_bill_transit_time numeric(25,2),
    draft_bill_pickup_wt numeric(25,2),
    draft_bill_delivery_wt numeric(25,2),
    draft_bill_loading_time numeric(25,2),
    draft_bill_unloading_time numeric(25,2),
    draft_bill_est_return_time numeric(25,2),
    draft_bill_no_of_empl integer,
    draft_bill_service_type character varying(80) COLLATE public.nocase,
    draft_bill_subserv_type character varying(80) COLLATE public.nocase,
    draft_bill_no_of_containers numeric(25,2),
    draft_bill_supp_bat_no character varying(60) COLLATE public.nocase,
    force_match_flag character varying(30) COLLATE public.nocase,
    draft_bill_reimbursable character varying(510) COLLATE public.nocase,
    draft_bill_remarks character varying(510) COLLATE public.nocase,
    draft_bill_line_status character varying(80) COLLATE public.nocase,
    draft_bill_contract character varying(40) COLLATE public.nocase,
    draft_bill_periodfrom timestamp without time zone,
    draft_bill_periodto timestamp without time zone,
    draft_bill_veh_id character varying(60) COLLATE public.nocase,
    draft_bill_veh_type character varying(80) COLLATE public.nocase,
    draft_bill_driver_id character varying(60) COLLATE public.nocase,
    draft_bill_equip_id character varying(60) COLLATE public.nocase,
    draft_bill_equip_type character varying(80) COLLATE public.nocase,
    draft_consignee_name character varying(300) COLLATE public.nocase,
    draft_pri_ref_doc character varying(40) COLLATE public.nocase,
    draft_pri_gateway_auth_no character varying(510) COLLATE public.nocase,
    draft_authorization_date timestamp without time zone,
    draft_cust_item_id character varying(80) COLLATE public.nocase,
    draft_item_id character varying(80) COLLATE public.nocase,
    draft_item_desc character varying(1500) COLLATE public.nocase,
    draft_item_qty numeric(25,2),
    draft_bill_exchange_rate numeric(25,2),
    draft_bill_base_amount numeric(25,2),
    draft_bill_inv_gen_flag character varying(20) COLLATE public.nocase,
    draft_bill_dd1 character varying(40) COLLATE public.nocase,
    draft_bill_dd2 character varying(40) COLLATE public.nocase,
    draft_leg_behavior character varying(510) COLLATE public.nocase,
    draft_bill_primary_ref_docno character varying(40) COLLATE public.nocase,
    tmp_df_bill_primary_ref_doc_no character varying(40) COLLATE public.nocase,
    draft_bill_calc_qty numeric(25,2),
    draft_bill_calc_rate numeric(25,2),
    draft_bill_resourcetype character varying(510) COLLATE public.nocase,
    draft_bill_ord_src character varying(100) COLLATE public.nocase,
    draft_bill_odo_ref15_hdr character varying(510) COLLATE public.nocase,
    draft_bill_approved_by character varying(60) COLLATE public.nocase,
    draft_bill_approved_date timestamp without time zone,
    draft_bill_flex_field6 numeric(25,2),
    draft_bill_grp character varying(80) COLLATE public.nocase,
    draft_bill_invoice_type character varying(510) COLLATE public.nocase,
    customer_id character varying(80) COLLATE public.nocase,
    supplier_id character varying(80) COLLATE public.nocase,
    db_inco_terms character varying(510) COLLATE public.nocase,
    draft_bill_created_by character varying(60) COLLATE public.nocase,
    draft_bill_modified_by character varying(60) COLLATE public.nocase,
    draft_bill_created_date timestamp without time zone,
    draft_bill_modified_date timestamp without time zone,
    draft_bill_service_currency character varying(20) COLLATE public.nocase,
    draft_bill_int_ord_lineno integer,
    draft_bill_int_ord_cust_id character varying(40) COLLATE public.nocase,
    draft_bill_channel_type character varying(510) COLLATE public.nocase,
    draft_bill_reason_code character varying(510) COLLATE public.nocase,
    draft_bill_amend_user character varying(60) COLLATE public.nocase,
    draft_bill_amend_date timestamp without time zone,
    draft_bill_approve_user character varying(60) COLLATE public.nocase,
    draft_bill_approve_date timestamp without time zone,
    draft_bill_cancel_user character varying(60) COLLATE public.nocase,
    draft_bill_cancel_date timestamp without time zone,
    draft_bill_expflg character varying(20) COLLATE public.nocase,
    draft_bill_billing_id character varying(80) COLLATE public.nocase,
    draft_bill_fuel_tcd_code character varying(20) COLLATE public.nocase,
    draft_bill_fuel_tcd_variant character varying(20) COLLATE public.nocase,
    wsm_draft_bill_accrual_jv_no character varying(40) COLLATE public.nocase,
    wsm_draft_bill_reversal_jv_no character varying(40) COLLATE public.nocase,
    wsm_draft_bill_accrual_jv_date timestamp without time zone,
    wsm_draft_bill_accrual_jv_amount numeric(25,2),
    wsm_draft_bill_reversal_jv_date timestamp without time zone,
    wsm_draft_bill_reversal_jv_amount numeric(25,2),
    draft_bill_accural_flag character varying(30) COLLATE public.nocase,
    draft_bill_br_remittance_yn character varying(510) COLLATE public.nocase,
    draft_bill_accrual_amend_flag character varying(30) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);

ALTER TABLE dwh.f_draftbilldetail ALTER COLUMN draft_bill_dtl_key ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh.f_draftbilldetail_draft_bill_dtl_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY dwh.f_draftbilldetail
    ADD CONSTRAINT f_draftbilldetail_pkey PRIMARY KEY (draft_bill_dtl_key);

ALTER TABLE ONLY dwh.f_draftbilldetail
    ADD CONSTRAINT f_draftbilldetail_ukey UNIQUE (draft_bill_no, draft_bill_ou, draft_bill_lineno);

CREATE INDEX f_draftbilldetail_key_idx ON dwh.f_draftbilldetail USING btree (draft_bill_hdr_key);

CREATE INDEX f_draftbilldetail_key_idx1 ON dwh.f_draftbilldetail USING btree (draft_bill_no, draft_bill_ou, draft_bill_lineno);

CREATE INDEX f_draftbilldetail_ndx ON dwh.f_draftbilldetail USING btree (draft_bill_triggerring_no, draft_bill_ref_doc_no, draft_bill_ou);