CREATE TABLE dwh.f_fbpvoucherdtl (
    fbp_dtl_key bigint NOT NULL,
    fbp_company_key bigint NOT NULL,
    parent_key character varying(300) COLLATE public.nocase,
    current_key character varying(300) COLLATE public.nocase,
    company_code character varying(20) COLLATE public.nocase,
    ou_id integer,
    fb_id character varying(40) COLLATE public.nocase,
    fb_voucher_no character varying(40) COLLATE public.nocase,
    serial_no integer,
    "timestamp" integer,
    account_code character varying(80) COLLATE public.nocase,
    drcr_flag character varying(20) COLLATE public.nocase,
    cost_center character varying(20) COLLATE public.nocase,
    analysis_code character varying(10) COLLATE public.nocase,
    subanalysis_code character varying(10) COLLATE public.nocase,
    base_amount numeric(20,2),
    par_base_amount numeric(20,2),
    createdby character varying(60) COLLATE public.nocase,
    createddate timestamp without time zone,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);