CREATE TABLE dwh.f_gateexecdetail (
    gate_exec_dtl_key bigint NOT NULL,
    gate_exec_dtl_loc_key bigint NOT NULL,
    gate_exec_dtl_veh_key bigint NOT NULL,
    gate_exec_dtl_eqp_key bigint NOT NULL,
    gate_exec_dtl_emp_hdr_key bigint NOT NULL,
    gate_loc_code character varying(20) COLLATE public.nocase,
    gate_pln_no character varying(40) COLLATE public.nocase,
    gate_pln_ou integer,
    gate_exec_no character varying(40) COLLATE public.nocase,
    gate_exec_ou integer,
    gate_exec_date timestamp without time zone,
    gate_exec_status character varying(20) COLLATE public.nocase,
    gate_exec_gateno character varying(40) COLLATE public.nocase,
    gate_purpose character varying(20) COLLATE public.nocase,
    gate_flag character varying(20) COLLATE public.nocase,
    gate_actual_date timestamp without time zone,
    gate_ser_provider character varying(510) COLLATE public.nocase,
    gate_person character varying(120) COLLATE public.nocase,
    gate_veh_type character varying(80) COLLATE public.nocase,
    gate_vehicle_no character varying(60) COLLATE public.nocase,
    gate_equip_type character varying(80) COLLATE public.nocase,
    gate_equip_no character varying(60) COLLATE public.nocase,
    gate_ref_doc_typ1 character varying(20) COLLATE public.nocase,
    gate_ref_doc_no1 character varying(40) COLLATE public.nocase,
    gate_ref_doc_typ2 character varying(20) COLLATE public.nocase,
    gate_ref_doc_no2 character varying(40) COLLATE public.nocase,
    gate_ref_doc_typ3 character varying(20) COLLATE public.nocase,
    gate_ref_doc_no3 character varying(40) COLLATE public.nocase,
    gate_instructions character varying(510) COLLATE public.nocase,
    gate_employee character varying(40) COLLATE public.nocase,
    gate_created_by character varying(60) COLLATE public.nocase,
    gate_created_date timestamp without time zone,
    gate_timestamp integer,
    gate_userdefined1 character varying(510) COLLATE public.nocase,
    gate_gatein_no character varying(40) COLLATE public.nocase,
    gate_customer_name character varying(80) COLLATE public.nocase,
    gate_vendor_name character varying(80) COLLATE public.nocase,
    gate_from character varying(80) COLLATE public.nocase,
    gate_to character varying(80) COLLATE public.nocase,
    gate_noofunits integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);