CREATE TABLE dwh.f_gritemtrackingdetail (
    gr_itm_tk_dtl_key bigint NOT NULL,
    gr_itm_tk_dtl_loc_key bigint NOT NULL,
    gr_itm_tk_dtl_itm_hdr_key bigint NOT NULL,
    gr_itm_tk_dtl_customer_key bigint NOT NULL,
    stk_ou integer,
    stk_location character varying(20) COLLATE public.nocase,
    stk_item character varying(80) COLLATE public.nocase,
    stk_customer character varying(40) COLLATE public.nocase,
    stk_date timestamp without time zone,
    stk_uid_serial_no character varying(60) COLLATE public.nocase,
    stk_lot_no character varying(60) COLLATE public.nocase,
    stk_su character varying(20) COLLATE public.nocase,
    stk_gr_thu_id character varying(80) COLLATE public.nocase,
    stk_gr_thu_serial_no character varying(60) COLLATE public.nocase,
    stk_pack_thu_id character varying(80) COLLATE public.nocase,
    stk_pack_thu_serial_no character varying(60) COLLATE public.nocase,
    stk_opn_bal numeric(13,2),
    stk_received numeric(13,2),
    stk_issued numeric(13,2),
    stk_cls_bal numeric(13,2),
    stk_write_off_qty numeric(13,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);