CREATE TABLE dwh.f_grthulotdetail (
    gr_lot_key bigint NOT NULL,
    gr_lot_loc_key bigint NOT NULL,
    gr_lot_thu_key bigint NOT NULL,
    gr_lot_thu_item_key bigint NOT NULL,
    gr_loc_code character varying(20) COLLATE public.nocase,
    gr_exec_no character varying(40) COLLATE public.nocase,
    gr_exec_ou integer,
    gr_thu_id character varying(80) COLLATE public.nocase,
    gr_lot_thu_sno character varying(60) COLLATE public.nocase,
    gr_line_no integer,
    gr_item_line_no integer,
    gr_item_code character varying(80) COLLATE public.nocase,
    gr_lot_no character varying(60) COLLATE public.nocase,
    gr_qty numeric(13,2),
    gr_thu_uid_sr_no character varying(80) COLLATE public.nocase,
    gr_thu_lot_su character varying(20) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);