CREATE TABLE dwh.f_loadingdetail (
    loading_dtl_key bigint NOT NULL,
    loading_hdr_key bigint NOT NULL,
    loading_dtl_loc_key bigint NOT NULL,
    loading_dtl_thu_key bigint NOT NULL,
    loading_dtl_stg_mas_key bigint NOT NULL,
    loading_dtl_shp_pt_key bigint NOT NULL,
    loading_loc_code character varying(20) COLLATE public.nocase,
    loading_exec_no character varying(40) COLLATE public.nocase,
    loading_exec_ou integer,
    loading_lineno integer,
    loading_thu_id character varying(80) COLLATE public.nocase,
    loading_ship_point character varying(40) COLLATE public.nocase,
    loading_disp_doc_type character varying(20) COLLATE public.nocase,
    loading_disp_doc_no character varying(40) COLLATE public.nocase,
    loading_transfer_doc character varying(510) COLLATE public.nocase,
    loading_thu_desc character varying(510) COLLATE public.nocase,
    loading_thu_class character varying(80) COLLATE public.nocase,
    loading_thu_sr_no character varying(60) COLLATE public.nocase,
    loading_thu_acc character varying(150) COLLATE public.nocase,
    loading_disp_doc_date timestamp without time zone,
    loading_pal_qty numeric(20,2),
    loading_tran_typ character varying(20) COLLATE public.nocase,
    loading_start_date_time timestamp without time zone,
    loading_end_date_time timestamp without time zone,
    loading_so_no character varying(40) COLLATE public.nocase,
    loading_stage character varying(50) COLLATE public.nocase,
    loading_curr_exec character varying(40) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);