CREATE TABLE dwh.f_outboundschdetailhistory (
    obd_sdl_his_key bigint NOT NULL,
    obh_hr_his_key bigint NOT NULL,
    oub_loc_key bigint NOT NULL,
    oub_itm_key bigint NOT NULL,
    oub_sch_loc_code character varying(20) COLLATE public.nocase,
    oub_sch_ou integer,
    oub_outbound_ord character varying(40) COLLATE public.nocase,
    oub_sch_amendno integer,
    oub_sch_lineno integer,
    oub_sch_item_code character varying(80) COLLATE public.nocase,
    oub_item_lineno integer,
    oub_sch_order_qty numeric(25,2),
    oub_sch_masteruom character varying(20) COLLATE public.nocase,
    oub_sch_deliverydate timestamp without time zone,
    oub_sch_serfrom timestamp without time zone,
    oub_sch_serto timestamp without time zone,
    oub_sch_plan_gd_iss_dt timestamp without time zone,
    oub_sch_plan_gd_iss_time timestamp without time zone,
    oub_sch_operation_status character varying(20) COLLATE public.nocase,
    oub_sch_picked_qty numeric(25,2),
    oub_sch_packed_qty numeric(25,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);