CREATE TABLE dwh.f_outboundlotsrldetail (
    oub_lotsl_loc_key bigint NOT NULL,
    obh_hr_key bigint NOT NULL,
    oub_loc_key bigint NOT NULL,
    oub_itm_key bigint NOT NULL,
    oub_lotsl_loc_code character varying(20) COLLATE public.nocase,
    oub_lotsl_ou integer,
    oub_outbound_ord character varying(40) COLLATE public.nocase,
    oub_lotsl_lineno integer,
    oub_item_code character varying(80) COLLATE public.nocase,
    oub_item_lineno integer,
    oub_lotsl_order_qty numeric(20,2),
    oub_lotsl_batchno character varying(60) COLLATE public.nocase,
    oub_lotsl_serialno character varying(60) COLLATE public.nocase,
    oub_lotsl_masteruom character varying(20) COLLATE public.nocase,
    oub_refdocno1 character varying(40) COLLATE public.nocase,
    oub_refdocno2 character varying(40) COLLATE public.nocase,
    oub_thu_id character varying(80) COLLATE public.nocase,
    oub_thu_srno character varying(60) COLLATE public.nocase,
    oub_cus_srno character varying(140) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);