CREATE TABLE dwh.f_packplanheader (
    pack_pln_hdr_key bigint NOT NULL,
    pack_pln_hdr_loc_key bigint NOT NULL,
    pack_pln_hdr_date_key bigint NOT NULL,
    pack_pln_hdr_emp_hdr_key bigint NOT NULL,
    pack_loc_code character varying(20) COLLATE public.nocase,
    pack_pln_no character varying(40) COLLATE public.nocase,
    pack_pln_ou integer,
    pack_pln_date timestamp without time zone,
    pack_pln_status character varying(20) COLLATE public.nocase,
    pack_employee character varying(40) COLLATE public.nocase,
    pack_packing_bay character varying(40) COLLATE public.nocase,
    pack_source_stage character varying(510) COLLATE public.nocase,
    pack_source_docno character varying(40) COLLATE public.nocase,
    pack_created_by character varying(60) COLLATE public.nocase,
    pack_created_date timestamp without time zone,
    pack_modified_by character varying(60) COLLATE public.nocase,
    pack_modified_date timestamp without time zone,
    pack_timestamp integer,
    pack_userdefined1 character varying(510) COLLATE public.nocase,
    pack_userdefined2 character varying(510) COLLATE public.nocase,
    pack_userdefined3 character varying(510) COLLATE public.nocase,
    pack_pln_urgent integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);