CREATE TABLE dwh.f_packexecthuheader (
    pack_exec_thu_hdr_key bigint NOT NULL,
    pack_exec_hdr_key bigint NOT NULL,
    pack_exec_loc_key bigint NOT NULL,
    pack_exec_thu_key bigint NOT NULL,
    pack_exec_uom_key bigint NOT NULL,
    pack_exec_loc_code character varying(20) COLLATE public.nocase,
    pack_exec_no character varying(40) COLLATE public.nocase,
    pack_exec_ou integer,
    pack_exec_thu_id character varying(80) COLLATE public.nocase,
    pack_exec_thu_class character varying(80) COLLATE public.nocase,
    pack_exec_thu_sr_no character varying(60) COLLATE public.nocase,
    pack_exec_thu_qty numeric(25,2),
    pack_exec_thu_weight numeric(25,2),
    pack_exec_thu_weight_uom character varying(20) COLLATE public.nocase,
    pack_exec_thu_su_chk integer,
    pack_exec_uid1_ser_no character varying(60) COLLATE public.nocase,
    pack_exec_thuspace numeric(25,2),
    pack_exec_length numeric(25,2),
    pack_exec_breadth numeric(25,2),
    pack_exec_height numeric(25,2),
    pack_exec_uom character varying(20) COLLATE public.nocase,
    pack_exec_volumeuom character varying(20) COLLATE public.nocase,
    pack_exec_volume numeric(25,2),
    pack_exec_itm_serno_pkplan character varying(40) COLLATE public.nocase,
    pack_exec_itemslno character varying(60) COLLATE public.nocase,
    pack_exec_thu_id2 character varying(80) COLLATE public.nocase,
    pack_exec_thu_sr_no2 character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);