CREATE TABLE dwh.f_packheader (
    pack_hdr_key bigint NOT NULL,
    pack_location character varying(510) COLLATE public.nocase,
    pack_ou integer,
    pack_pack_rule character varying(510) COLLATE public.nocase,
    pack_single_step character varying(510) COLLATE public.nocase,
    pack_by_customer character varying(30) COLLATE public.nocase,
    pack_by_item character varying(30) COLLATE public.nocase,
    pack_by_pick_numb character varying(30) COLLATE public.nocase,
    pack_storage_pickbay character varying(30) COLLATE public.nocase,
    pack_load_balancing character varying(30) COLLATE public.nocase,
    pack_item_type character varying(30) COLLATE public.nocase,
    pack_timestamp integer,
    pack_created_by character varying(60) COLLATE public.nocase,
    pack_created_date timestamp without time zone,
    pack_modified_by character varying(60) COLLATE public.nocase,
    pack_modified_date timestamp without time zone,
    pack_step character varying(40) COLLATE public.nocase,
    pack_short_pick integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);