CREATE TABLE dwh.f_pcsgateinfodetail (
    pcs_gtin_dtl_key bigint NOT NULL,
    datekey bigint NOT NULL,
    id integer,
    orderno character varying(50) COLLATE public.nocase,
    gateno character varying(50) COLLATE public.nocase,
    ewayno character varying(50) COLLATE public.nocase,
    ewaydate character varying(50) COLLATE public.nocase,
    awbno character varying(50) COLLATE public.nocase,
    drivername character varying(150) COLLATE public.nocase,
    contactno character varying(150) COLLATE public.nocase,
    vehno character varying(150) COLLATE public.nocase,
    driverlicenseno character varying(150) COLLATE public.nocase,
    transporter character varying(100) COLLATE public.nocase,
    isnno character varying(100) COLLATE public.nocase,
    createdby character varying(100) COLLATE public.nocase,
    createddate timestamp without time zone,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);