CREATE TABLE dwh.f_putawayplandetail (
    pway_pln_dtl_key bigint NOT NULL,
    pway_pln_dtl_loc_key bigint NOT NULL,
    pway_pln_dtl_date_key bigint NOT NULL,
    pway_pln_dtl_stg_mas_key bigint NOT NULL,
    pway_pln_dtl_emp_hdr_key bigint NOT NULL,
    pway_loc_code character varying(20) COLLATE public.nocase,
    pway_pln_no character varying(40) COLLATE public.nocase,
    pway_pln_ou integer,
    pway_pln_date timestamp without time zone,
    pway_pln_status character varying(20) COLLATE public.nocase,
    pway_stag_id character varying(40) COLLATE public.nocase,
    pway_mhe_id character varying(60) COLLATE public.nocase,
    pway_employee_id character varying(40) COLLATE public.nocase,
    pway_source_stage character varying(510) COLLATE public.nocase,
    pway_source_docno character varying(40) COLLATE public.nocase,
    pway_created_by character varying(60) COLLATE public.nocase,
    pway_created_date timestamp without time zone,
    pway_modified_by character varying(60) COLLATE public.nocase,
    pway_modified_date timestamp without time zone,
    pway_timestamp integer,
    pway_output_pln character varying(510) COLLATE public.nocase,
    pway_type character varying(20) COLLATE public.nocase,
    pway_comp_flag character varying(20) COLLATE public.nocase,
    pway_first_pln_no character varying(40) COLLATE public.nocase,
    pway_by_flag character varying(16) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);