CREATE TABLE dwh.f_rptacctinfodtl (
    rptacctinfodtl_key bigint NOT NULL,
    rptacctinfodtl_curr_key bigint NOT NULL,
    rptacctinfodtl_company_key bigint NOT NULL,
    rptacctinfodtl_opcoa_key bigint NOT NULL,
    rptacctinfodtl_datekey bigint NOT NULL,
    ou_id integer,
    tran_no character varying(40) COLLATE public.nocase,
    fb_id character varying(40) COLLATE public.nocase,
    account_code character varying(80) COLLATE public.nocase,
    tran_type character varying(80) COLLATE public.nocase,
    drcr_flag character varying(20) COLLATE public.nocase,
    posting_line_no integer,
    fin_post_date timestamp without time zone,
    currency character varying(10) COLLATE public.nocase,
    cost_center character varying(20) COLLATE public.nocase,
    tran_amount numeric(25,2),
    analysis_code character varying(10) COLLATE public.nocase,
    subanalysis_code character varying(10) COLLATE public.nocase,
    basecur_erate numeric(25,2),
    base_amount numeric(25,2),
    par_base_amt numeric(25,2),
    batch_id character varying(300) COLLATE public.nocase,
    account_type character varying(30) COLLATE public.nocase,
    company_id character varying(20) COLLATE public.nocase,
    component_id character varying(40) COLLATE public.nocase,
    bu_id character varying(40) COLLATE public.nocase,
    tran_date timestamp without time zone,
    createdby character varying(60) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE public.nocase,
    source_comp character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);