CREATE TABLE dwh.f_sadadjvoucherhdr (
    sadadjvoucherhdr_key bigint NOT NULL,
    sadadjvoucherhdr_curr_key bigint NOT NULL,
    sadadjvoucherhdr_vendor_key bigint NOT NULL,
    ou_id integer,
    adj_voucher_no character varying(40) COLLATE public.nocase,
    stimestamp integer,
    voucher_date timestamp without time zone,
    fb_id character varying(40) COLLATE public.nocase,
    voucher_amount numeric(25,2),
    status character varying(50) COLLATE public.nocase,
    supp_code character varying(40) COLLATE public.nocase,
    adjust_seq character varying(30) COLLATE public.nocase,
    currency_code character varying(10) COLLATE public.nocase,
    voucher_type character varying(40) COLLATE public.nocase,
    rev_voucher_no character varying(40) COLLATE public.nocase,
    reversal_date timestamp without time zone,
    notype_no character varying(20) COLLATE public.nocase,
    currentkey character varying(300) COLLATE public.nocase,
    voucher_tran_type character varying(80) COLLATE public.nocase,
    batch_id character varying(300) COLLATE public.nocase,
    createdby character varying(60) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    tcal_exclusive_amt numeric(25,2),
    tcal_status character varying(30) COLLATE public.nocase,
    comments character varying(512) COLLATE public.nocase,
    autogen_flag character varying(30) COLLATE public.nocase,
    voucher_remarks character varying(510) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);