CREATE TABLE IF NOT EXISTS dwh.f_siposteddoclog
(
    si_posted_doc_log_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    si_posted_doc_log_vendor_key bigint NOT NULL,
    si_posted_doc_log_curr_key bigint NOT NULL,
    si_posted_doc_log_opcoa_key bigint NOT NULL,
    si_posted_doc_log_date_key bigint NOT NULL,
    tran_ou integer,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    term_no character varying(40) COLLATE public.nocase,
    amt_type character varying(50) COLLATE public.nocase,
    dr_doc_ou integer,
    dr_doc_type character varying(20) COLLATE public.nocase,
    dr_doc_no character varying(36) COLLATE public.nocase,
    cr_doc_ou integer,
    cr_doc_type character varying(20) COLLATE public.nocase,
    cr_doc_no character varying(36) COLLATE public.nocase,
    cr_doc_term character varying(40) COLLATE public.nocase,
    dr_doc_term character varying(40) COLLATE public.nocase,
    lo_id character varying(40) COLLATE public.nocase,
    tran_date timestamp without time zone,
    supplier_code character varying(32) COLLATE public.nocase,
    tran_currency character varying(10) COLLATE public.nocase,
    tran_amount numeric(25,2),
    basecur_erate numeric(25,2),
    par_exchange_rate numeric(25,2),
    par_base_amount numeric(25,2),
    posting_status character varying(10) COLLATE public.nocase,
    posting_date timestamp without time zone,
    batch_id character varying(256) COLLATE public.nocase,
    cross_curr_erate numeric(25,2),
    base_amount numeric(25,2),
    account_code character varying(64) COLLATE public.nocase,
    account_type character varying(30) COLLATE public.nocase,
    fb_id character varying(40) COLLATE public.nocase,
    pay_mode character varying(50) COLLATE public.nocase,
    paid_amt numeric(25,2),
    requested_amt numeric(25,2),
    discount_amt numeric(25,2),
    penalty_amount numeric(25,2),
    adjusted_amount numeric(25,2),
    disc_availed numeric(25,2),
    check_no character varying(60) COLLATE public.nocase,
    base_adjusted_amount numeric(25,2),
    pbase_adjusted_amount numeric(25,2),
    log_pdc_flag character varying(24) COLLATE public.nocase,
    pdc_void_flag character varying(24) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_siposteddoclog_pkey PRIMARY KEY (si_posted_doc_log_key),
    CONSTRAINT f_siposteddoclog_ukey UNIQUE (tran_ou, tran_type, tran_no, term_no, amt_type, dr_doc_ou, dr_doc_type, dr_doc_no, cr_doc_ou, cr_doc_type, cr_doc_no, cr_doc_term, dr_doc_term, account_type)
)
