CREATE TABLE IF NOT EXISTS dwh.f_sinapportionedtcddtl
(
    f_sin_apportioned_tcd_dtl_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tran_type character varying(20) COLLATE public.nocase,
    tran_ou integer,
    tran_no character varying(36) COLLATE public.nocase,
    line_no integer,
    item_tcd_code character varying(64) COLLATE public.nocase,
    item_tcd_var character varying(64) COLLATE public.nocase,
    tcd_version integer,
    "timestamp" integer,
    item_type character varying(10) COLLATE public.nocase,
    tcd_rate numeric(13,2),
    taxable_amt numeric(13,2),
    tcd_amount numeric(13,2),
    tcd_currency character varying(10) COLLATE public.nocase,
    base_amount numeric(13,2),
    cost_center character varying(20) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_sin_apportioned_tcd_dtl_pkey PRIMARY KEY (f_sin_apportioned_tcd_dtl_key),
    CONSTRAINT f_sin_apportioned_tcd_dtl_ukey UNIQUE (tran_type, tran_ou, tran_no, line_no, item_tcd_code, item_tcd_var, tcd_version)
)