CREATE TABLE IF NOT EXISTS dwh.f_sinpogrupdinfo
(
    sin_po_gr__upd_info_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    po_type character varying(20) COLLATE public.nocase,
    po_ou integer,
    po_no character varying(36) COLLATE public.nocase,
    po_amend_no integer,
    po_line_no integer,
    po_qty numeric(25,2),
    grinv_type character varying(20) COLLATE public.nocase,
    grinv_sequence_no integer,
    grinv_ou integer,
    grinv_no character varying(36) COLLATE public.nocase,
    grinv_line_no integer,
    grinv_qty numeric(25,2),
    grinv_aplan_upd_qty numeric(25,2),
    grinv_aplan_bal_upd_qty numeric(25,2),
    proposal_no character varying(36) COLLATE public.nocase,
    cwip_acc_no character varying(64) COLLATE public.nocase,
    inv_po_amount numeric(25,2),
    inv_tran_amount numeric(25,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_sinpogrupdinfo_pkey PRIMARY KEY (sin_po_gr__upd_info_key),
    CONSTRAINT f_sinpogrupdinfo_ukey UNIQUE (po_type, po_ou, po_no, po_amend_no, po_line_no, grinv_type, grinv_ou, grinv_no, grinv_line_no)
)