CREATE TABLE IF NOT EXISTS dwh.f_sidocbalancehis
(
    f_si_doc_balance_his_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    si_doc_balance_his_curr_key bigint NOT NULL,
    tran_ou integer,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    term_no character varying(40) COLLATE public.nocase,
    tran_currency character varying(10) COLLATE public.nocase,
    tran_date timestamp without time zone,
    doc_status character varying(50) COLLATE public.nocase,
    adjusted_amount numeric(20,2),
    disc_availed numeric(20,2),
    penalty_amount numeric(20,2),
    supp_code character varying(32) COLLATE public.nocase,
    fb_id character varying(40) COLLATE public.nocase,
    account_type character varying(30) COLLATE public.nocase,
    batch_id character varying(256) COLLATE public.nocase,
    base_adjusted_amount numeric(20,2),
    pbase_adjusted_amount numeric(20,2),
    adj_payment_no character varying(36) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_si_doc_balance_his_pkey PRIMARY KEY (f_si_doc_balance_his_key),
    CONSTRAINT f_si_doc_balance_his_ukey UNIQUE (tran_ou, tran_type, tran_no, term_no, account_type, batch_id, adj_payment_no)
)
