CREATE TABLE IF NOT EXISTS dwh.f_sidocbalance
(
    si_doc_balance_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    si_doc_balance_curr_key bigint NOT NULL,
    si_doc_balance_opcoa_key bigint NOT NULL,
    si_doc_balance_vendor_key bigint NOT NULL,
    si_doc_balance_date_key bigint NOT NULL,
    tran_ou integer,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    term_no character varying(40) COLLATE public.nocase,
    lo_id character varying(40) COLLATE public.nocase,
    tran_currency character varying(10) COLLATE public.nocase,
    tran_amount numeric(25,2),
    exchange_rate numeric(25,2),
    base_amount numeric(25,2),
    par_exchange_rate numeric(25,2),
    par_base_amount numeric(25,2),
    doc_status character varying(50) COLLATE public.nocase,
    adjustment_status character varying(50) COLLATE public.nocase,
    discount_amount numeric(25,2),
    disc_availed numeric(25,2),
    penalty_amount numeric(25,2),
    paid_amt numeric(25,2),
    requested_amount numeric(25,2),
    adjusted_amount numeric(25,2),
    batch_id character varying(256) COLLATE public.nocase,
    due_date timestamp without time zone,
    discount_date timestamp without time zone,
    account_code character varying(64) COLLATE public.nocase,
    account_type character varying(30) COLLATE public.nocase,
    supp_code character varying(32) COLLATE public.nocase,
    fb_id character varying(40) COLLATE public.nocase,
    tran_date timestamp without time zone,
    outstanding_amt numeric(25,2),
    posting_date timestamp without time zone,
    base_outstanding_amt numeric(25,2),
    pbase_outstanding_amt numeric(25,2),
    base_adjusted_amount numeric(25,2),
    pbase_adjusted_amount numeric(25,2),
    base_paid_amt numeric(25,2),
    pbase_paid_amt numeric(25,2),
    disc_amount_type character varying(80) COLLATE public.nocase,
    disc_percent numeric(25,2),
    penalty_percent numeric(25,2),
    pdc_flag character varying(24) COLLATE public.nocase,
    pdc_void_flag character varying(24) COLLATE public.nocase,
    instr_no character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_sidocbalance_pkey PRIMARY KEY (si_doc_balance_key)
)