CREATE TABLE IF NOT EXISTS dwh.f_siacctinfodtl
(
    si_acct_info_dtl_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    si_acct_info_dtl_opcoa_key bigint NOT NULL,
    si_acct_info_dtl_curr_key bigint NOT NULL,
    si_acct_info_dtl_company_key bigint NOT NULL,
    si_acct_info_dtl_date_key bigint NOT NULL,
    si_acct_info_dtl_vendor_key bigint NOT NULL,
    si_acct_info_dtl_itm_hdr_key bigint NOT NULL,
    tran_ou integer,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    line_no integer,
    vat_line_no integer,
    component_id character varying(32) COLLATE public.nocase,
    exchange_rate numeric(25,2),
    company_code character varying(20) COLLATE public.nocase,
    fb_id character varying(40) COLLATE public.nocase,
    account_code character varying(64) COLLATE public.nocase,
    drcr_flag character varying(20) COLLATE public.nocase,
    txnou_id integer,
    bu_id character varying(40) COLLATE public.nocase,
    tran_date timestamp without time zone,
    tran_qty numeric(25,2),
    tran_amount_acc_cur numeric(25,2),
    ctrl_acct_type character varying(30) COLLATE public.nocase,
    auto_post_acct_type character varying(30) COLLATE public.nocase,
    analysis_code character varying(10) COLLATE public.nocase,
    subanalysis_code character varying(10) COLLATE public.nocase,
    cost_center character varying(20) COLLATE public.nocase,
    item_code character varying(64) COLLATE public.nocase,
    item_variant character varying(20) COLLATE public.nocase,
    uom character varying(30) COLLATE public.nocase,
    supplier_code character varying(32) COLLATE public.nocase,
    acct_currency character varying(10) COLLATE public.nocase,
    base_amount numeric(25,2),
    par_exchange_rate numeric(25,2),
    par_base_amount numeric(25,2),
    narration character varying(510) COLLATE public.nocase,
    auth_date timestamp without time zone,
    ref_doc_ou integer,
    ref_doc_type character varying(20) COLLATE public.nocase,
    ref_doc_no character varying(36) COLLATE public.nocase,
    vat_usage_flag character varying(10) COLLATE public.nocase,
    posting_date timestamp without time zone,
    base_currency character varying(10) COLLATE public.nocase,
    account_type character varying(30) COLLATE public.nocase,
    batch_id character varying(256) COLLATE public.nocase,
    createdby character varying(60) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    ibe_flag character varying(24) COLLATE public.nocase,
    fin_year character varying(30) COLLATE public.nocase,
    fin_period character varying(30) COLLATE public.nocase,
    fbp_post_flag character varying(24) COLLATE public.nocase,
    hdrremarks character varying(510) COLLATE public.nocase,
    mlremarks character varying(510) COLLATE public.nocase,
    pdc_void_flag character varying(24) COLLATE public.nocase,
    instr_no character varying(60) COLLATE public.nocase,
    tranline_no integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_siacctinfodtl_pkey PRIMARY KEY (si_acct_info_dtl_key)
)
