CREATE TABLE dwh.f_stockbinhistorydetail (
    stock_bin_key bigint NOT NULL,
    stock_loc_key bigint NOT NULL,
    stock_thu_key bigint NOT NULL,
    stock_item_key bigint NOT NULL,
    stock_cust_key bigint NOT NULL,
    stock_ou integer,
    stock_date timestamp without time zone,
    stock_location character varying(20) COLLATE public.nocase,
    stock_zone character varying(20) COLLATE public.nocase,
    stock_bin character varying(20) COLLATE public.nocase,
    stock_bin_type character varying(40) COLLATE public.nocase,
    stock_customer character varying(40) COLLATE public.nocase,
    stock_item character varying(80) COLLATE public.nocase,
    stock_opening_bal numeric(13,2),
    stock_in_qty numeric(13,2),
    stock_out_qty numeric(13,2),
    stock_bin_qty numeric(13,2),
    stock_thu_id character varying(80) COLLATE public.nocase,
    stock_su_opening_bal numeric(13,2),
    stock_su_count_qty_in numeric(13,2),
    stock_su_count_qty_out numeric(13,2),
    stock_su_count_qty_bal numeric(13,2),
    stock_su character varying(20) COLLATE public.nocase,
    stock_thu_opening_bal numeric(13,2),
    stock_thu_count_qty_in numeric(13,2),
    stock_thu_count_qty_out numeric(13,2),
    stock_thu_count_qty_bal numeric(13,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    bin_dtl_key bigint
);