CREATE TABLE dwh.f_stockuidtrackingdetail (
    stk_trc_dtl_key bigint NOT NULL,
    stk_trc_dtl_loc_key bigint NOT NULL,
    stk_trc_dtl_zone_key bigint NOT NULL,
    stk_trc_dtl_bin_type_key bigint NOT NULL,
    stk_trc_dtl_customer_key bigint NOT NULL,
    stk_trc_dtl_thu_key bigint NOT NULL,
    stk_ou integer,
    stk_location character varying(20) COLLATE public.nocase,
    stk_zone character varying(20) COLLATE public.nocase,
    stk_bin character varying(20) COLLATE public.nocase,
    stk_bin_type character varying(40) COLLATE public.nocase,
    stk_staging_id character varying(40) COLLATE public.nocase,
    stk_stage character varying(80) COLLATE public.nocase,
    stk_customer character varying(40) COLLATE public.nocase,
    stk_uid_serial_no character varying(60) COLLATE public.nocase,
    stk_thu_id character varying(80) COLLATE public.nocase,
    stk_su character varying(20) COLLATE public.nocase,
    stk_from_date timestamp without time zone,
    stk_to_date timestamp without time zone,
    stk_from_tran_type character varying(50) COLLATE public.nocase,
    stk_to_tran_type character varying(50) COLLATE public.nocase,
    stk_from_tran_no character varying(40) COLLATE public.nocase,
    stk_to_tran_no character varying(40) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);