CREATE TABLE dwh.f_stockbalancestorageunitlotlevel (
    sbl_lot_level_key bigint NOT NULL,
    sbl_lot_level_wh_key bigint NOT NULL,
    sbl_lot_level_itm_hdr_key bigint NOT NULL,
    sbl_lot_level_zone_key bigint NOT NULL,
    sbl_lot_level_thu_key bigint NOT NULL,
    sbl_wh_code character varying(20) COLLATE public.nocase,
    sbl_ouinstid integer,
    sbl_item_code character varying(80) COLLATE public.nocase,
    sbl_lot_no character varying(60) COLLATE public.nocase,
    sbl_zone character varying(20) COLLATE public.nocase,
    sbl_bin character varying(20) COLLATE public.nocase,
    sbl_su character varying(20) COLLATE public.nocase,
    sbl_su_type character varying(20) COLLATE public.nocase,
    sbl_thu_id character varying(80) COLLATE public.nocase,
    sbl_stock_status character varying(20) COLLATE public.nocase,
    sbl_quantity numeric(132,0),
    sbl_su_serial_no character varying(80) COLLATE public.nocase,
    sbl_wh_bat_no character varying(60) COLLATE public.nocase,
    sbl_supp_bat_no character varying(60) COLLATE public.nocase,
    sbl_ido_no character varying(40) COLLATE public.nocase,
    sbl_gr_no character varying(40) COLLATE public.nocase,
    sbl_trantype character varying(50) COLLATE public.nocase,
    sbl_thu_serial_no character varying(60) COLLATE public.nocase,
    sbl_su_serial_no2 character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);