CREATE TABLE dwh.f_stockrejecteddetail (
    rejstk_dtl_key bigint NOT NULL,
    rejstk_dtl_loc_key bigint NOT NULL,
    rejstk_dtl_itm_hdr_key bigint NOT NULL,
    rejstk_dtl_thu_key bigint NOT NULL,
    rejstk_loc_code character varying(20) COLLATE public.nocase,
    rejstk_ou integer,
    rejstk_gr_no character varying(40) COLLATE public.nocase,
    rejstk_item_code character varying(80) COLLATE public.nocase,
    rejstk_gr_line_no integer,
    rejstk_rejected_qty numeric(20,2),
    rejstk_created_by character varying(60) COLLATE public.nocase,
    rejstk_created_date timestamp without time zone,
    rejstk_modified_by character varying(60) COLLATE public.nocase,
    rejstk_modified_date timestamp without time zone,
    rejstk_staging_id character varying(40) COLLATE public.nocase,
    rejstk_line_no integer,
    rejstk_lot_no character varying(60) COLLATE public.nocase,
    rejstk_gr_exec_no character varying(40) COLLATE public.nocase,
    rejstk_thuid character varying(80) COLLATE public.nocase,
    rejstk_thu_ser_no character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);