CREATE TABLE dwh.f_stockstoragebalancedetail (
    stk_su_dtl_key bigint NOT NULL,
    stk_su_loc_key bigint NOT NULL,
    stk_su_customer_key bigint NOT NULL,
    stk_ou integer,
    stk_location character varying(20) COLLATE public.nocase,
    stk_customer character varying(40) COLLATE public.nocase,
    stk_date timestamp without time zone,
    stk_su character varying(20) COLLATE public.nocase,
    stk_su_opn_bal numeric(20,2),
    stk_su_received numeric(20,2),
    stk_su_issued numeric(20,2),
    stk_su_cls_bal numeric(20,2),
    stk_su_peak_qty numeric(20,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);