CREATE TABLE dwh.f_stockconversiondetail (
    stk_con_dtl_key bigint NOT NULL,
    stk_con_hdr_key bigint NOT NULL,
    stk_con_dtl_loc_key bigint NOT NULL,
    stk_con_dtl_customer_key bigint NOT NULL,
    stk_con_dtl_itm_hdr_key bigint NOT NULL,
    stk_con_dtl_zone_key bigint NOT NULL,
    stk_con_loc_code character varying(20) COLLATE public.nocase,
    stk_con_proposal_no character varying(40) COLLATE public.nocase,
    stk_con_proposal_ou integer,
    stk_con_lineno integer,
    stk_con_cust_no character varying(40) COLLATE public.nocase,
    stk_con_item_code character varying(80) COLLATE public.nocase,
    stk_con_item_batch_no character varying(40) COLLATE public.nocase,
    stk_con_item_sr_no character varying(60) COLLATE public.nocase,
    stk_con_bin character varying(20) COLLATE public.nocase,
    stk_con_qty numeric(20,2),
    stk_con_from_status character varying(20) COLLATE public.nocase,
    stk_con_to_status character varying(20) COLLATE public.nocase,
    stk_con_from_qty numeric(20,2),
    stk_con_to_qty numeric(20,2),
    stk_con_status character varying(20) COLLATE public.nocase,
    stk_con_remarks character varying(510) COLLATE public.nocase,
    stk_con_su character varying(510) COLLATE public.nocase,
    stk_con_uid_serial_no character varying(510) COLLATE public.nocase,
    stk_con_zone character varying(20) COLLATE public.nocase,
    stk_con_batchno character varying(60) COLLATE public.nocase,
    stk_con_source_staging_id character varying(40) COLLATE public.nocase,
    stk_con_tar_bin character varying(20) COLLATE public.nocase,
    stk_gr_line_no integer,
    stk_gr_exec_no character varying(40) COLLATE public.nocase,
    stk_con_res_code character varying(510) COLLATE public.nocase,
    stk_wrtoff_qlty integer,
    stk_con_stksts character varying(20) COLLATE public.nocase,
    stk_con_from_thu_srno character varying(60) COLLATE public.nocase,
    stk_con_coo character varying(100) COLLATE public.nocase,
    stk_con_inven_type character varying(80) COLLATE public.nocase,
    stk_con_item_atrib1 character varying(100) COLLATE public.nocase,
    stk_con_item_atrib2 character varying(100) COLLATE public.nocase,
    stk_con_item_atrib3 character varying(100) COLLATE public.nocase,
    stk_con_prod_status character varying(80) COLLATE public.nocase,
    stk_con_stk_lineno integer,
    stk_con_curr_stock_qty numeric(20,2),
    stk_con_item_atrib6 character varying(100) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);