CREATE TABLE dwh.f_stockconversionheader (
    stk_con_hdr_key bigint NOT NULL,
    stk_con_loc_key bigint NOT NULL,
    stk_con_date_key bigint NOT NULL,
    stk_con_loc_code character varying(20) COLLATE public.nocase,
    stk_con_proposal_no character varying(40) COLLATE public.nocase,
    stk_con_proposal_ou integer,
    stk_con_proposal_date timestamp without time zone,
    stk_con_proposal_status character varying(20) COLLATE public.nocase,
    stk_con_proposal_type character varying(20) COLLATE public.nocase,
    stk_con_ref_doc_no character varying(40) COLLATE public.nocase,
    stk_con_approver character varying(50) COLLATE public.nocase,
    stk_con_remarks character varying(510) COLLATE public.nocase,
    stk_con_created_by character varying(60) COLLATE public.nocase,
    stk_con_created_date timestamp without time zone,
    stk_con_modified_by character varying(60) COLLATE public.nocase,
    stk_con_modified_date timestamp without time zone,
    stk_con_timestamp integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);