CREATE TABLE dwh.f_surreceiptdtl (
    surreceiptdtl_key bigint NOT NULL,
    surreceiptdtl_curr_key bigint NOT NULL,
    surreceiptdtl_opcoa_key bigint NOT NULL,
    ou_id integer,
    receipt_type character varying(10) COLLATE public.nocase,
    receipt_no character varying(40) COLLATE public.nocase,
    refdoc_lineno integer,
    tran_type character varying(80) COLLATE public.nocase,
    stimestamp integer,
    usage character varying(40) COLLATE public.nocase,
    account_code character varying(80) COLLATE public.nocase,
    currency_code character varying(10) COLLATE public.nocase,
    account_amount numeric(25,2),
    drcr_flag character varying(10) COLLATE public.nocase,
    base_amount numeric(25,2),
    remarks character varying(510) COLLATE public.nocase,
    cost_center character varying(20) COLLATE public.nocase,
    analysis_code character varying(10) COLLATE public.nocase,
    subanalysis_code character varying(10) COLLATE public.nocase,
    batch_id character varying(300) COLLATE public.nocase,
    acct_type character varying(30) COLLATE public.nocase,
    createdby character varying(60) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    item_desc character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);