CREATE TABLE IF NOT EXISTS dwh.f_tcaltaxdtl
(
    f_tcal_tax_dtl_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tax_type character varying(50) COLLATE public.nocase,
    tran_type character varying(20) COLLATE public.nocase,
    tran_no character varying(36) COLLATE public.nocase,
    tran_ou integer,
    tran_line_no integer,
    tax_line_no integer,
    tax_code character varying(20) COLLATE public.nocase,
    code_type character varying(20) COLLATE public.nocase,
    tax_rate numeric(13,2),
    tax_basis character varying(10) COLLATE public.nocase,
    taxable_amt numeric(20,2),
    comp_tax_amt numeric(20,2),
    corr_tax_amt numeric(20,2),
    comp_tax_amt_bascurr numeric(20,2),
    corr_tax_amt_bascurr numeric(20,2),
    created_by character varying(60) COLLATE public.nocase,
    created_date timestamp without time zone,
    modified_by character varying(60) COLLATE public.nocase,
    modified_date timestamp without time zone,
    tax_group character varying(20) COLLATE public.nocase,
    ref_doc_line_no integer,
    taxable_amt_base numeric(20,2),
    tax_community character varying(50) COLLATE public.nocase,
    commodity_code character varying(80) COLLATE public.nocase,
    original_tax_code character varying(20) COLLATE public.nocase,
    original_tax_rate numeric(20,2),
    threshold_flag character varying(24) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_tcal_tax_dtl_pkey PRIMARY KEY (f_tcal_tax_dtl_key),
    CONSTRAINT f_tcal_tax_dtl_ukey UNIQUE (tax_type, tran_type, tran_no, tran_ou, tran_line_no, tax_line_no)
)
