CREATE TABLE dwh.f_triplogthudetail (
    tltd_tpthd_key bigint NOT NULL,
    plpth_hdr_key bigint NOT NULL,
    tltd_vendor_key bigint NOT NULL,
    tltd_ouinstance integer,
    tltd_trip_plan_id character varying(40) COLLATE public.nocase,
    tltd_trip_plan_line_id character varying(300) COLLATE public.nocase,
    tltd_dispatch_doc_no character varying(40) COLLATE public.nocase,
    tltd_thu_line_no character varying(300) COLLATE public.nocase,
    tltd_thu_id character varying(80) COLLATE public.nocase,
    tltd_class_of_stores character varying(80) COLLATE public.nocase,
    tltd_planned_qty numeric(25,2),
    tltd_thu_actual_qty numeric(25,2),
    tltd_damaged_qty numeric(25,2),
    tltd_vendor_id character varying(40) COLLATE public.nocase,
    tltd_vendor_thu_type character varying(80) COLLATE public.nocase,
    tltd_vendor_thu_id character varying(80) COLLATE public.nocase,
    tltd_vendor_doc_no character varying(80) COLLATE public.nocase,
    tltd_vendor_ac_no character varying(80) COLLATE public.nocase,
    tltd_cha_id character varying(80) COLLATE public.nocase,
    tltd_created_date character varying(50) COLLATE public.nocase,
    tltd_created_by character varying(60) COLLATE public.nocase,
    tltd_modified_date character varying(50) COLLATE public.nocase,
    tltd_modified_by character varying(60) COLLATE public.nocase,
    tltd_timestamp integer,
    tltd_transfer_type character varying(80) COLLATE public.nocase,
    tltd_remarks character varying(80) COLLATE public.nocase,
    tltd_trip_sequence integer,
    tltd_thu_weight numeric(25,2),
    tltd_rsncode_damage character varying(80) COLLATE public.nocase,
    tltd_thu_weight_uom character varying(30) COLLATE public.nocase,
    tltd_reasoncode_remarks character varying(510) COLLATE public.nocase,
    tltd_damaged_reasoncode character varying(80) COLLATE public.nocase,
    tltd_returned_reasoncode character varying(80) COLLATE public.nocase,
    tltd_actual_planned_mismatch_reason character varying(80) COLLATE public.nocase,
    tltd_actual_pallet_space integer,
    tltd_returned_qty integer,
    tltd_planned_palletspace integer,
    tltd_actual_palletspace integer,
    tltd_volume numeric(25,2),
    tltd_volume_uom character varying(30) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);