CREATE TABLE dwh.f_tripvendortariffrevcostdetail (
    tvtrcd_dtl_key bigint NOT NULL,
    tvtrcd_hdr_key bigint NOT NULL,
    tvtrcd_ouinstance integer,
    tvtrcd_trip_plan_id character varying(80) COLLATE public.nocase,
    tvtrcd_booking_request character varying(80) COLLATE public.nocase,
    tvtrcd_unique_id character varying(300) COLLATE public.nocase,
    tvtrcd_leg_id character varying(80) COLLATE public.nocase,
    tvtrcd_buy_sell_type character varying(80) COLLATE public.nocase,
    tvtrcd_stage_of_derivation character varying(80) COLLATE public.nocase,
    tvtrcd_date_of_stage timestamp without time zone,
    tvtrcd_contract_id character varying(80) COLLATE public.nocase,
    tvtrcd_tariff_id character varying(80) COLLATE public.nocase,
    tvtrcd_tariff_type character varying(80) COLLATE public.nocase,
    tvtrcd_rate numeric(13,2),
    tvtrcd_remarks character varying(510) COLLATE public.nocase,
    tvtrcd_trip_rev_cost_sk character varying(300) COLLATE public.nocase,
    tvtrcd_trip_plan_hdr_sk character varying(300) COLLATE public.nocase,
    tvtrcd_created_by character varying(80) COLLATE public.nocase,
    tvtrcd_created_date character varying(80) COLLATE public.nocase,
    tvtrcd_modified_by character varying(80) COLLATE public.nocase,
    tvtrcd_modified_date timestamp without time zone,
    tvtrcd_time_stamp integer,
    tvtrcd_resource_type character varying(80) COLLATE public.nocase,
    tvtrcd_weight numeric(13,2),
    tvtrcd_weight_uom character varying(20) COLLATE public.nocase,
    tvtrcd_pallet numeric(13,2),
    tvtrcd_chk_flag character varying(10) COLLATE public.nocase,
    tvtrcd_vendor_flag character varying(10) COLLATE public.nocase,
    tvtrcd_tariff_remarks character varying(8000) COLLATE public.nocase,
    tvtrcd_resource_id character varying(80) COLLATE public.nocase,
    tvtrcd_amendment_no integer,
    tvtrcd_fl_tariff_id character varying(80) COLLATE public.nocase,
    tvtrcd_agreed_rate numeric(13,2),
    tvtrcd_agreed_cost numeric(13,2),
    tvtrcd_charagable_quantity numeric(13,2),
    tvtrcd_exchange_rate numeric(13,2),
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);