CREATE TABLE dwh.f_trippodattachmentdetail (
    tpad_dtl_key bigint NOT NULL,
    tpad_trip_hdr_key bigint NOT NULL,
    tpad_ouinstance integer,
    tpad_trip_id character varying(80) COLLATE public.nocase,
    tpad_seqno integer,
    tpad_line_no character varying(300) COLLATE public.nocase,
    tpad_doc_no character varying(80) COLLATE public.nocase,
    tpad_document_code character varying(80) COLLATE public.nocase,
    tpad_attachment_file_name character varying(510) COLLATE public.nocase,
    tpad_attachment character varying(8000) COLLATE public.nocase,
    tpad_remarks character varying(510) COLLATE public.nocase,
    tpad_created_by character varying(60) COLLATE public.nocase,
    tpad_created_date timestamp without time zone,
    tpad_last_updated_by character varying(60) COLLATE public.nocase,
    tpad_last_updated_date timestamp without time zone,
    tpad_timestamp integer,
    tpad_addln_doc_no character varying(80) COLLATE public.nocase,
    tpad_doc_type character varying(80) COLLATE public.nocase,
    tpad_hdn_file_name character varying(510) COLLATE public.nocase,
    tpad_parent_guid character varying(300) COLLATE public.nocase,
    tpad_dispatch_doc_no character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);