-- Table: dwh.f_tstltaxhdr

-- DROP TABLE IF EXISTS dwh.f_tstltaxhdr;

CREATE TABLE IF NOT EXISTS dwh.f_tstltaxhdr
(
    tstl_tax_hdr_key bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tran_no character varying(40) COLLATE public.nocase,
    tax_type character varying(50) COLLATE public.nocase,
    tran_type character varying(20) COLLATE public.nocase,
    tran_ou integer,
    tran_line_no integer,
    own_tax_region character varying(20) COLLATE public.nocase,
    own_regd_no character varying(80) COLLATE public.nocase,
    party_tax_region character varying(20) COLLATE public.nocase,
    party_regd_no character varying(80) COLLATE public.nocase,
    decl_tax_region character varying(20) COLLATE public.nocase,
    tax_category character varying(80) COLLATE public.nocase,
    tax_class character varying(80) COLLATE public.nocase,
    tax_register character varying(20) COLLATE public.nocase,
    tax_reference character varying(20) COLLATE public.nocase,
    ref_doc_type character varying(20) COLLATE public.nocase,
    ref_doc_no character varying(36) COLLATE public.nocase,
    ref_doc_ou integer,
    item_tc_type character varying(20) COLLATE public.nocase,
    item_tc_usage_id character varying(64) COLLATE public.nocase,
    item_tc_variant character varying(20) COLLATE public.nocase,
    distrib_charge numeric(20,2),
    distrib_disc numeric(20,2),
    tax_uom character varying(20) COLLATE public.nocase,
    quantity numeric(20,2),
    basic_amt numeric(20,2),
    stat_tax numeric(20,2),
    tc_amt numeric(20,2),
    disc_amt numeric(20,2),
    taxable_amt numeric(20,2),
    taxable_perc numeric(20,2),
    nontax_tc_amt numeric(20,2),
    nontax_disc_amt numeric(20,2),
    comp_tax_amt numeric(20,2),
    corr_tax_amt numeric(20,2),
    comp_tax_amt_bascurr numeric(20,2),
    corr_tax_amt_bascurr numeric(20,2),
    item_value_bascurr numeric(20,2),
    distr_tc_bascurr numeric(20,2),
    distr_disc_bascurr numeric(20,2),
    stat_tax_bascurr numeric(20,2),
    tc_amt_bascurr numeric(20,2),
    disc_amt_bascurr numeric(20,2),
    non_tax_base_tc numeric(20,2),
    non_tax_base_disc numeric(20,2),
    trade_type character varying(50) COLLATE public.nocase,
    remit_due_date timestamp without time zone,
    cert_gen_date timestamp without time zone,
    incorporation_date timestamp without time zone,
    decl_year character varying(20) COLLATE public.nocase,
    decl_period character varying(30) COLLATE public.nocase,
    created_by character varying(60) COLLATE public.nocase,
    created_date timestamp without time zone,
    modified_by character varying(60) COLLATE public.nocase,
    modified_date timestamp without time zone,
    tax_jv_no character varying(36) COLLATE public.nocase,
    tax_status character varying(80) COLLATE public.nocase,
    weightage_factor integer,
    tax_incl_amount numeric(20,2),
    tax_excl_amount numeric(20,2),
    taxable_amt_bascur numeric(20,2),
    tax_tran_date timestamp without time zone,
    tax_supp_cust_code character varying(36) COLLATE public.nocase,
    tax_party_type character varying(50) COLLATE public.nocase,
    tax_assessee_type character varying(80) COLLATE public.nocase,
    tax_fbid character varying(40) COLLATE public.nocase,
    refdoc_line_no integer,
    dedtax_amt numeric(20,2),
    dedtax_amt_bascurr numeric(20,2),
    drcr_flag character varying(20) COLLATE public.nocase,
    tax_exc_amt numeric(20,2),
    tax_inc_amt numeric(20,2),
    taxcommunity character varying(50) COLLATE public.nocase,
    taxableamt_base numeric(20,2),
    ware_house character varying(20) COLLATE public.nocase,
    tdstran_amt numeric(20,2),
    conref_doc_no character varying(40) COLLATE public.nocase,
    conref_doc_ou integer,
    conref_doc_type character varying(20) COLLATE public.nocase,
    shipto_id character varying(20) COLLATE public.nocase,
    sec_heading character varying(50) COLLATE public.nocase,
    sub_heading character varying(50) COLLATE public.nocase,
    shipto_statecode character varying(30) COLLATE public.nocase,
    billto_statecode character varying(30) COLLATE public.nocase,
    shipto_country character varying(80) COLLATE public.nocase,
    billto_country character varying(80) COLLATE public.nocase,
    cp_return_frequency character varying(80) COLLATE public.nocase,
    claim_refund_flag character varying(80) COLLATE public.nocase,
    prov_itc_flag character varying(80) COLLATE public.nocase,
    pos_state_code character varying(510) COLLATE public.nocase,
    rev_charge_flag character varying(510) COLLATE public.nocase,
    ret1_new_classification character varying(80) COLLATE public.nocase,
    sec7act character varying(510) COLLATE public.nocase,
    new_return_status character varying(50) COLLATE public.nocase,
    ref_doc_date timestamp without time zone,
    invoice_type character varying(80) COLLATE public.nocase,
    sub_supply_type character varying(50) COLLATE public.nocase,
    trans_mode character varying(80) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    CONSTRAINT f_tstl_tax_hdr_pkey PRIMARY KEY (tstl_tax_hdr_key),
    CONSTRAINT f_tstl_tax_hdr_ukey UNIQUE (tran_no, tax_type, tran_type, tran_ou, tran_line_no)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dwh.f_tstltaxhdr
    OWNER to proconnect;
-- Index: f_tstl_tax_hdr_key_idx

-- DROP INDEX IF EXISTS dwh.f_tstl_tax_hdr_key_idx;

CREATE INDEX IF NOT EXISTS f_tstl_tax_hdr_key_idx
    ON dwh.f_tstltaxhdr USING btree
    (tran_no COLLATE public.nocase ASC NULLS LAST, tax_type COLLATE public.nocase ASC NULLS LAST, tran_type COLLATE public.nocase ASC NULLS LAST, tran_ou ASC NULLS LAST, tran_line_no ASC NULLS LAST)
    TABLESPACE pg_default;