CREATE TABLE raw.raw_wms_draft_bill_exec_dtl (
    raw_id bigint NOT NULL,
    wms_exec_loc_code character varying(40) NOT NULL COLLATE public.nocase,
    wms_exec_ou integer NOT NULL,
    wms_exec_no character varying(72) NOT NULL COLLATE public.nocase,
    wms_exec_stage character varying(100) NOT NULL COLLATE public.nocase,
    wms_exec_line_no integer NOT NULL,
    wms_exec_executed_on timestamp without time zone,
    wms_exec_customer_id character varying(72) COLLATE public.nocase,
    wms_exec_ref_doc_type character varying(32) COLLATE public.nocase,
    wms_exec_ref_doc_no character varying(72) COLLATE public.nocase,
    wms_exec_ref_doc_line_no integer,
    wms_exec_ref_doc_sch_no integer,
    wms_exec_tran_qty numeric,
    wms_exec_item_lot_no character varying(112) COLLATE public.nocase,
    wms_exec_item_batch_no character varying(112) COLLATE public.nocase,
    wms_exec_item_serial_no character varying(112) COLLATE public.nocase,
    wms_exec_thu_id character varying(160) COLLATE public.nocase,
    wms_exec_thu_ser_no character varying(112) COLLATE public.nocase,
    wms_exec_uid character varying(160) COLLATE public.nocase,
    wms_exec_uid_ser_no character varying(112) COLLATE public.nocase,
    wms_exec_billing_status character varying(32) COLLATE public.nocase,
    wms_exec_bill_value numeric,
    wms_exec_item_code character varying(128) COLLATE public.nocase,
    wms_exec_su character varying(40) COLLATE public.nocase,
    wms_exec_lbchprhr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pickchrg_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pkpalthu_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_tchpalpk_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_thupkchr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_kmsslbpr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pkmxitm_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_unitpunp_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_palrestk_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_conschrg_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_cstchcon_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_flherffn_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdlopick_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdochwt_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_lodtpalc_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdochitm_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdipitrb_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdipsurb_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_damagadj_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_shpcbitq_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_vaschrg_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdlomuom_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_rfpcexwh_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_rfwcexwh_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_whtrchpk_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdimugr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdomupk_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_cupakchr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_consbchg_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdimetr_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdomepk_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdlioutc_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_damagadj_buy_bil_status character varying(72) COLLATE public.nocase,
    wms_exec_hdomuld_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdomeld_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdiochvl_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pkchrgui_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdchincbm_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hcdeinqt_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdchinqt_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdchinpt_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_whobferb_sell_bil_status character varying(160) COLLATE public.nocase,
    wms_exec_pthuc_status character varying(32) COLLATE public.nocase,
    wms_exec_pikpakqt_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_himluogr_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_homstpld_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hiochvol_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_houpmton_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pisamfee_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_pklicnt_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdichgei_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdoqcld_status character varying(32) COLLATE public.nocase,
    wms_exec_cusbsdcg_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_cuspakcg_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hothupkq_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdovcld_bill_status character varying(32) COLLATE public.nocase,
    wms_exec_hcoqumot_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_houtptld_sell_bil_status character varying(32) COLLATE public.nocase,
    wms_exec_hdlncopt_bil_status character varying(100) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_wms_draft_bill_exec_dtl ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_wms_draft_bill_exec_dtl_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_wms_draft_bill_exec_dtl
    ADD CONSTRAINT raw_wms_draft_bill_exec_dtl_pkey PRIMARY KEY (raw_id);