CREATE TABLE IF NOT EXISTS "raw".raw_sin_tcd_dtl
(
    raw_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tran_type character varying(20) COLLATE pg_catalog."default",
    tran_ou integer,
    tran_no character varying(36) COLLATE pg_catalog."default",
    line_no integer,
    item_tcd_code character varying(64) COLLATE pg_catalog."default",
    tcd_version integer,
    item_tcd_var character varying(64) COLLATE pg_catalog."default",
    "timestamp" integer,
    item_type character varying(10) COLLATE pg_catalog."default",
    tcd_level character varying(10) COLLATE pg_catalog."default",
    tcd_rate numeric(20,2),
    taxable_amount numeric(20,2),
    tcd_amount numeric(20,2),
    tcd_currency character varying(10) COLLATE pg_catalog."default",
    base_amount numeric(20,2),
    par_base_amount numeric(20,2),
    cost_center character varying(20) COLLATE pg_catalog."default",
    analysis_code character varying(10) COLLATE pg_catalog."default",
    subanalysis_code character varying(10) COLLATE pg_catalog."default",
    remarks character varying(1000) COLLATE pg_catalog."default",
    proposed_amount numeric(20,2),
    original_proposed_amt numeric(20,2),
    createdby character varying(60) COLLATE pg_catalog."default",
    createddate timestamp without time zone,
    modifiedby character varying(60) COLLATE pg_catalog."default",
    modifieddate timestamp without time zone,
    tms_flag character varying(10) COLLATE pg_catalog."default",
    etlcreateddatetime timestamp(3) without time zone
)