CREATE TABLE raw.raw_wms_equipment_hdr (
    raw_id bigint NOT NULL,
    wms_eqp_ou integer NOT NULL,
    wms_eqp_equipment_id character varying(120) NOT NULL COLLATE public.nocase,
    wms_eqp_description character varying(1020) COLLATE public.nocase,
    wms_eqp_status character varying(32) COLLATE public.nocase,
    wms_eqp_reasoncode character varying(160) COLLATE public.nocase,
    wms_eqp_type character varying(160) COLLATE public.nocase,
    wms_eqp_category character varying(160) COLLATE public.nocase,
    wms_eqp_reference_id character varying(120) COLLATE public.nocase,
    wms_eqp_asset_id character varying(72) COLLATE public.nocase,
    wms_eqp_asset_tag integer,
    wms_eqp_registration_num character varying(160) COLLATE public.nocase,
    wms_eqp_registration_name character varying(160) COLLATE public.nocase,
    wms_eqp_hazardous_goods integer,
    wms_eqp_owner_type character varying(32) COLLATE public.nocase,
    wms_eqp_agencyid character varying(64) COLLATE public.nocase,
    wms_eqp_registration_eff_date timestamp without time zone,
    wms_eqp_agency_contract_num character varying(64) COLLATE public.nocase,
    wms_eqp_registration_address character varying(1020) COLLATE public.nocase,
    wms_eqp_mfg_name character varying(160) COLLATE public.nocase,
    wms_eqp_mfg_date timestamp without time zone,
    wms_eqp_purchase_date timestamp without time zone,
    wms_eqp_inducted_date timestamp without time zone,
    wms_eqp_running_cost numeric,
    wms_eqp_unit character varying(40) COLLATE public.nocase,
    wms_eqp_ref_doc_number character varying(160) COLLATE public.nocase,
    wms_eqp_default_location character varying(40) COLLATE public.nocase,
    wms_eqp_current_location character varying(72) COLLATE public.nocase,
    wms_eqp_in_current_location timestamp without time zone,
    wms_eqp_weight_uom character varying(40) COLLATE public.nocase,
    wms_eqp_tare numeric,
    wms_eqp_max_allowable numeric,
    wms_eqp_interior_uom character varying(40) COLLATE public.nocase,
    wms_eqp_interior_length numeric,
    wms_eqp_interior_width numeric,
    wms_eqp_interior_height numeric,
    wms_eqp_exterior_uom character varying(40) COLLATE public.nocase,
    wms_eqp_exterior_length numeric,
    wms_eqp_exterior_width numeric,
    wms_eqp_exterior_height numeric,
    wms_eqp_temperature_uom character varying(40) COLLATE public.nocase,
    wms_eqp_temperature_minimum numeric,
    wms_eqp_temperature_maximum numeric,
    wms_eqp_volume numeric,
    wms_eqp_volume_uom character varying(40) COLLATE public.nocase,
    wms_eqp_teu_count numeric,
    wms_eqp_feu_count numeric,
    wms_eqp_life_eqp_capacity character varying(40) COLLATE public.nocase,
    wms_eqp_load_lift numeric,
    wms_eqp_height_lift numeric,
    wms_eqp_timestamp integer,
    wms_eqp_created_date timestamp without time zone,
    wms_eqp_created_by character varying(120) COLLATE public.nocase,
    wms_eqp_modified_date timestamp without time zone,
    wms_eqp_modified_by character varying(120) COLLATE public.nocase,
    wms_eqp_userdefined1 character varying(1020) COLLATE public.nocase,
    wms_eqp_userdefined2 character varying(1020) COLLATE public.nocase,
    wms_eqp_userdefined3 character varying(1020) COLLATE public.nocase,
    wms_eqp_intransit integer,
    wms_eqp_route character varying(72) COLLATE public.nocase,
    wms_eqp_between character varying(1020) COLLATE public.nocase,
    wms_eqp_and character varying(1020) COLLATE public.nocase,
    wms_eqp_gross_comb_mass numeric,
    wms_eqp_gross_veh_mass numeric,
    wms_eqp_overall_vol numeric,
    wms_eqp_internal_vol numeric,
    wms_eqp_refrigerated integer,
    wms_eqp_load_lift_uom character varying(40) COLLATE public.nocase,
    wms_eqp_height_lift_uom character varying(40) COLLATE public.nocase,
    wms_eqp_no_of_axles integer,
    wms_veh_current_loc_desc character varying(1020) COLLATE public.nocase,
    wms_veh_home_loc_desc character varying(1020) COLLATE public.nocase,
    wms_veh_home_geo_type character varying(1020) COLLATE public.nocase,
    wms_veh_current_geo_type character varying(1020) COLLATE public.nocase,
    wms_equip_ownrshp_eftfrm timestamp without time zone,
    wms_eqp_pallet_space integer,
    wms_eqp_raise_int_drfbill integer,
    wms_chassis_number character varying(160) COLLATE public.nocase,
    wms_min_weight numeric,
    wms_max_weight numeric,
    wms_min_length numeric,
    wms_load_carrying_weight_uom character varying(40) COLLATE public.nocase,
    wms_max_lenght numeric,
    wms_min_width numeric,
    wms_max_width numeric,
    wms_min_height numeric,
    wms_max_height numeric,
    wms_load_carrying_uom character varying(40) COLLATE public.nocase,
    wms_eqp_make character varying(160) COLLATE public.nocase,
    wms_eqp_model character varying(160) COLLATE public.nocase,
    wms_eqp_gen_uom character varying(40) COLLATE public.nocase,
    wms_eqp_gen_coupled numeric,
    wms_eqp_gen_coupled_loaded numeric,
    wms_eqp_emp_id character varying(160) COLLATE public.nocase,
    wms_eqp_commodity character varying(160) COLLATE public.nocase,
    wms_eqp_cls_of_stores character varying(160) COLLATE public.nocase,
    wms_eqp_last_bill_date timestamp without time zone,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_wms_equipment_hdr ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_wms_equipment_hdr_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_wms_equipment_hdr
    ADD CONSTRAINT raw_wms_equipment_hdr_pkey PRIMARY KEY (raw_id);