-- Table: raw.raw_tstl_tax_hdr

-- DROP TABLE IF EXISTS "raw".raw_tstl_tax_hdr;

CREATE TABLE IF NOT EXISTS "raw".raw_tstl_tax_hdr
(
    raw_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tran_no character varying(40) COLLATE public.nocase,
    tax_type character varying(50) COLLATE public.nocase,
    tran_type character varying(20) COLLATE public.nocase,
    tran_ou integer,
    tran_line_no integer,
    own_tax_region character varying(20) COLLATE public.nocase,
    own_regd_no character varying(80) COLLATE public.nocase,
    party_tax_region character varying(20) COLLATE public.nocase,
    party_regd_no character varying(80) COLLATE public.nocase,
    decl_tax_region character varying(20) COLLATE public.nocase,
    tax_category character varying(80) COLLATE public.nocase,
    tax_class character varying(80) COLLATE public.nocase,
    tax_register character varying(20) COLLATE public.nocase,
    tax_reference character varying(20) COLLATE public.nocase,
    ref_doc_type character varying(20) COLLATE public.nocase,
    ref_doc_no character varying(36) COLLATE public.nocase,
    ref_doc_ou integer,
    item_tc_type character varying(20) COLLATE public.nocase,
    item_tc_usage_id character varying(64) COLLATE public.nocase,
    item_tc_variant character varying(20) COLLATE public.nocase,
    distrib_charge numeric(20,2),
    distrib_disc numeric(20,2),
    tax_uom character varying(20) COLLATE public.nocase,
    quantity numeric(20,2),
    basic_amt numeric(20,2),
    stat_tax numeric(20,2),
    tc_amt numeric(20,2),
    disc_amt numeric(20,2),
    taxable_amt numeric(20,2),
    taxable_perc numeric(20,2),
    nontax_tc_amt numeric(20,2),
    nontax_disc_amt numeric(20,2),
    comp_tax_amt numeric(20,2),
    corr_tax_amt numeric(20,2),
    comp_tax_amt_bascurr numeric(20,2),
    corr_tax_amt_bascurr numeric(20,2),
    item_value_bascurr numeric(20,2),
    distr_tc_bascurr numeric(20,2),
    distr_disc_bascurr numeric(20,2),
    stat_tax_bascurr numeric(20,2),
    tc_amt_bascurr numeric(20,2),
    disc_amt_bascurr numeric(20,2),
    non_tax_base_tc numeric(20,2),
    non_tax_base_disc numeric(20,2),
    trade_type character varying(50) COLLATE public.nocase,
    remit_due_date timestamp without time zone,
    cert_gen_date timestamp without time zone,
    incorporation_date timestamp without time zone,
    decl_year character varying(20) COLLATE public.nocase,
    decl_period character varying(30) COLLATE public.nocase,
    addnl_param1 integer,
    addnl_param2 numeric(20,2),
    addnl_param3 character varying(80) COLLATE public.nocase,
    addnl_param4 character varying(510) COLLATE public.nocase,
    created_by character varying(60) COLLATE public.nocase,
    created_date timestamp without time zone,
    modified_by character varying(60) COLLATE public.nocase,
    modified_date timestamp without time zone,
    tax_jv_no character varying(36) COLLATE public.nocase,
    tax_status character varying(80) COLLATE public.nocase,
    weightage_factor integer,
    tax_incl_amount numeric(20,2),
    tax_excl_amount numeric(20,2),
    taxable_amt_bascur numeric(20,2),
    tax_tran_date timestamp without time zone,
    tax_supp_cust_code character varying(36) COLLATE public.nocase,
    tax_party_type character varying(50) COLLATE public.nocase,
    tax_assessee_type character varying(80) COLLATE public.nocase,
    tax_fbid character varying(40) COLLATE public.nocase,
    refdoc_line_no integer,
    tax_doc_type character varying(510) COLLATE public.nocase,
    tax_doc_no character varying(36) COLLATE public.nocase,
    dedtax_amt numeric(20,2),
    dedtax_amt_bascurr numeric(20,2),
    drcr_flag character varying(20) COLLATE public.nocase,
    tax_exc_amt numeric(20,2),
    tax_inc_amt numeric(20,2),
    taxcommunity character varying(50) COLLATE public.nocase,
    taxableamt_base numeric(20,2),
    ware_house character varying(20) COLLATE public.nocase,
    tdstran_amt numeric(20,2),
    conref_doc_no character varying(40) COLLATE public.nocase,
    conref_doc_ou integer,
    conref_doc_type character varying(20) COLLATE public.nocase,
    ttrantaxable_amt numeric(20,2),
    ttrantax_amt numeric(20,2),
    ttrantaxable_bascur numeric(20,2),
    ttrantax_bascur numeric(20,2),
    tax_amt_inv numeric(20,2),
    proc_action character varying(16) COLLATE public.nocase,
    shipto_id character varying(20) COLLATE public.nocase,
    ttrantax_class character varying(80) COLLATE public.nocase,
    propwht_amt numeric(20,2),
    appwht_amt numeric(20,2),
    noofinst integer,
    boe_no character varying(40) COLLATE public.nocase,
    boe_date timestamp(3) without time zone,
    adjusted_amount numeric(20,2),
    port_code character varying(510) COLLATE public.nocase,
    filed_year character varying(20) COLLATE public.nocase,
    filed_period character varying(30) COLLATE public.nocase,
    sec_heading character varying(50) COLLATE public.nocase,
    sub_heading character varying(50) COLLATE public.nocase,
    shipto_statecode character varying(30) COLLATE public.nocase,
    billto_statecode character varying(30) COLLATE public.nocase,
    shipto_country character varying(80) COLLATE public.nocase,
    billto_country character varying(80) COLLATE public.nocase,
    recon_year character varying(20) COLLATE public.nocase,
    recon_period character varying(30) COLLATE public.nocase,
    recon_date timestamp(3) without time zone,
    return_year character varying(20) COLLATE public.nocase,
    return_period character varying(30) COLLATE public.nocase,
    cp_return_frequency character varying(80) COLLATE public.nocase,
    claim_refund_flag character varying(80) COLLATE public.nocase,
    prov_itc_flag character varying(80) COLLATE public.nocase,
    pos_state_code character varying(510) COLLATE public.nocase,
    rev_charge_flag character varying(510) COLLATE public.nocase,
    ret1_new_classification character varying(80) COLLATE public.nocase,
    sec7act character varying(510) COLLATE public.nocase,
    new_return_status character varying(50) COLLATE public.nocase,
    ref_doc_date timestamp without time zone,
    invoice_type character varying(80) COLLATE public.nocase,
    sub_supply_type character varying(50) COLLATE public.nocase,
    trans_mode character varying(80) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    CONSTRAINT raw_tstl_tax_hdr_pkey PRIMARY KEY (raw_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "raw".raw_tstl_tax_hdr
    OWNER to proconnect;