CREATE TABLE raw.raw_fact_outbound_load (
    raw_id bigint NOT NULL,
    surrogatekey character varying(400) NOT NULL COLLATE public.nocase,
    tran_type character varying(100) NOT NULL COLLATE public.nocase,
    refkey character varying(400) NOT NULL COLLATE public.nocase,
    load_ou integer NOT NULL,
    load_loc_code character varying(40) NOT NULL COLLATE public.nocase,
    loading_ld_sheet_no character varying(72) COLLATE public.nocase,
    loading_ld_sheet_date timestamp without time zone,
    loading_ld_sheet_status character varying(32) COLLATE public.nocase,
    loading_dock_no character varying(72) COLLATE public.nocase,
    loading_ready_load integer,
    loading_lsp character varying(64) COLLATE public.nocase,
    loading_actual_lsp character varying(64) COLLATE public.nocase,
    loading_remarks character varying(1020) COLLATE public.nocase,
    loading_thu_id character varying(160) COLLATE public.nocase,
    loading_ship_point character varying(72) COLLATE public.nocase,
    loading_disp_doc_type character varying(32) COLLATE public.nocase,
    loading_disp_doc_no character varying(72) COLLATE public.nocase,
    loading_thu_desc character varying(1020) COLLATE public.nocase,
    loading_thu_class character varying(160) COLLATE public.nocase,
    loading_thu_sr_no character varying(112) COLLATE public.nocase,
    loading_thu_acc character varying(280) COLLATE public.nocase,
    loading_disp_doc_date timestamp without time zone,
    loading_loading_status character varying(32) COLLATE public.nocase,
    loading_pal_qty numeric,
    loading_tran_typ character varying(32) COLLATE public.nocase,
    loading_ven_thuid character varying(160) COLLATE public.nocase,
    loading_source_stage character varying(1020) COLLATE public.nocase,
    loading_source_docno character varying(72) COLLATE public.nocase,
    loading_pln_created_by character varying(120) COLLATE public.nocase,
    loading_pln_created_date timestamp without time zone,
    loading_pln_modified_by character varying(120) COLLATE public.nocase,
    loading_pln_modified_date timestamp without time zone,
    loading_pln_userdefined1 character varying(1020) COLLATE public.nocase,
    loading_pln_userdefined2 character varying(1020) COLLATE public.nocase,
    loading_pln_userdefined3 character varying(1020) COLLATE public.nocase,
    loading_exec_no character varying(72) COLLATE public.nocase,
    loading_exec_date timestamp without time zone,
    loading_exec_status character varying(32) COLLATE public.nocase,
    loading_lineno integer,
    loading_start_date_time timestamp without time zone,
    loading_end_date_time timestamp without time zone,
    unload_flag character varying(60) COLLATE public.nocase,
    loading_reason_code character varying(1020) COLLATE public.nocase,
    loading_userdef1 character varying(1020) COLLATE public.nocase,
    loading_userdef2 character varying(1020) COLLATE public.nocase,
    loading_userdef3 character varying(1020) COLLATE public.nocase,
    loading_userdef4 timestamp without time zone,
    loading_userdef5 timestamp without time zone,
    loading_stage character varying(100) COLLATE public.nocase,
    loading_curr_exec character varying(72) COLLATE public.nocase,
    loading_dock character varying(72) COLLATE public.nocase,
    loading_mhe character varying(120) COLLATE public.nocase,
    loading_employee character varying(80) COLLATE public.nocase,
    loading_packing_bay character varying(72) COLLATE public.nocase,
    loading_veh_type character varying(160) COLLATE public.nocase,
    loading_veh_no character varying(120) COLLATE public.nocase,
    laoding_equip_type character varying(160) COLLATE public.nocase,
    laoding_equip_no character varying(120) COLLATE public.nocase,
    loading_container_no character varying(72) COLLATE public.nocase,
    loading_person character varying(1020) COLLATE public.nocase,
    loading_exec_created_by character varying(120) COLLATE public.nocase,
    loading_exec_created_date timestamp without time zone,
    loading_exec_modified_by character varying(120) COLLATE public.nocase,
    loading_exec_modified_date timestamp without time zone,
    loading_exec_userdefined1 character varying(1020) COLLATE public.nocase,
    loading_exec_userdefined2 character varying(1020) COLLATE public.nocase,
    loading_exec_userdefined3 character varying(1020) COLLATE public.nocase,
    loading_manifest_no character varying(72) COLLATE public.nocase,
    loading_exec_startdate timestamp without time zone,
    loading_exec_enddate timestamp without time zone,
    loading_exec_seal_no character varying(1020) COLLATE public.nocase,
    loading_booking_req character varying(72) COLLATE public.nocase,
    loading_manf_flag character varying(32) COLLATE public.nocase,
    loading_gen_from character varying(32) COLLATE public.nocase,
    loading_rsn_code character varying(160) COLLATE public.nocase,
    loading_trip_planid character varying(72) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_fact_outbound_load ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_fact_outbound_load_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_fact_outbound_load
    ADD CONSTRAINT raw_fact_outbound_load_pkey PRIMARY KEY (raw_id);