CREATE TABLE raw.raw_spy_voucher_hdr (
    raw_id bigint NOT NULL,
    ou_id integer NOT NULL,
    paybatch_no character varying(72) NOT NULL COLLATE public.nocase,
    voucher_no character varying(72) NOT NULL COLLATE public.nocase,
    vtimestamp integer NOT NULL,
    voucher_amount numeric,
    vouch_amt_bef numeric,
    roundoff_amt numeric,
    exchange_rate numeric,
    par_exchange_rate numeric,
    pay_currency character varying(20) COLLATE public.nocase,
    payee character varying(64) COLLATE public.nocase,
    pay_mode character varying(100) COLLATE public.nocase,
    bank_cash_code character varying(128) COLLATE public.nocase,
    priority character varying(48) COLLATE public.nocase,
    dd_charges character varying(40) COLLATE public.nocase,
    status character varying(100) COLLATE public.nocase,
    supp_receipt_no character varying(72) COLLATE public.nocase,
    receipt_date timestamp without time zone,
    reason_code character varying(40) COLLATE public.nocase,
    hld_reason_code character varying(40) COLLATE public.nocase,
    hld_remarks character varying(400) COLLATE public.nocase,
    rev_remarks character varying(400) COLLATE public.nocase,
    rev_date timestamp without time zone,
    batch_id character varying(512) COLLATE public.nocase,
    supp_acct_in character varying(60) COLLATE public.nocase,
    supp_bank_ref character varying(128) COLLATE public.nocase,
    supp_acc_no character varying(128) COLLATE public.nocase,
    lsv_id character varying(72) COLLATE public.nocase,
    esr_line character varying(512) COLLATE public.nocase,
    doc_status character varying(48) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    line_no integer,
    tcal_status character varying(48) COLLATE public.nocase,
    tcal_exclusive_amt numeric,
    total_tcal_amount numeric,
    request_date timestamp without time zone,
    supplier_code character varying(64) COLLATE public.nocase,
    lcnumber character varying(120) COLLATE public.nocase,
    refid character varying(480) COLLATE public.nocase,
    tr_flag character varying(4) COLLATE public.nocase,
    tr_percent numeric,
    tr_amount numeric,
    tr_tenure integer,
    tr_duedate timestamp without time zone,
    receipt_no character varying(72) COLLATE public.nocase,
    tr_totalamount numeric,
    recon_reqflg character varying(48) COLLATE public.nocase,
    ict_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    be_amount numeric,
    be_amount_base numeric,
    be_totalamount numeric,
    be_percent numeric,
    be_currency character varying(20) COLLATE public.nocase,
    be_duedate timestamp without time zone,
    be_boeno character varying(128) COLLATE public.nocase,
    be_flag character varying(4) COLLATE public.nocase,
    be_issuedat character varying(400) COLLATE public.nocase,
    be_coveredamt numeric,
    be_redemptionamt numeric,
    be_status character varying(100) COLLATE public.nocase,
    lt_loanno character varying(1020) COLLATE public.nocase,
    lt_loanamount numeric,
    lt_loantype character varying(1020) COLLATE public.nocase,
    lt_loanp numeric,
    lt_currency character varying(20) COLLATE public.nocase,
    lt_anchordate timestamp without time zone,
    lt_flag character varying(4) COLLATE public.nocase,
    lt_loannumtype character varying(40) COLLATE public.nocase,
    lt_surnumtype character varying(40) COLLATE public.nocase,
    lt_loancat character varying(1020) COLLATE public.nocase,
    lt_loanpurp character varying(1020) COLLATE public.nocase,
    lt_maturitydate timestamp without time zone,
    lt_interestacc character varying(128) COLLATE public.nocase,
    lt_loanaccount character varying(128) COLLATE public.nocase,
    lt_lenderid character varying(80) COLLATE public.nocase,
    lt_interestid character varying(72) COLLATE public.nocase,
    lt_noofinstall character varying(72) COLLATE public.nocase,
    lt_costcenter character varying(40) COLLATE public.nocase,
    lt_analysiscode character varying(20) COLLATE public.nocase,
    lt_subanalysiscode character varying(20) COLLATE public.nocase,
    lt_loandesc character varying(1020) COLLATE public.nocase,
    lt_loanptype character varying(1020) COLLATE public.nocase,
    lt_projou integer,
    lt_projcode character varying(280) COLLATE public.nocase,
    mail_sent character varying(100) DEFAULT 'N'::character varying COLLATE public.nocase,
    loan_fa character varying(48) COLLATE public.nocase,
    gen_from character varying(100) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_spy_voucher_hdr ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_spy_voucher_hdr_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_spy_voucher_hdr
    ADD CONSTRAINT raw_spy_voucher_hdr_pkey PRIMARY KEY (raw_id);