CREATE TABLE raw.raw_wms_draft_bill_acc_tariff_dtl (
    raw_id bigint NOT NULL,
    wms_draft_bill_ou integer NOT NULL,
    wms_draft_bill_line_no integer NOT NULL,
    wms_draft_bill_location character varying(40) COLLATE public.nocase,
    wms_draft_bill_division character varying(40) COLLATE public.nocase,
    wms_draft_bill_tran_type character varying(100) NOT NULL COLLATE public.nocase,
    wms_draft_bill_ref_doc_no character varying(72) COLLATE public.nocase,
    wms_draft_bill_ref_doc_type character varying(32) COLLATE public.nocase,
    wms_draft_bill_trigger_doc_no character varying(72) COLLATE public.nocase,
    wms_draft_bill_trigger_doc_line_no character varying(512) COLLATE public.nocase,
    wms_draft_bill_trigger_doc_type character varying(32) COLLATE public.nocase,
    wms_draft_bill_trip_leg character varying(512) COLLATE public.nocase,
    wms_draft_bill_contract_id character varying(72) COLLATE public.nocase,
    wms_draft_bill_tariff_id character varying(72) COLLATE public.nocase,
    wms_draft_bill_acc_tariff_type character varying(32) COLLATE public.nocase,
    wms_draft_bill_billable_hours numeric,
    wms_draft_bill_value numeric,
    wms_draft_bill_su_count numeric,
    wms_draft_bill_consumables_count numeric,
    wms_draft_bill_created_by character varying(120) COLLATE public.nocase,
    wms_draft_bill_created_date timestamp without time zone,
    wms_draft_bill_trip_thu_line_no character varying(512) COLLATE public.nocase,
    wms_draft_bill_contract_amend_no integer,
    wms_draft_bill_thu_id character varying(160) COLLATE public.nocase,
    wms_draft_bill_equipment character varying(120) COLLATE public.nocase,
    wms_draft_bill_vehicle character varying(120) COLLATE public.nocase,
    wms_draft_bill_employee character varying(80) COLLATE public.nocase,
    wms_draft_bill_equipment_type character varying(160) COLLATE public.nocase,
    wms_draft_bill_vehicle_type character varying(160) COLLATE public.nocase,
    wms_draft_bill_su character varying(40) COLLATE public.nocase,
    wms_draft_bill_item_code character varying(128) COLLATE public.nocase,
    wms_draft_bill_item_qty numeric,
    wms_draft_bill_master_uom character varying(40) COLLATE public.nocase,
    wms_draft_bill_item_wt numeric,
    wms_draft_bill_item_wt_uom character varying(40) COLLATE public.nocase,
    wms_draft_bill_no_of_weeks integer,
    wms_draft_bill_weight numeric,
    wms_draft_bill_vendorid character varying(64) COLLATE public.nocase,
    wms_draft_bill_thu_space numeric,
    wms_draft_bill_pickup_wt numeric,
    wms_draft_bill_delivery_wt numeric,
    wms_draft_bill_transit_time numeric,
    wms_draft_bill_loading_time numeric,
    wms_draft_bill_unloading_time numeric,
    wms_draft_bill_est_return_time numeric,
    wms_draft_bill_no_of_empl numeric,
    wms_draft_bill_billable_intervals numeric,
    wms_draft_bill_billing_status character varying(32) COLLATE public.nocase,
    wms_draft_bill_customer_id character varying(72) COLLATE public.nocase,
    wms_draft_bill_booking_location character varying(40) COLLATE public.nocase,
    wms_draft_bill_db_no character varying(72) COLLATE public.nocase,
    wms_draft_bill_db_ln_no integer,
    wms_draft_bill_no_of_containers numeric,
    wms_draft_bill_supp_bat_no character varying(112) COLLATE public.nocase,
    wms_draft_bill_item_class character varying(1020) COLLATE public.nocase,
    wms_draft_bill_periodfrom timestamp without time zone,
    wms_draft_bill_periodto timestamp without time zone,
    wms_draft_bill_item_group character varying(160) COLLATE public.nocase,
    wms_draft_bill_ref_doc_line_no integer,
    wms_draft_bill_thu_qty numeric,
    wms_draft_bill_volume numeric,
    wms_draft_bill_distance numeric,
    wms_draft_bill_resourcetype character varying(1020) COLLATE public.nocase,
    wms_draft_bill_total_storage_cost numeric,
    wms_draft_bill_gross_vol_sales numeric,
    wms_draft_bill_calc_basis character varying(32) COLLATE public.nocase,
    wms_draft_bill_channel_type character varying(1020) COLLATE public.nocase,
    wms_draft_bill_in_ord_lineno integer,
    wms_draft_bill_in_ord_cust_id character varying(72) COLLATE public.nocase,
    wms_draft_bill_int_ord_cust_id character varying(72) COLLATE public.nocase,
    wms_draft_bill_exch_rate numeric,
    wms_draft_bill_margin numeric,
    wms_draft_bill_min_charge numeric,
    wms_draft_bill_max_charge numeric,
    wms_draft_bill_min_charge_added character varying(32) COLLATE public.nocase,
    wms_draft_bill_discount numeric,
    wms_draft_bill_cont_rate numeric,
    wms_draft_bill_value_currency character(20) COLLATE public.nocase,
    wms_draft_bill_alt_bill_currency character(20) COLLATE public.nocase,
    wms_draft_bill_seq_no integer,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_wms_draft_bill_acc_tariff_dtl ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_wms_draft_bill_acc_tariff_dtl_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_wms_draft_bill_acc_tariff_dtl
    ADD CONSTRAINT raw_wms_draft_bill_acc_tariff_dtl_pkey PRIMARY KEY (raw_id);