CREATE TABLE raw.raw_sin_item_dtl (
    raw_id bigint NOT NULL,
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_ou integer NOT NULL,
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    line_no integer NOT NULL,
    "timestamp" integer,
    po_amendment_no integer,
    visible_line_no integer,
    ref_doc_type character varying(40) COLLATE public.nocase,
    ref_doc_no character varying(72) COLLATE public.nocase,
    ref_doc_date timestamp without time zone,
    pors_type character varying(40) COLLATE public.nocase,
    po_no character varying(72) COLLATE public.nocase,
    po_ou integer,
    item_tcd_code character varying(128) COLLATE public.nocase,
    item_tcd_var character varying(128) COLLATE public.nocase,
    uom character varying(60) COLLATE public.nocase,
    rate_per numeric,
    invoice_qty numeric,
    invoice_rate numeric,
    invoice_amount numeric,
    proposed_qty numeric,
    proposed_rate numeric,
    proposed_amount numeric,
    tran_amount numeric,
    remarks character varying(4000) COLLATE public.nocase,
    cost_center character varying(40) COLLATE public.nocase,
    analysis_code character varying(20) COLLATE public.nocase,
    subanalysis_code character varying(20) COLLATE public.nocase,
    ref_doc_ou integer,
    unmatched_amount numeric,
    unmatched_perc integer,
    tax_amount numeric,
    disc_amount numeric,
    line_amount numeric,
    item_amount numeric,
    base_amount numeric,
    original_proposed_amt numeric,
    original_proposed_qty numeric,
    po_line_no integer,
    ref_doc_line_no integer,
    par_base_amount numeric,
    base_value numeric,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    item_desc character varying(3000) COLLATE public.nocase,
    matching_type character varying(8) COLLATE public.nocase,
    reconciled_qty numeric,
    orderno_instname character varying(160) COLLATE public.nocase,
    refdocno_instname character varying(160) COLLATE public.nocase,
    orderno_cur character varying(20) COLLATE public.nocase,
    po_date timestamp without time zone,
    po_categ character varying(60) COLLATE public.nocase,
    gr_opt character varying(48) COLLATE public.nocase,
    po_qty numeric,
    imports_flag character varying(48) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    tms_ou integer,
    tms_no character varying(72) COLLATE public.nocase,
    tms_type character varying(40) COLLATE public.nocase,
    retention_amt numeric,
    retentionperc numeric,
    ret_postol numeric,
    ret_negtol numeric,
    ipv_flag character varying(8) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    epv_flag character varying(8) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    retentionml numeric,
    holdml numeric,
    acusage character varying(80) COLLATE public.nocase,
    boe_no character varying(72) COLLATE public.nocase,
    boe_date timestamp without time zone,
    dest_comp character varying(40) COLLATE public.nocase,
    destou character varying(160) COLLATE public.nocase,
    destfb character varying(160) COLLATE public.nocase,
    destusageid character varying(160) COLLATE public.nocase,
    interfbjvno character varying(160) COLLATE public.nocase,
    dest_cost_center character varying(160) COLLATE public.nocase,
    dest_sub_analysis_code character varying(160) COLLATE public.nocase,
    dest_analysis_code character varying(160) COLLATE public.nocase,
    dest_account_code character varying(128) COLLATE public.nocase,
    itercomp_account_code character varying(128) COLLATE public.nocase,
    port_code character varying(1020) COLLATE public.nocase,
    own_tax_region character varying(40) COLLATE public.nocase,
    party_tax_region character varying(40) COLLATE public.nocase,
    decl_tax_region character varying(40) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_sin_item_dtl ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_sin_item_dtl_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_sin_item_dtl
    ADD CONSTRAINT raw_sin_item_dtl_pkey PRIMARY KEY (raw_id);