CREATE TABLE raw.raw_sur_receipt_hdr (
    raw_id bigint NOT NULL,
    ou_id integer NOT NULL,
    receipt_no character varying(72) NOT NULL COLLATE public.nocase,
    receipt_type character varying(16) NOT NULL COLLATE public.nocase,
    tran_type character varying(160) NOT NULL COLLATE public.nocase,
    stimestamp integer NOT NULL,
    receipt_date timestamp without time zone,
    receipt_category character varying(16) COLLATE public.nocase,
    fb_id character varying(80) COLLATE public.nocase,
    notype_no character varying(40) COLLATE public.nocase,
    remitter_name character varying(240) COLLATE public.nocase,
    receipt_method character varying(120) COLLATE public.nocase,
    receipt_mode character varying(16) COLLATE public.nocase,
    receipt_route character varying(16) COLLATE public.nocase,
    bank_cash_code character varying(128) COLLATE public.nocase,
    currency_code character varying(20) COLLATE public.nocase,
    exchange_rate numeric,
    receipt_amount numeric,
    origin_no character varying(72) COLLATE public.nocase,
    reason_code character varying(40) COLLATE public.nocase,
    remarks character varying(1020) COLLATE public.nocase,
    instr_no character varying(120) COLLATE public.nocase,
    micr_no character varying(120) COLLATE public.nocase,
    instr_amount numeric,
    instr_date timestamp without time zone,
    instr_status character varying(16) COLLATE public.nocase,
    bank_code character varying(128) COLLATE public.nocase,
    card_no character varying(120) COLLATE public.nocase,
    card_auth_no character varying(72) COLLATE public.nocase,
    issuer character varying(160) COLLATE public.nocase,
    valid_till_month character varying(40) COLLATE public.nocase,
    valid_till_year integer,
    address1 character varying(160) COLLATE public.nocase,
    address2 character varying(160) COLLATE public.nocase,
    address3 character varying(160) COLLATE public.nocase,
    city character varying(160) COLLATE public.nocase,
    state character varying(160) COLLATE public.nocase,
    country character varying(160) COLLATE public.nocase,
    zip_code character varying(80) COLLATE public.nocase,
    contact character varying(160) COLLATE public.nocase,
    url character varying(200) COLLATE public.nocase,
    mail_stop character varying(80) COLLATE public.nocase,
    pager_no character varying(80) COLLATE public.nocase,
    telex character varying(80) COLLATE public.nocase,
    email_id character varying(240) COLLATE public.nocase,
    phone_no character varying(80) COLLATE public.nocase,
    mobile_no character varying(80) COLLATE public.nocase,
    fax_no character varying(80) COLLATE public.nocase,
    receipt_status character varying(8) COLLATE public.nocase,
    rr_flag character varying(16) COLLATE public.nocase,
    batch_id character varying(512) COLLATE public.nocase,
    refdoc_no character varying(72) COLLATE public.nocase,
    refdoc_type character varying(160) COLLATE public.nocase,
    parbaseexrate numeric,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    doc_status character varying(48) COLLATE public.nocase,
    tcal_exclusive_amt numeric,
    total_tcal_amount numeric,
    tcal_status character varying(48) COLLATE public.nocase,
    source_comp character varying(48) COLLATE public.nocase,
    acct_type character varying(60) COLLATE public.nocase,
    insamt_btcal numeric,
    consistency_stamp character varying(48) COLLATE public.nocase,
    refdoc_ou integer,
    instr_type character varying(100) COLLATE public.nocase,
    pdr_status character varying(100) COLLATE public.nocase,
    pdr_rev_flag character varying(48) COLLATE public.nocase,
    workflow_status character varying(80) COLLATE public.nocase,
    auto_gen_flag character varying(48) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    afe_number character varying(72) COLLATE public.nocase,
    job_number character varying(72) COLLATE public.nocase,
    costcenter_hdr character varying(40) COLLATE public.nocase,
    bc_coveredamt numeric,
    bc_no character varying(128) COLLATE public.nocase,
    bc_redemptionamt numeric,
    report_flag character varying(40) COLLATE public.nocase,
    ifb_flag character varying(48) DEFAULT 'N'::character varying NOT NULL COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);