CREATE TABLE raw.raw_fact_inbound_asn (
    raw_id bigint NOT NULL,
    surrogatekey character varying(4000) COLLATE public.nocase,
    reference_no character varying(400) NOT NULL COLLATE public.nocase,
    tran_type character varying(500) COLLATE public.nocase,
    asn_ou integer NOT NULL,
    asn_location character varying(40) NOT NULL COLLATE public.nocase,
    asn_no character varying(72) NOT NULL COLLATE public.nocase,
    asn_prefdoc_type character varying(1020) COLLATE public.nocase,
    asn_prefdoc_no character varying(72) COLLATE public.nocase,
    asn_prefdoc_date timestamp without time zone,
    asn_date timestamp without time zone,
    asn_status character varying(1020) COLLATE public.nocase,
    asn_operation_status character varying(100) COLLATE public.nocase,
    asn_ib_order character varying(72) COLLATE public.nocase,
    asn_sup_asn_no character varying(72) COLLATE public.nocase,
    asn_sup_asn_date timestamp without time zone,
    asn_sent_by character varying(160) COLLATE public.nocase,
    asn_rem character varying(1020) COLLATE public.nocase,
    asn_shp_ref_typ character varying(160) COLLATE public.nocase,
    asn_shp_carrier character varying(160) COLLATE public.nocase,
    asn_shp_mode character varying(160) COLLATE public.nocase,
    asn_shp_eqp_no character varying(120) COLLATE public.nocase,
    asn_shp_rem character varying(1020) COLLATE public.nocase,
    asn_usrdf1 character varying(1020) COLLATE public.nocase,
    asn_usrdf2 character varying(1020) COLLATE public.nocase,
    asn_usrdf3 character varying(1020) COLLATE public.nocase,
    asn_createdby character varying(120) COLLATE public.nocase,
    asn_created_date timestamp without time zone,
    asn_modifiedby character varying(120) COLLATE public.nocase,
    asn_modified_date timestamp without time zone,
    asn_gate_no character varying(160) COLLATE public.nocase,
    asn_type character varying(32) COLLATE public.nocase,
    asn_lineno integer,
    asn_line_status character varying(100) COLLATE public.nocase,
    asn_itm_code character varying(128) COLLATE public.nocase,
    asn_qty numeric,
    asn_batch_no character varying(112) COLLATE public.nocase,
    po_lineno integer,
    gr_flag character(8) COLLATE public.nocase,
    asn_rec_qty numeric,
    asn_acc_qty numeric,
    asn_rej_qty numeric,
    asn_dtl_rem character varying(1020) COLLATE public.nocase,
    asn_customer_item_code character varying(128) COLLATE public.nocase,
    asn_order_uom character varying(40) COLLATE public.nocase,
    asn_master_uom_qty numeric,
    asn_cust_sl_no character varying(112) COLLATE public.nocase,
    asn_ref_doc_no1 character varying(72) COLLATE public.nocase,
    asn_outboundorder_no character varying(72) COLLATE public.nocase,
    asn_outboundorder_qty numeric,
    asn_outboundorder_lineno integer,
    asn_user_def_1 character varying(1020) COLLATE public.nocase,
    asn_user_def_2 numeric,
    asn_user_def_3 character varying(1020) COLLATE public.nocase,
    asn_hold integer,
    asn_stock_status character varying(160) COLLATE public.nocase,
    asn_item_attribute1 character varying(200) COLLATE public.nocase,
    asn_item_attribute2 character varying(200) COLLATE public.nocase,
    asn_item_attribute3 character varying(200) COLLATE public.nocase,
    asn_item_attribute4 character varying(200) COLLATE public.nocase,
    asn_item_attribute5 character varying(200) COLLATE public.nocase,
    asn_itm_cust character varying(72) COLLATE public.nocase,
    asn_cust_po_lineno integer,
    asn_lottable1 character varying(1024) COLLATE public.nocase,
    asn_lottable2 character varying(1024) COLLATE public.nocase,
    asn_lottable3 character varying(1024) COLLATE public.nocase,
    asn_lottable4 timestamp without time zone,
    asn_lottable5 timestamp without time zone,
    asn_lottable6 character varying(1024) COLLATE public.nocase,
    asn_lottable7 character varying(1024) COLLATE public.nocase,
    asn_lottable8 character varying(1024) COLLATE public.nocase,
    asn_lottable9 character varying(1024) COLLATE public.nocase,
    asn_lottable10 character varying(1024) COLLATE public.nocase,
    asn_shp_ref_no character varying(200) COLLATE public.nocase,
    asn_reason_code character varying(100) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);

ALTER TABLE raw.raw_fact_inbound_asn ALTER COLUMN raw_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME raw.raw_fact_inbound_asn_raw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY raw.raw_fact_inbound_asn
    ADD CONSTRAINT raw_fact_inbound_asn_pkey PRIMARY KEY (raw_id);