-- Table: raw.raw_tstl_tran_hdr

-- DROP TABLE IF EXISTS "raw".raw_tstl_tran_hdr;

CREATE TABLE IF NOT EXISTS "raw".raw_tstl_tran_hdr
(
    raw_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tran_no character varying(72) COLLATE public.nocase NOT NULL,
    tax_type character varying(100) COLLATE public.nocase NOT NULL,
    tran_type character varying(40) COLLATE public.nocase NOT NULL,
    tran_ou integer NOT NULL,
    tax_community character varying(100) COLLATE public.nocase NOT NULL,
    tran_date timestamp without time zone NOT NULL,
    applicable_flag character(4) COLLATE public.nocase NOT NULL,
    company_code character varying(40) COLLATE public.nocase NOT NULL,
    buid character varying(80) COLLATE public.nocase NOT NULL,
    fbid character varying(80) COLLATE public.nocase NOT NULL,
    tran_curr character(20) COLLATE public.nocase NOT NULL,
    incl_option character varying(32) COLLATE public.nocase NOT NULL,
    tax_excl_amt numeric NOT NULL,
    tax_incl_amt numeric NOT NULL,
    comp_tax_amt numeric NOT NULL,
    corr_tax_amt numeric NOT NULL,
    party_type character varying(32) COLLATE public.nocase NOT NULL,
    supp_cust_code character varying(72) COLLATE public.nocase,
    assessee_type character varying(160) COLLATE public.nocase,
    cap_deduct_charge character varying(32) COLLATE public.nocase NOT NULL,
    bas_exch_rate numeric NOT NULL,
    pbas_exch_rate numeric,
    comp_tax_amt_bascurr numeric NOT NULL,
    corr_tax_amt_bascurr numeric NOT NULL,
    nontax_tc_amt numeric NOT NULL,
    nontax_disc_amt numeric NOT NULL,
    component_name character varying(160) COLLATE public.nocase NOT NULL,
    original_tran_no character varying(72) COLLATE public.nocase,
    doc_status character varying(32) COLLATE public.nocase NOT NULL,
    tax_status character varying(32) COLLATE public.nocase NOT NULL,
    tax_adj_status character varying(32) COLLATE public.nocase,
    cert_recd_status character varying(32) COLLATE public.nocase NOT NULL,
    dr_cr_flag character varying(32) COLLATE public.nocase,
    usage_id character varying(128) COLLATE public.nocase,
    tax_excl_amt_bascurr numeric NOT NULL,
    tax_incl_amt_bascurr numeric NOT NULL,
    weightage_factor integer NOT NULL,
    tax_rate numeric NOT NULL,
    addnl_param1 integer,
    addnl_param2 numeric,
    addnl_param3 character varying(160) COLLATE public.nocase,
    addnl_param4 character varying(1020) COLLATE public.nocase,
    "timestamp" integer NOT NULL,
    created_at integer NOT NULL,
    created_by character varying(120) COLLATE public.nocase NOT NULL,
    created_date timestamp without time zone NOT NULL,
    modified_by character varying(120) COLLATE public.nocase NOT NULL,
    modified_date timestamp without time zone NOT NULL,
    post_date timestamp without time zone,
    rev_doc_date timestamp without time zone,
    rev_decl_year character varying(40) COLLATE public.nocase,
    revdecl_period character varying(60) COLLATE public.nocase,
    tranamt numeric,
    rev_tran_no character varying(72) COLLATE public.nocase,
    tradetype character varying(32) COLLATE public.nocase,
    taxon character varying(32) COLLATE public.nocase,
    rec_type character varying(4) COLLATE public.nocase,
    tax_amt_inv numeric,
    threshld_flag character varying(48) COLLATE public.nocase,
    cap_flag character varying(160) COLLATE public.nocase,
    ttrantaxable_amt numeric,
    ttrantax_amt numeric,
    tcalpdc_flag character varying(48) COLLATE public.nocase,
    propwht_amt numeric,
    appwht_amt numeric,
    supp_cust_name character varying(240) COLLATE public.nocase,
    ack_no character varying(1020) COLLATE public.nocase,
    supp_inv_no character varying(400) COLLATE public.nocase,
    supp_inv_date timestamp without time zone,
    supp_inv_amount numeric,
    recon_flag character varying(48) COLLATE pg_catalog."default",
    tax_adj_vouch_no character varying(72) COLLATE public.nocase,
    nature_of_reason character varying COLLATE public.nocase,
    gsp_ret_status character varying(100) COLLATE public.nocase,
    sec_heading character varying(100) COLLATE public.nocase,
    sub_heading character varying(100) COLLATE public.nocase,
    report_flag character varying(40) COLLATE public.nocase,
    gst3b_ack_no character varying(1000) COLLATE public.nocase,
    eway_bill_no character varying(1020) COLLATE public.nocase,
    valid_upto character varying(1020) COLLATE public.nocase,
    eway_bill_date character varying(1020) COLLATE public.nocase,
    original_supp_inv_no character varying(400) COLLATE public.nocase,
    upload_date timestamp without time zone,
    upload_dec_year character varying(1020) COLLATE public.nocase,
    upload_dec_period character varying(1020) COLLATE public.nocase,
    gstr2a_classification character varying(160) COLLATE public.nocase,
    aadhaar_no character varying(160) COLLATE public.nocase,
    pan_no character varying(160) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now(),
    CONSTRAINT raw_tstl_tran_hdr_pkey PRIMARY KEY (raw_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "raw".raw_tstl_tran_hdr
    OWNER to proconnect;