CREATE TABLE raw.raw_ci_doc_hdr (
    raw_id bigint NOT NULL,
    tran_ou integer NOT NULL,
    tran_type character varying(40) NOT NULL COLLATE public.nocase,
    tran_no character varying(72) NOT NULL COLLATE public.nocase,
    ctimestamp integer NOT NULL,
    lo_id character varying(80) COLLATE public.nocase,
    batch_id character varying(512) COLLATE public.nocase,
    fb_id character varying(80) COLLATE public.nocase,
    cust_code character varying(72) COLLATE public.nocase,
    tran_currency character varying(20) COLLATE public.nocase,
    tran_amount numeric,
    basecur_erate numeric,
    par_exchange_rate numeric,
    doc_status character varying(100) COLLATE public.nocase,
    instr_no character varying(120) COLLATE public.nocase,
    instr_date timestamp without time zone,
    instr_status character varying(100) COLLATE public.nocase,
    reason_code character varying(40) COLLATE public.nocase,
    ps_gen_flag character varying(4) COLLATE public.nocase,
    createdby character varying(120) COLLATE public.nocase,
    createddate timestamp without time zone,
    modifiedby character varying(120) COLLATE public.nocase,
    modifieddate timestamp without time zone,
    pay_term character varying(60) COLLATE public.nocase,
    due_amount numeric,
    received_amount numeric,
    adjusted_amount numeric,
    discount_amount numeric,
    discount_availed numeric,
    penalty_amount numeric,
    write_off_amount numeric,
    write_back_amount numeric,
    paid_amount numeric,
    reversed_docno character varying(72) COLLATE public.nocase,
    reversal_date timestamp without time zone,
    adjustment_status character varying(100) COLLATE public.nocase,
    provision_amount_cm numeric,
    tran_date timestamp without time zone,
    company_code character varying(40) COLLATE public.nocase,
    bank_code character varying(128) COLLATE public.nocase,
    payterm_version integer,
    transfer_status character varying(100) COLLATE public.nocase,
    vat_incorporate_flag character varying(48) COLLATE public.nocase,
    intbanktran_status character varying(100) COLLATE public.nocase,
    cust_companycode character varying(128) COLLATE public.nocase,
    cust_bank_ref character varying(128) COLLATE public.nocase,
    cust_bank_acct character varying(128) COLLATE public.nocase,
    ibe_flag character varying(48) COLLATE public.nocase,
    base_amount numeric,
    par_base_amount numeric,
    lcnumber character varying(120) COLLATE public.nocase,
    refid character varying(480) COLLATE public.nocase,
    lc_applicable character varying(48) COLLATE public.nocase,
    bookingno character varying(280) COLLATE public.nocase,
    masterbillofladingno character varying(280) COLLATE public.nocase,
    billofladingno character varying(280) COLLATE public.nocase,
    pdc_status character varying(100) COLLATE public.nocase,
    ims_flag character varying(48) COLLATE public.nocase,
    scheme_code character varying(160) COLLATE public.nocase,
    project_ou integer,
    project_code character varying(280) COLLATE public.nocase,
    pdc_flag character varying(48) COLLATE public.nocase,
    report_flag character varying(20) DEFAULT 'N'::character varying COLLATE public.nocase,
    realization_date timestamp without time zone,
    address_id character varying(24) COLLATE public.nocase,
    otc_flag character varying(48) COLLATE public.nocase,
    etlcreateddatetime timestamp(3) without time zone DEFAULT now()
);