CREATE TABLE click.d_customergrouphdr (
    cgh_key bigint NOT NULL,
    cgh_lo character varying(60) COLLATE public.nocase,
    cgh_bu character varying(60) COLLATE public.nocase,
    cgh_cust_group_code character varying(20) COLLATE public.nocase,
    cgh_control_group_flag character varying(20) COLLATE public.nocase,
    cgh_group_type_code character varying(20) COLLATE public.nocase,
    cgh_created_at integer,
    cgh_cust_group_desc character varying(100) COLLATE public.nocase,
    cgh_cust_group_desc_shd character varying(100) COLLATE public.nocase,
    cgh_reason_code character varying(20) COLLATE public.nocase,
    cgh_status character varying(20) COLLATE public.nocase,
    cgh_prev_status character varying(20) COLLATE public.nocase,
    cgh_created_by character varying(100) COLLATE public.nocase,
    cgh_created_date timestamp(3) without time zone,
    cgh_modified_by character varying(100) COLLATE public.nocase,
    cgh_modified_date timestamp(3) without time zone,
    cgh_timestamp_value integer,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);