CREATE TABLE click.d_wmsquickcodes (
    code_key bigint NOT NULL,
    code_ou integer,
    code_type character varying(510) COLLATE public.nocase,
    code character varying(80) COLLATE public.nocase,
    code_desc character varying(80) COLLATE public.nocase,
    code_default character varying(20) COLLATE public.nocase,
    seq_no integer,
    status character varying(20) COLLATE public.nocase,
    category character varying(20) COLLATE public.nocase,
    user_flag character varying(20) COLLATE public.nocase,
    code_timestamp integer,
    langid integer,
    created_date timestamp without time zone,
    created_by character varying(60) COLLATE public.nocase,
    modified_date timestamp without time zone,
    modified_by character varying(60) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone
);