CREATE TABLE click.f_grn (
    grn_key bigint NOT NULL,
    gr_pln_key bigint NOT NULL,
    gr_dtl_key bigint NOT NULL,
    gr_itm_dtl_key bigint NOT NULL,
    asn_key bigint NOT NULL,
    gr_loc_key bigint NOT NULL,
    gr_date_key bigint NOT NULL,
    gr_emp_hdr_key bigint NOT NULL,
    gr_itm_dtl_itm_hdr_key bigint NOT NULL,
    gr_itm_dtl_uom_key bigint NOT NULL,
    gr_itm_dtl_stg_mas_key bigint NOT NULL,
    gr_loc_code character varying(20) COLLATE public.nocase,
    gr_pln_no character varying(40) COLLATE public.nocase,
    gr_pln_ou integer,
    gr_pln_date timestamp without time zone,
    gr_pln_status character varying(20) COLLATE public.nocase,
    gr_po_no character varying(40) COLLATE public.nocase,
    gr_po_date timestamp without time zone,
    gr_asn_no character varying(40) COLLATE public.nocase,
    gr_asn_date timestamp without time zone,
    gr_employee character varying(80) COLLATE public.nocase,
    gr_staging_id character varying(40) COLLATE public.nocase,
    gr_ref_type character varying(510) COLLATE public.nocase,
    gr_item character varying(80) COLLATE public.nocase,
    gr_item_qty numeric(20,2),
    gr_lot_no character varying(60) COLLATE public.nocase,
    gr_acpt_qty numeric(20,2),
    gr_rej_qty numeric(20,2),
    gr_storage_unit character varying(20) COLLATE public.nocase,
    gr_mas_uom character varying(20) COLLATE public.nocase,
    gr_su_qty numeric(20,2),
    gr_itmexecution_date timestamp without time zone,
    gr_reasoncode character varying(80) COLLATE public.nocase,
    gr_cross_dock character varying(40) COLLATE public.nocase,
    gr_stock_status character varying(20) COLLATE public.nocase,
    gr_exec_no character varying(40) COLLATE public.nocase,
    gr_lineno integer,
    gr_no character varying(40) COLLATE public.nocase,
    gr_emp character varying(80) COLLATE public.nocase,
    gr_start_date timestamp without time zone,
    gr_end_date timestamp without time zone,
    gr_exec_status character varying(20) COLLATE public.nocase,
    gr_created_by character varying(60) COLLATE public.nocase,
    gr_exec_date timestamp without time zone,
    gr_gen_from character varying(16) COLLATE public.nocase,
    gr_created_date timestamp without time zone,
    gr_modified_date timestamp without time zone,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    activeindicator integer
);