CREATE TABLE click.f_inboundsladetail (
    sla_ib_key bigint NOT NULL,
    sla_ouid integer,
    sla_lockey bigint,
    sla_customerkey bigint,
    sla_datekey bigint,
    sla_customerid character varying(40) COLLATE public.nocase,
    sla_loccode character varying(20) COLLATE public.nocase,
    sla_dateactual date,
    sla_prefdocno character varying(80) COLLATE public.nocase,
    sla_supasnno character varying(80) COLLATE public.nocase,
    sla_ordtime time without time zone,
    sla_cutofftime time without time zone,
    sla_asntype character varying(20) COLLATE public.nocase,
    sla_preftype character varying(20) COLLATE public.nocase,
    sla_grnstatus character varying(20) COLLATE public.nocase,
    sla_pwaystatus character varying(20) COLLATE public.nocase,
    sla_equipmentflag integer,
    sla_grexecdate timestamp without time zone,
    sla_putawayexecdate timestamp without time zone,
    sla_grexpclstime timestamp without time zone,
    sla_grontime integer,
    sla_pwayexpclstime timestamp without time zone,
    sla_pwayontime integer,
    sla_category character varying(20) COLLATE public.nocase,
    sla_prexpclstime timestamp without time zone,
    sla_prontime integer,
    asn_timediff_inmin integer,
    grn_timediff_inmin integer,
    pway_timediff_inmin integer,
    sla_loadeddatetime timestamp without time zone DEFAULT CURRENT_DATE
);