-- Table: click.f_pickingdetail

-- DROP TABLE IF EXISTS click.f_pickingdetail;

CREATE TABLE IF NOT EXISTS click.f_pickingdetail
(
    pick_dtl_key bigint NOT NULL,
    pick_hdr_key bigint NOT NULL,
    pick_loc_key bigint NOT NULL,
    pick_loc_code character varying(20) COLLATE public.nocase,
    pick_exec_no character varying(40) COLLATE public.nocase,
    pick_exec_ou integer,
    pick_lineno integer,
    pick_wave_no character varying(40) COLLATE public.nocase,
    pick_so_no character varying(40) COLLATE public.nocase,
    pick_so_line_no integer,
    pick_sch_lineno integer,
    pick_so_qty numeric(20,2),
    pick_item_code character varying(80) COLLATE public.nocase,
    pick_item_batch_no character varying(60) COLLATE public.nocase,
    pick_item_sr_no character varying(60) COLLATE public.nocase,
    pick_uid_sr_no character varying(40) COLLATE public.nocase,
    pick_qty numeric(20,2),
    pick_zone character varying(20) COLLATE public.nocase,
    pick_bin character varying(40) COLLATE public.nocase,
    pick_bin_qty numeric(20,2),
    pick_plan_line_no integer,
    pick_reason_code character varying(80) COLLATE public.nocase,
    pick_allc_line_no integer,
    pick_lot_no character varying(60) COLLATE public.nocase,
    pick_su character varying(20) COLLATE public.nocase,
    pick_su_serial_no character varying(60) COLLATE public.nocase,
    pick_su_type character varying(20) COLLATE public.nocase,
    pick_thu_id character varying(80) COLLATE public.nocase,
    pick_allocated_qty numeric(20,2),
    pick_thu_serial_no character varying(60) COLLATE public.nocase,
    pick_urgent_cb character varying(510) COLLATE public.nocase,
    pick_exec_thu_wt numeric(20,2),
    pick_exec_thu_wt_uom character varying(20) COLLATE public.nocase,
    pick_length numeric(20,2),
    pick_breadth numeric(20,2),
    pick_height numeric(20,2),
    pick_uom character varying(20) COLLATE public.nocase,
    pick_volumeuom character varying(20) COLLATE public.nocase,
    pick_volume integer,
    pick_weightuom character varying(20) COLLATE public.nocase,
    pick_thuweight numeric(20,2),
    pick_customerserialno character varying(60) COLLATE public.nocase,
    pick_warrantyserialno character varying(60) COLLATE public.nocase,
    pick_counted_blnceqty numeric(20,2),
    pick_staging_id character varying(40) COLLATE public.nocase,
    pick_source_thu_id character varying(80) COLLATE public.nocase,
    pick_source_thu_serial_no character varying(80) COLLATE public.nocase,
    pick_cross_dk_staging_id character varying(40) COLLATE public.nocase,
    pick_stock_status character varying(80) COLLATE public.nocase,
    pick_outbound_no character varying(40) COLLATE public.nocase,
    pick_customer_code character varying(40) COLLATE public.nocase,
    pick_customer_item_code character varying(80) COLLATE public.nocase,
    gift_card_serial_no character varying(60) COLLATE public.nocase,
    warranty_serial_no character varying(60) COLLATE public.nocase,
    pick_ser_flag character varying(20) COLLATE public.nocase,
    pick_ser_date timestamp without time zone,
    pick_su2 character varying(20) COLLATE public.nocase,
    pick_uom1 character varying(20) COLLATE public.nocase,
    pick_su_serial_no2 character varying(60) COLLATE public.nocase,
    pick_system_date timestamp without time zone,
    pick_exec_ml_start_date timestamp without time zone,
    pick_exec_ml_end_date timestamp without time zone,
    pick_targetlocation character varying(510) COLLATE public.nocase,
    pick_item_attribute1 character varying(100) COLLATE public.nocase,
    etlactiveind integer,
    etljobname character varying(200) COLLATE public.nocase,
    envsourcecd character varying(50) COLLATE public.nocase,
    datasourcecd character varying(50) COLLATE public.nocase,
    etlcreatedatetime timestamp(3) without time zone,
    etlupdatedatetime timestamp(3) without time zone,
    pick_itm_key bigint,
    createddate timestamp(3) without time zone,
    updatedatetime timestamp(3) without time zone,
    CONSTRAINT f_pickingdetail_pkey PRIMARY KEY (pick_dtl_key),
    CONSTRAINT f_pickingdetail_ukey UNIQUE (pick_loc_code, pick_exec_no, pick_exec_ou, pick_lineno)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS click.f_pickingdetail
    OWNER to proconnect;