CREATE INDEX d_customer_idx ON click.d_customer USING btree (customer_id, customer_ou);
CREATE INDEX d_date_date_actual_idx ON click.d_date USING btree (dateactual);
CREATE INDEX d_excessitem_idx ON click.d_excessitem USING btree (ex_itm_ou, ex_itm_code, ex_itm_loc_code);
CREATE INDEX d_exchangerate_idx ON click.d_exchangerate USING btree (ou_id, exchrate_type, from_currency, to_currency, inverse_typeno, start_date);
CREATE INDEX d_itemheader_idx ON click.d_itemheader USING btree (itm_ou, itm_code);
CREATE INDEX d_itemheader_idx1 ON click.d_itemheader USING btree (itm_customer, itm_ou);
CREATE INDEX d_location_key_idx ON click.d_location USING btree (loc_code, loc_ou);
CREATE INDEX d_locationusermapping_idx ON click.d_locationusermapping USING btree (loc_ou, loc_code, loc_lineno);
CREATE INDEX d_tarifftransport_idx ON click.d_tarifftransport USING btree (tf_tp_id, tf_tp_ou);
CREATE INDEX d_thuitemmap_idx ON click.d_thuitemmap USING btree (thu_loc_code, thu_ou, thu_serial_no, thu_id, thu_item, thu_lot_no, thu_itm_serial_no);
CREATE INDEX d_thuitemmap_idx1 ON click.d_thuitemmap USING btree (COALESCE(etlupdatedatetime, etlcreatedatetime));
CREATE INDEX f_asn_date_idx ON click.f_asn USING btree (asn_created_date, asn_modified_date);
CREATE INDEX f_asn_inb_idx ON click.f_asn USING btree (asn_ib_order, asn_loc_key);
CREATE INDEX f_asn_join_idx ON click.f_asn USING btree (asn_no, asn_ou, asn_location, asn_gate_no, asn_lineno, asn_prefdoc_type, asn_type, asn_status, asn_sup_asn_no);
CREATE INDEX f_asn_key_idx ON click.f_asn USING btree (asn_hr_key, asn_dtl_key, gate_exec_dtl_key, asn_loc_key, asn_date_key, asn_cust_key, asn_dtl_itm_hdr_key, gate_exec_dtl_veh_key);
CREATE INDEX f_gr_po_idx ON click.f_grn USING btree (gr_po_no, gr_loc_key);
CREATE INDEX f_grn_date_idx ON click.f_grn USING btree (gr_created_date, gr_modified_date);
CREATE INDEX f_grn_join_idx ON click.f_grn USING btree (gr_loc_code, gr_pln_ou, gr_pln_no, gr_asn_no, gr_exec_no, gr_lineno, gr_no, gr_po_no);
CREATE INDEX f_grn_key_idx ON click.f_grn USING btree (gr_pln_key, gr_dtl_key, gr_emp_hdr_key, gr_itm_dtl_key, asn_key, gr_loc_key, gr_date_key, gr_itm_dtl_itm_hdr_key, gr_itm_dtl_uom_key, gr_itm_dtl_stg_mas_key);
CREATE INDEX f_inboundsladetail_ndx ON click.f_inboundsladetail USING btree (sla_ouid, sla_customerkey, sla_datekey, sla_lockey, sla_prefdocno);
CREATE INDEX f_outboundorderdetail_ndx ON click.f_outboundorderdetail USING btree (ord_ou, ord_lockey, ord_sono);
CREATE INDEX f_outboundorderdetail_ndx1 ON click.f_outboundorderdetail USING btree (ord_ou, ord_lockey, ord_sono);
CREATE INDEX f_outboundorderdetail_ndx2 ON click.f_outboundorderdetail USING btree (ord_ou, ord_lockey, ord_ordertype, ord_shipmenttype);
CREATE INDEX f_outboundpickpackdetail_ndx ON click.f_outboundpickpackdetail USING btree (pickpack_ordkey);
CREATE INDEX f_outboundpickpackdetail_ndx1 ON click.f_outboundpickpackdetail USING btree (pickpack_ou, pickpack_lockey, pickpack_sono);
CREATE INDEX f_outboundsladetail_ndx ON click.f_outboundsladetail USING btree (sla_ordkey);
CREATE INDEX f_outboundsladetail_ndx1 ON click.f_outboundsladetail USING btree (sla_ou, sla_loccode, sla_ordertype, sla_shipmenttype);
CREATE INDEX f_outboundsladetail_ndx2 ON click.f_outboundsladetail USING btree (sla_ou, sla_loccode, sla_sono);
CREATE INDEX f_putaway_date_idx ON click.f_putaway USING btree (created_date, modified_date);
CREATE INDEX f_putaway_join_idx ON click.f_putaway USING btree (pway_loc_code, pway_pln_no, pway_pln_ou, pway_lineno, pway_po_no, pway_item, pway_gr_no, pway_exec_no);
CREATE INDEX f_putaway_key_idx ON click.f_putaway USING btree (pway_pln_dtl_key, pway_pln_itm_dtl_key, pway_itm_dtl_key, pway_exe_dtl_key, grn_key, pway_pln_dtl_loc_key, pway_pln_dtl_date_key, pway_pln_dtl_stg_mas_key, pway_pln_dtl_emp_hdr_key, pway_pln_itm_dtl_itm_hdr_key, pway_pln_itm_dtl_zone_key);
CREATE INDEX f_putaway_po_idx ON click.f_putaway USING btree (pway_po_no, pway_pln_dtl_loc_key);
CREATE INDEX f_shipment_details_idx1 ON click.f_shipment_details USING btree (ouinstance, trip_plan_id, br_request_id);
CREATE INDEX f_shipment_details_idx2 ON click.f_shipment_details USING btree (ouinstance, trip_plan_id, dispatch_doc_no);
CREATE INDEX f_shipment_details_idx3 ON click.f_shipment_details USING btree (((trip_plan_createddate)::date));
CREATE INDEX f_shipment_details_idx4 ON click.f_shipment_details USING btree (leg_behaviour);
CREATE INDEX f_skumaster_idx ON click.f_skumaster USING btree (sku_ou, sku_code);
CREATE INDEX f_wmsinboundsummary_key_idx1 ON click.f_wmsinboundsummary USING btree (customer_key, datekey, loc_key, ou_id, item_group, item_class, asn_type, inb_type, grn_status, pway_status);
CREATE INDEX d_customer_idx ON dwh.d_customer USING btree (customer_ou, customer_id);
CREATE INDEX d_date_date_actual_idx ON dwh.d_date USING btree (datekey, dateactual);
CREATE INDEX d_excessitem_idx ON dwh.d_excessitem USING btree (ex_itm_ou, ex_itm_code, ex_itm_loc_code);
CREATE INDEX d_excessitem_idx1 ON dwh.d_excessitem USING btree (ex_itm_ou, ex_itm_code);
CREATE INDEX d_excessitemsuconvdetail_idx ON dwh.d_excessitemsuconvdetail USING btree (ex_itm_ou, ex_itm_code);
CREATE INDEX d_exchangerate_idx ON dwh.d_exchangerate USING btree (ou_id, exchrate_type, from_currency, to_currency, inverse_typeno, start_date);
CREATE INDEX d_hht_master_key_idx ON dwh.d_hht_master USING btree (hht_loc_key);
CREATE INDEX d_inboundtat_idx ON dwh.d_inboundtat USING btree (locationcode, ou, ordertype, servicetype);
CREATE INDEX d_itemheader_idx ON dwh.d_itemheader USING btree (itm_ou, itm_code);
CREATE INDEX d_itemheader_idx1 ON dwh.d_itemheader USING btree (itm_ou, itm_customer);
CREATE INDEX d_location_key_idx ON dwh.d_location USING btree (loc_code, loc_ou);
CREATE INDEX d_locationusermapping_idx ON dwh.d_locationusermapping USING btree (loc_ou, loc_code, loc_lineno);
CREATE INDEX d_outboundlocshiftdetail_key_idx ON dwh.d_outboundlocshiftdetail USING btree (obd_loc_sht_key);
CREATE INDEX d_outboundlocshiftdetail_key_idx3 ON dwh.d_outboundlocshiftdetail USING btree (ou, locationcode, ordertype, servicetype);
CREATE INDEX d_tarifftransport_idx ON dwh.d_tarifftransport USING btree (tf_tp_id, tf_tp_ou);
CREATE INDEX d_thu_idx ON dwh.d_thu USING btree (thu_ou, thu_id);
CREATE INDEX d_thuitemmap_idx ON dwh.d_thuitemmap USING btree (thu_loc_code, thu_ou, thu_serial_no, thu_id, thu_item, thu_lot_no, thu_itm_serial_no);
CREATE INDEX d_tmsdeliverytat_key_idx ON dwh.d_tmsdeliverytat USING btree (agent_code, shipfrom_pincode, shipto_pincode);
CREATE INDEX d_uom_idx ON dwh.d_uom USING btree (mas_ouinstance, mas_uomcode);
CREATE INDEX d_vehicle_idx ON dwh.d_vehicle USING btree (veh_ou, veh_id);
CREATE INDEX d_vehicle_key_ndx ON dwh.d_vehicle USING btree (veh_ou, veh_id);
CREATE INDEX d_vendor_idx_1 ON dwh.d_vendor USING btree (vendor_ou, vendor_id);
CREATE INDEX d_wmsoutboundtat_key_idx ON dwh.d_wmsoutboundtat USING btree (wms_loc_key);
CREATE INDEX d_wmsoutboundtat_key_idx1 ON dwh.d_wmsoutboundtat USING btree (ou, wms_loc_key, ordertype, servicetype);
CREATE INDEX d_wmsoutboundtat_key_idx2 ON dwh.d_wmsoutboundtat USING btree (ou, locationcode, ordertype, servicetype);
CREATE INDEX f_abbaccountbudgetdtl_key_idx ON dwh.f_abbaccountbudgetdtl USING btree (company_code, fb_id, fin_year_code, fin_period_code, account_code);
CREATE INDEX f_acapassethdr_key_idx ON dwh.f_acapassethdr USING btree (ou_id, cap_number, asset_number);
CREATE INDEX f_adepdeprratehdr_key_idx ON dwh.f_adepdeprratehdr USING btree (ou_id, asset_class, depr_rate_id);
CREATE INDEX f_adeppprocesshdr_key_idx ON dwh.f_adeppprocesshdr USING btree (ou_id, depr_proc_runno, depr_book);
CREATE INDEX f_ainqcwipaccountinginfo_key_idx ON dwh.f_ainqcwipaccountinginfo USING btree (tran_ou, component_id, company_code, tran_number, proposal_no);
CREATE INDEX f_allocitemdetailshistory_key_idx ON dwh.f_allocitemdetailshistory USING btree (allc_ouinstid, allc_doc_no, allc_doc_ou, allc_doc_line_no, allc_alloc_line_no);
CREATE INDEX f_allocitemdetailshistory_key_idx1 ON dwh.f_allocitemdetailshistory USING btree (allc_itm_hdr_key, allc_thu_key, allc_wh_key, allc_zone_key);
CREATE INDEX f_aplanacqproposalhdr_key_idx ON dwh.f_aplanacqproposalhdr USING btree (pln_pro_curr_key);
CREATE INDEX f_aplanacqproposalhdr_key_idx1 ON dwh.f_aplanacqproposalhdr USING btree (ou_id, fb_id, financial_year, asset_class_code, currency_code, proposal_number, addnl_entity);
CREATE INDEX f_asnadditionaldetail_key_idx ON dwh.f_asnadditionaldetail USING btree (asn_pop_loc_key);
CREATE INDEX f_asnadditionaldetail_key_idx1 ON dwh.f_asnadditionaldetail USING btree (asn_pop_asn_no, asn_pop_loc, asn_pop_ou, asn_pop_line_no);
CREATE INDEX f_asndetailhistory_key_idx ON dwh.f_asndetailhistory USING btree (asn_hdr_hst_key, asn_dtl_hst_loc_key, asn_dtl_hst_itm_hdr_key, asn_dtl_hst_thu_key);
CREATE INDEX f_asndetailhistory_key_idx1 ON dwh.f_asndetailhistory USING btree (asn_ou, asn_location, asn_no, asn_amendno, asn_lineno);
CREATE INDEX f_asndetailhistory_key_idx2 ON dwh.f_asndetailhistory USING btree (asn_ou, asn_location, asn_no, asn_amendno);
CREATE INDEX f_asndetails_join_idx ON dwh.f_asndetails USING btree (asn_ou, asn_location, asn_no, asn_lineno);
CREATE INDEX f_asndetails_key_idx ON dwh.f_asndetails USING btree (asn_hr_key, asn_dtl_loc_key, asn_dtl_itm_hdr_key, asn_dtl_thu_key, asn_dtl_uom_key);
CREATE INDEX f_asnheader_key_idx ON dwh.f_asnheader USING btree (asn_loc_key, asn_date_key, asn_cust_key, asn_supp_key);
CREATE INDEX f_asnheader_key_idx1 ON dwh.f_asnheader USING btree (asn_ou, asn_location, asn_no, asn_gate_no);
CREATE INDEX f_asnheader_key_idx2 ON dwh.f_asnheader USING btree (asn_location, asn_ou, asn_no);
CREATE INDEX f_asnheaderhistory_key_idx ON dwh.f_asnheaderhistory USING btree (asn_hdr_hst_loc_key, asn_hdr_hst_datekey, asn_hdr_hst_customer_key);
CREATE INDEX f_asnheaderhistory_key_idx1 ON dwh.f_asnheaderhistory USING btree (asn_ou, asn_location, asn_no, asn_amendno);
CREATE INDEX f_bindetails_key_idx ON dwh.f_bindetails USING btree (bin_loc_key, bin_zone_key);
CREATE INDEX f_bindetails_key_idx1 ON dwh.f_bindetails USING btree (bin_ou, bin_code, bin_loc_code, bin_zone, bin_type);
CREATE INDEX f_bindetails_key_idx2 ON dwh.f_bindetails USING btree (bin_typ_key);
CREATE INDEX f_binexecdetail_key_idx ON dwh.f_binexecdetail USING btree (bin_exec_hdr_key, bin_exec_loc_key, bin_exec_itm_hdr_key, bin_exec_thu_key);
CREATE INDEX f_binexechdr_key_idx ON dwh.f_binexechdr USING btree (bin_loc_key, bin_emp_hdr_key, bin_date_key);
CREATE INDEX f_binexecitemdetail_key_idx ON dwh.f_binexecitemdetail USING btree (bin_hdr_key, bin_loc_key, bin_itm_hdr_key, bin_thu_key);
CREATE INDEX f_binplandetails_key_idx ON dwh.f_binplandetails USING btree (bin_loc_dl_key);
CREATE INDEX f_binplandetails_key_idx1 ON dwh.f_binplandetails USING btree (bin_loc_code, bin_pln_no, bin_pln_lineno, bin_pln_ou);
CREATE INDEX f_binplanheader_key_idx ON dwh.f_binplanheader USING btree (bin_loc_key);
CREATE INDEX f_binplanheader_key_idx1 ON dwh.f_binplanheader USING btree (bin_loc_code, bin_pln_no, bin_pln_ou);
CREATE INDEX f_bookingrequest_key_idx ON dwh.f_bookingrequest USING btree (br_curr_key, br_rou_key, br_loc_key, br_customer_key);
CREATE INDEX f_bookingrequest_key_idx1 ON dwh.f_bookingrequest USING btree (br_ouinstance, br_request_id);
CREATE INDEX f_bookingrequestreasonhistory_key_idx ON dwh.f_bookingrequestreasonhistory USING btree (br_ouinstance, br_request_id, amend_no);
CREATE INDEX f_bookingrequestreasonhistory_key_idx1 ON dwh.f_bookingrequestreasonhistory USING btree (br_hdr_key);
CREATE INDEX f_brconsignmentconsigneedetail_key_idx ON dwh.f_brconsignmentconsigneedetail USING btree (br_key, brccd_consignee_hdr_key);
CREATE INDEX f_brconsignmentconsigneedetail_key_idx1 ON dwh.f_brconsignmentconsigneedetail USING btree (ccd_ouinstance, ccd_br_id);
CREATE INDEX f_brconsignmentdetail_key_idx ON dwh.f_brconsignmentdetail USING btree (br_key, brcd_thu_key, brcd_curr_key);
CREATE INDEX f_brconsignmentdetail_key_idx1 ON dwh.f_brconsignmentdetail USING btree (cd_ouinstance, cd_br_id, cd_line_no);
CREATE INDEX f_brconsignmentskudetail_key_idx ON dwh.f_brconsignmentskudetail USING btree (br_key);
CREATE INDEX f_brconsignmentskudetail_key_idx1 ON dwh.f_brconsignmentskudetail USING btree (brcsd_ou, brcsd_br_id, brcsd_thu_line_no, brcsd_sku_line_no);
CREATE INDEX f_brconsignmentthuserialdetail_key_idx ON dwh.f_brconsignmentthuserialdetail USING btree (ctsd_ouinstance, ctsd_br_id, ctsd_thu_line_no, ctsd_thu_serial_line_no);
CREATE INDEX f_brconsignmentthuserialdetail_key_idx1 ON dwh.f_brconsignmentthuserialdetail USING btree (ctsd_br_key);
CREATE INDEX f_brewaybilldetail_key_idx ON dwh.f_brewaybilldetail USING btree (br_key);
CREATE INDEX f_brewaybilldetail_key_idx1 ON dwh.f_brewaybilldetail USING btree (ewbd_br_no, ewbd_ouinstance);
CREATE INDEX f_brplanningprofiledetail_key_idx ON dwh.f_brplanningprofiledetail USING btree (brppd_ouinstance, brppd_profile_id, brppd_br_id);
CREATE INDEX f_brplanningprofiledetail_key_idx1 ON dwh.f_brplanningprofiledetail USING btree (brppd_cust_key, brppd_loc_key);
CREATE INDEX f_brshipmentdetail_key_idx ON dwh.f_brshipmentdetail USING btree (brsd_ouinstance, brsd_br_id);
CREATE INDEX f_brshipmentdetail_key_idx1 ON dwh.f_brshipmentdetail USING btree (brsd_br_key);
CREATE INDEX f_brthucontractdetail_key_idx ON dwh.f_brthucontractdetail USING btree (br_key);
CREATE INDEX f_brthucontractdetail_key_idx1 ON dwh.f_brthucontractdetail USING btree (brctd_ou, brctd_br_id, brctd_tariff_id, brctd_thu_line_no, brctd_staging_ref_document);
CREATE INDEX f_cdcnarpostingsdtl_key_idx ON dwh.f_cdcnarpostingsdtl USING btree (tran_type, tran_ou, tran_no, posting_line_no);
CREATE INDEX f_cdcnarpostingsdtl_key_idx1 ON dwh.f_cdcnarpostingsdtl USING btree (cdcnarpostingsdtl_customer_key);
CREATE INDEX f_cdiarpostingsdtl_date_idx ON dwh.f_cdiarpostingsdtl USING btree (createddate, modifieddate, entry_date, auth_date, posting_date, tran_date);
CREATE INDEX f_cdiarpostingsdtl_key_idx ON dwh.f_cdiarpostingsdtl USING btree (company_key, fb_key, curr_key, itm_hdr_key, uom_key, customer_key);
CREATE INDEX f_cdiinvoicehdr_key_idx ON dwh.f_cdiinvoicehdr USING btree (fb_key, curr_key);
CREATE INDEX f_cdiitemdtl_key_idx ON dwh.f_cdiitemdtl USING btree (uom_key);
CREATE INDEX f_cidochdr_key_idx ON dwh.f_cidochdr USING btree (customer_key, curr_key, company_key, fb_key);
CREATE INDEX f_contractdetail_key_idx ON dwh.f_contractdetail USING btree (cont_id, cont_lineno, cont_ou, cont_tariff_id);
CREATE INDEX f_contractdetail_key_idx1 ON dwh.f_contractdetail USING btree (cont_hdr_key);
CREATE INDEX f_contractdetailhistory_key_idx ON dwh.f_contractdetailhistory USING btree (cont_id, cont_lineno, cont_ou, cont_amendno);
CREATE INDEX f_contractdetailhistory_key_idx1 ON dwh.f_contractdetailhistory USING btree (cont_hdr_hst_key);
CREATE INDEX f_contractdetailhistory_key_idx2 ON dwh.f_contractdetailhistory USING btree (cont_id, cont_ou, cont_amendno);
CREATE INDEX f_contractheader_key_idx ON dwh.f_contractheader USING btree (cont_id, cont_ou);
CREATE INDEX f_contractheader_ndx ON dwh.f_contractheader USING btree (cont_ou, cont_id, cont_vendor_id, cont_type);
CREATE INDEX f_contractheaderhistory_key_idx ON dwh.f_contractheaderhistory USING btree (cont_id, cont_ou, cont_amendno);
CREATE INDEX f_contractheaderhistory_key_idx1 ON dwh.f_contractheaderhistory USING btree (cont_hdr_hst_customer_key, cont_hdr_hst_datekey, cont_hdr_hst_loc_key, cont_hdr_hst_vendor_key, cont_hdr_hst_curr_key);
CREATE INDEX f_contractrevleakdetail_key_idx ON dwh.f_contractrevleakdetail USING btree (cont_rev_lkge_ou, cont_rev_lkge_line_no);
CREATE INDEX f_contracttransferinvoicedetail_key_idx ON dwh.f_contracttransferinvoicedetail USING btree (cont_transfer_inv_no, cont_transfer_lineno, cont_transfer_inv_ou);
CREATE INDEX f_contracttransferinvoicedetail_key_idx1 ON dwh.f_contracttransferinvoicedetail USING btree (cont_inv_hdr_key);
CREATE INDEX f_contracttransferinvoiceheader_key_idx ON dwh.f_contracttransferinvoiceheader USING btree (cont_transfer_inv_no, cont_transfer_inv_ou);
CREATE INDEX f_deliverydelayreason_idx ON dwh.f_deliverydelayreason USING btree (invoiceno, tranou, locationcode);
CREATE INDEX f_deliverydelayreason_idx1 ON dwh.f_deliverydelayreason USING btree (tranou, type, activity, locationcode, invoiceno, invoiceholdtype, invoicedate, guid, remarks);
CREATE INDEX f_deliverydelayreason_idx2 ON dwh.f_deliverydelayreason USING btree (tranou, type, activity, locationcode, invoiceno, invoiceholdtype, invoicedate, guid, remarks);
CREATE INDEX f_deliverydelayreason_idx3 ON dwh.f_deliverydelayreason USING btree (tranou, locationcode, invoiceno);
CREATE INDEX f_dispatchconsdetail_key_idx ON dwh.f_dispatchconsdetail USING btree (disp_con_loc_key, disp_con_customer_key);
CREATE INDEX f_dispatchdetail_key_idx ON dwh.f_dispatchdetail USING btree (dispatch_hdr_key, dispatch_dtl_loc_key, dispatch_dtl_thu_key, dispatch_dtl_shp_pt_key, dispatch_dtl_customer_key);
CREATE INDEX f_dispatchdocheader_key_idx ON dwh.f_dispatchdocheader USING btree (ddh_customer_key, ddh_consignee_hdr_key, ddh_curr_key, ddh_loc_key);
CREATE INDEX f_dispatchdocheader_key_idx1 ON dwh.f_dispatchdocheader USING btree (ddh_ouinstance, ddh_dispatch_doc_no);
CREATE INDEX f_dispatchdocheader_key_ndx ON dwh.f_dispatchdocheader USING btree (ddh_ouinstance, ddh_reference_doc_no);
CREATE INDEX f_dispatchdocsignature_key_idx ON dwh.f_dispatchdocsignature USING btree (ddh_key);
CREATE INDEX f_dispatchdocsignature_key_idx1 ON dwh.f_dispatchdocsignature USING btree (dds_ouinstance, dds_trip_id, dds_seqno, dds_dispatch_doc_no);
CREATE INDEX f_dispatchdocthuchilddetail_key_idx ON dwh.f_dispatchdocthuchilddetail USING btree (ddtd_key);
CREATE INDEX f_dispatchdocthuchilddetail_key_idx1 ON dwh.f_dispatchdocthuchilddetail USING btree (ddtcd_ouinstance, ddtcd_dispatch_doc_no, ddtcd_thu_line_no, ddtcd_thu_child_line_no);
CREATE INDEX f_dispatchdocthudetail_key_idx ON dwh.f_dispatchdocthudetail USING btree (ddh_key, ddh_thu_key);
CREATE INDEX f_dispatchdocthudetail_key_idx1 ON dwh.f_dispatchdocthudetail USING btree (ddtd_ouinstance, ddtd_dispatch_doc_no, ddtd_thu_line_no);
CREATE INDEX f_dispatchdocthuserialdetail_key_idx ON dwh.f_dispatchdocthuserialdetail USING btree (ddtd_key);
CREATE INDEX f_dispatchdocthuserialdetail_key_idx1 ON dwh.f_dispatchdocthuserialdetail USING btree (ddtsd_ouinstance, ddtsd_dispatch_doc_no, ddtsd_thu_line_no, ddtsd_thu_serial_line_no);
CREATE INDEX f_dispatchdocthuskudetail_key_idx ON dwh.f_dispatchdocthuskudetail USING btree (ddtd_key);
CREATE INDEX f_dispatchdocthuskudetail_key_idx1 ON dwh.f_dispatchdocthuskudetail USING btree (ddtsd_ou, ddtsd_dispatch_doc_no, ddtsd_thu_line_no);
CREATE INDEX f_dispatchheader_key_idx ON dwh.f_dispatchheader USING btree (dispatch_hdr_loc_key, dispatch_hdr_veh_key);
CREATE INDEX f_dispatchloaddetail_key_idx ON dwh.f_dispatchloaddetail USING btree (disp_load_loc_key, disp_load_customer_key);
CREATE INDEX f_divisionareadetail_key_idx ON dwh.f_divisionareadetail USING btree (div_key);
CREATE INDEX f_draftbilldetail_key_idx ON dwh.f_draftbilldetail USING btree (draft_bill_hdr_key);
CREATE INDEX f_draftbilldetail_key_idx1 ON dwh.f_draftbilldetail USING btree (draft_bill_no, draft_bill_ou, draft_bill_lineno);
CREATE INDEX f_draftbilldetail_ndx ON dwh.f_draftbilldetail USING btree (draft_bill_triggerring_no, draft_bill_ref_doc_no, draft_bill_ou);
CREATE INDEX f_draftbillexecdetail_key_idx ON dwh.f_draftbillexecdetail USING btree (draft_bill_itm_hdr_key, draft_bill_stg_mas_key, draft_bill_thu_key, draft_bill_customer_key, draft_bill_loc_key);
CREATE INDEX f_draftbillexecdetail_key_idx1 ON dwh.f_draftbillexecdetail USING btree (exec_loc_code, exec_ou, exec_no, exec_stage, exec_line_no);
CREATE INDEX f_draftbillheader_key_idx ON dwh.f_draftbillheader USING btree (draft_loc_key, draft_cust_key, draft_curr_key);
CREATE INDEX f_draftbillheader_key_idx1 ON dwh.f_draftbillheader USING btree (draft_bill_no, draft_bill_ou);
CREATE INDEX f_draftbillheader_key_idx2 ON dwh.f_draftbillheader USING btree (draft_bill_ou, draft_bill_contract_id, draft_bill_supplier);
CREATE INDEX f_draftbillsuppliercontractdetail_key_idx ON dwh.f_draftbillsuppliercontractdetail USING btree (draft_bill_ou, draft_bill_location, draft_bill_division, draft_bill_tran_type, draft_bill_ref_doc_no, draft_bill_ref_doc_type, draft_bill_vendor_id, draft_bill_resource_type);
CREATE INDEX f_draftbilltariffdetail_key_idx ON dwh.f_draftbilltariffdetail USING btree (draft_bill_ou, draft_bill_line_no, draft_bill_tran_type);
CREATE INDEX f_eamamchdr_key_idx ON dwh.f_eamamchdr USING btree (amc_vendor_key, amc_curr_key);
CREATE INDEX f_execthudetail_key_idx ON dwh.f_execthudetail USING btree (plepd_trip_exe_pln_dtl_key);
CREATE INDEX f_execthudetail_key_idx1 ON dwh.f_execthudetail USING btree (pletd_ouinstance, pletd_execution_plan_id, pletd_line_no, pletd_dispatch_docno, pletd_thu_line_no);
CREATE INDEX f_execthuserialdetail_key_idx ON dwh.f_execthuserialdetail USING btree (plepd_trip_exe_pln_dtl_key);
CREATE INDEX f_execthuserialdetail_key_idx1 ON dwh.f_execthuserialdetail USING btree (pletsd_ouinstance, pletsd_execution_plan_id, pletsd_line_no, pletsd_thu_line_no, pletsd_serial_line_no);
CREATE INDEX f_fbpaccountbalance_key_idx ON dwh.f_fbpaccountbalance USING btree (fbp_act_curr_key);
CREATE INDEX f_fbppostedtrndtl_key_idx ON dwh.f_fbppostedtrndtl USING btree (fbp_trn_curr_key, fbp_trn_company_key);
CREATE INDEX f_fbpvoucherdtl_key_idx ON dwh.f_fbpvoucherdtl USING btree (fbp_company_key);
CREATE INDEX f_fbpvoucherhdr_key_idx ON dwh.f_fbpvoucherhdr USING btree (fbp_company_key);
CREATE INDEX f_gateexecdetail_key_idx ON dwh.f_gateexecdetail USING btree (gate_exec_dtl_emp_hdr_key, gate_exec_dtl_eqp_key, gate_exec_dtl_veh_key, gate_exec_dtl_loc_key);
CREATE INDEX f_gateexecdetail_key_idx1 ON dwh.f_gateexecdetail USING btree (gate_loc_code, gate_exec_no, gate_exec_ou);
CREATE INDEX f_gateplandetail_key_idx ON dwh.f_gateplandetail USING btree (gate_pln_dtl_eqp_key, gate_pln_dtl_veh_key, gate_pln_dtl_loc_key);
CREATE INDEX f_gateplandetail_key_idx1 ON dwh.f_gateplandetail USING btree (gate_loc_code, gate_pln_no, gate_pln_ou);
CREATE INDEX f_goodsempequipmap_key_idx ON dwh.f_goodsempequipmap USING btree (gr_loc_key);
CREATE INDEX f_goodsempequipmap_key_idx1 ON dwh.f_goodsempequipmap USING btree (gr_loc_cod, gr_ou, gr_lineno);
CREATE INDEX f_goodsissuedetails_key_idx ON dwh.f_goodsissuedetails USING btree (gi_loc_key);
CREATE INDEX f_goodsissuedetails_key_idx1 ON dwh.f_goodsissuedetails USING btree (gi_no, gi_ou, gi_loc_code, gi_outbound_ord_no, gi_line_no);
CREATE INDEX f_goodsreceiptdetails_join_idx ON dwh.f_goodsreceiptdetails USING btree (gr_loc_code, gr_pln_no, gr_pln_ou, gr_exec_no, gr_exec_ou, gr_po_no);
CREATE INDEX f_goodsreceiptdetails_key_idx ON dwh.f_goodsreceiptdetails USING btree (gr_loc_key, gr_emp_hdr_key, gr_date_key, gr_stg_mas_key);
CREATE INDEX f_goodsreceiptitemdetails_join_idx ON dwh.f_goodsreceiptitemdetails USING btree (gr_exec_no, gr_lineno, gr_loc_code, gr_po_no, gr_item, gr_lineno, gr_exec_ou, gr_exe_asn_line_no);
CREATE INDEX f_goodsreceiptitemdetails_key_idx ON dwh.f_goodsreceiptitemdetails USING btree (gr_dtl_key, gr_itm_dtl_loc_key, gr_itm_dtl_itm_hdr_key, gr_itm_dtl_uom_key, gr_itm_dtl_thu_key, gr_itm_dtl_stg_mas_key);
CREATE INDEX f_grheader_key_idx ON dwh.f_grheader USING btree (gr_date_key, gr_emp_hdr_key, gr_vendor_key, gr_curr_key);
CREATE INDEX f_gritemtrackingdetail_key_idx ON dwh.f_gritemtrackingdetail USING btree (gr_itm_tk_dtl_loc_key, gr_itm_tk_dtl_itm_hdr_key, gr_itm_tk_dtl_customer_key);
CREATE INDEX f_grplandetail_key_idx ON dwh.f_grplandetail USING btree (gr_loc_key, gr_date_key);
CREATE INDEX f_grplandetail_key_idx1 ON dwh.f_grplandetail USING btree (gr_loc_code, gr_pln_no, gr_pln_ou, gr_po_no, gr_asn_no);
CREATE INDEX f_grserialinfo_key_idx ON dwh.f_grserialinfo USING btree (gr_loc_key);
CREATE INDEX f_grserialinfo_key_idx1 ON dwh.f_grserialinfo USING btree (gr_loc_code, gr_exec_no, gr_exec_ou, gr_lineno, gr_serial_no);
CREATE INDEX f_grthudetail_key_idx ON dwh.f_grthudetail USING btree (gr_loc_key);
CREATE INDEX f_grthudetail_key_idx1 ON dwh.f_grthudetail USING btree (gr_loc_code, gr_pln_no, gr_pln_ou, gr_lineno);
CREATE INDEX f_grthuheader_key_idx ON dwh.f_grthuheader USING btree (gr_loc_key, gr_thu_key);
CREATE INDEX f_grthuheader_key_idx1 ON dwh.f_grthuheader USING btree (gr_loc_code, gr_exec_no, gr_exec_ou, gr_thu_id, gr_thu_sno, gr_thu_su, gr_thu_uid_ser_no);
CREATE INDEX f_grthulotdetail_key_idx ON dwh.f_grthulotdetail USING btree (gr_lot_loc_key, gr_lot_thu_key, gr_lot_thu_item_key);
CREATE INDEX f_grthulotdetail_key_idx1 ON dwh.f_grthulotdetail USING btree (gr_loc_code, gr_exec_no, gr_exec_ou, gr_thu_id, gr_lot_thu_sno, gr_line_no, gr_thu_uid_sr_no, gr_thu_lot_su);
CREATE INDEX f_inboundamendheader_key_idx ON dwh.f_inboundamendheader USING btree (inb_loc_key);
CREATE INDEX f_inboundamendheader_key_idx1 ON dwh.f_inboundamendheader USING btree (inb_loc_code, inb_orderno, inb_ou, inb_amendno);
CREATE INDEX f_inbounddetail_key_idx ON dwh.f_inbounddetail USING btree (inb_itm_dtl_loc_key, inb_itm_dtl_itm_hdr_key);
CREATE INDEX f_inbounddetail_key_idx1 ON dwh.f_inbounddetail USING btree (inb_loc_code, inb_orderno, inb_lineno, inb_ou);
CREATE INDEX f_inboundheader_key_idx ON dwh.f_inboundheader USING btree (inb_loc_key);
CREATE INDEX f_inboundheader_key_idx1 ON dwh.f_inboundheader USING btree (inb_loc_code, inb_orderno, inb_ou);
CREATE INDEX f_inbounditemamenddetail_key_idx ON dwh.f_inbounditemamenddetail USING btree (inb_itm_key, inb_loc_key);
CREATE INDEX f_inbounditemamenddetail_key_idx1 ON dwh.f_inbounditemamenddetail USING btree (inb_loc_code, inb_orderno, inb_lineno, inb_ou, inb_amendno);
CREATE INDEX f_inboundorderbindetail_key_idx ON dwh.f_inboundorderbindetail USING btree (inb_loc_key);
CREATE INDEX f_inboundorderbindetail_key_idx1 ON dwh.f_inboundorderbindetail USING btree (in_ord_location, in_ord_no, in_ord_lineno, in_ord_ou);
CREATE INDEX f_inboundplantracking_key_idx ON dwh.f_inboundplantracking USING btree (pln_date_key);
CREATE INDEX f_inboundplantracking_key_idx1 ON dwh.f_inboundplantracking USING btree (pln_lineno, pln_ou);
CREATE INDEX f_inboundscheduleitemamenddetail_key_idx ON dwh.f_inboundscheduleitemamenddetail USING btree (inb_itm_key, inb_loc_key);
CREATE INDEX f_inboundscheduleitemdetail_key_idx ON dwh.f_inboundscheduleitemdetail USING btree (inb_itm_key, inb_loc_key);
CREATE INDEX f_inboundscheduleitemdetail_key_idx1 ON dwh.f_inboundscheduleitemdetail USING btree (inb_loc_code, inb_orderno, inb_lineno, inb_ou);
CREATE INDEX f_internalorderheader_key_idx ON dwh.f_internalorderheader USING btree (in_ord_hdr_customer_key, in_ord_hdr_loc_key);
CREATE INDEX f_itemallocdetail_key_idx ON dwh.f_itemallocdetail USING btree (allc_itm_hdr_key, allc_wh_key, allc_zone_key, allc_thu_key, allc_uom_key, allc_stg_mas_key);
CREATE INDEX f_itemallocdetail_key_idx1 ON dwh.f_itemallocdetail USING btree (allc_doc_no, allc_doc_line_no, allc_alloc_line_no, allc_doc_ou);
CREATE INDEX f_loadingdetail_key_idx ON dwh.f_loadingdetail USING btree (loading_hdr_key, loading_dtl_loc_key, loading_dtl_stg_mas_key, loading_dtl_thu_key, loading_dtl_shp_pt_key);
CREATE INDEX f_loadingheader_key_idx ON dwh.f_loadingheader USING btree (loading_hdr_emp_hdr_key, loading_hdr_eqp_key, loading_hdr_veh_key, loading_hdr_loc_key);
CREATE INDEX f_locationareadetail_key_idx ON dwh.f_locationareadetail USING btree (loc_pop_loc_key);
CREATE INDEX f_lotmasterdetail_key_idx ON dwh.f_lotmasterdetail USING btree (lot_mst_dtl_itm_hdr_key, lot_mst_dtl_wh_key);
CREATE INDEX f_lotmasterdetail_key_idx1 ON dwh.f_lotmasterdetail USING btree (lm_lotno_ou, lm_wh_code, lm_item_code, lm_lot_no, lm_serial_no, lm_trans_no);
CREATE INDEX f_lottrackingdetail_key_idx ON dwh.f_lottrackingdetail USING btree (stk_loc_key, stk_item_key, stk_customer_key);
CREATE INDEX f_lottrackingdetail_key_idx1 ON dwh.f_lottrackingdetail USING btree (stk_ou, stk_location, stk_item, stk_customer, stk_date, stk_lot_no);
CREATE INDEX f_notesheader_key_idx ON dwh.f_notesheader USING btree (notes_compkey);
CREATE INDEX f_outbounddocdetail_key_idx ON dwh.f_outbounddocdetail USING btree (obd_loc_key);
CREATE INDEX f_outbounddocdetail_key_idx1 ON dwh.f_outbounddocdetail USING btree (oub_doc_loc_code, oub_outbound_ord, oub_doc_lineno, oub_doc_ou);
CREATE INDEX f_outbounddocdetail_key_idx2 ON dwh.f_outbounddocdetail USING btree (oub_doc_ou, oub_doc_loc_code, oub_doc_loc_code);
CREATE INDEX f_outboundheader_key_idx ON dwh.f_outboundheader USING btree (obh_cust_key, obh_loc_key);
CREATE INDEX f_outboundheader_key_idx1 ON dwh.f_outboundheader USING btree (oub_ou, oub_loc_code, oub_outbound_ord);
CREATE INDEX f_outboundheader_key_idx2 ON dwh.f_outboundheader USING btree (oub_ou, obh_loc_key, oub_prim_rf_dc_no);
CREATE INDEX f_outboundheader_key_idx3 ON dwh.f_outboundheader USING btree (obh_loc_key, obh_cust_key, oub_prim_rf_dc_no);
CREATE INDEX f_outboundheader_key_idx4 ON dwh.f_outboundheader USING btree (oub_prim_rf_dc_no, oub_ou);
CREATE INDEX f_outboundheader_key_idx_1 ON dwh.f_outboundheader USING btree (oub_orderdatekey);
CREATE INDEX f_outboundheader_key_idx_2 ON dwh.f_outboundheader USING btree (oub_modified_date, oub_created_date);
CREATE INDEX f_outboundheader_key_idx_5 ON dwh.f_outboundheader USING btree (oub_ou, oub_loc_code, oub_prim_rf_dc_no);
CREATE INDEX f_outboundheader_key_idx_7 ON dwh.f_outboundheader USING btree (oub_ou, oub_loc_code, oub_order_type, oub_shipment_type);
CREATE INDEX f_outboundheaderhistory_key_idx1 ON dwh.f_outboundheaderhistory USING btree (oub_ou, oub_loc_code, oub_outbound_ord, oub_amendno);
CREATE INDEX f_outboundheaderhistory_key_idx2 ON dwh.f_outboundheaderhistory USING btree (obh_loc_key, obh_cust_key);
CREATE INDEX f_outboundheaderhistory_key_idx3 ON dwh.f_outboundheaderhistory USING btree (obh_hr_his_key);
CREATE INDEX f_outbounditemdetail_key_idx ON dwh.f_outbounditemdetail USING btree (obd_itm_key, obd_loc_key);
CREATE INDEX f_outbounditemdetail_key_idx1 ON dwh.f_outbounditemdetail USING btree (oub_itm_ou, oub_itm_loc_code, oub_outbound_ord, oub_itm_lineno);
CREATE INDEX f_outbounditemdetailhistory_key_idx1 ON dwh.f_outbounditemdetailhistory USING btree (obd_itm_key, obd_loc_key);
CREATE INDEX f_outbounditemdetailhistory_key_idx2 ON dwh.f_outbounditemdetailhistory USING btree (oub_itm_loc_code, oub_itm_ou, oub_outbound_ord, oub_itm_amendno, oub_itm_lineno);
CREATE INDEX f_outbounditemdetailhistory_key_idx3 ON dwh.f_outbounditemdetailhistory USING btree (obh_hr_his_key);
CREATE INDEX f_outboundlotsrldetail_idx ON dwh.f_outboundlotsrldetail USING btree (oub_lotsl_ou, oub_lotsl_loc_code, oub_outbound_ord);
CREATE INDEX f_outboundlotsrldetail_key_idx ON dwh.f_outboundlotsrldetail USING btree (oub_loc_key, oub_itm_key);
CREATE INDEX f_outboundlotsrldetail_key_idx1 ON dwh.f_outboundlotsrldetail USING btree (oub_lotsl_loc_code, oub_lotsl_ou, oub_outbound_ord, oub_lotsl_lineno);
CREATE INDEX f_outboundlotsrldetail_key_idx2 ON dwh.f_outboundlotsrldetail USING btree (oub_lotsl_ou, oub_lotsl_loc_code, oub_outbound_ord);
CREATE INDEX f_outboundlotsrldetailhistory_key_idx1 ON dwh.f_outboundlotsrldetailhistory USING btree (oub_lotsl_loc_code, oub_lotsl_ou, oub_outbound_ord, oub_lotsl_lineno, oub_lotsl_amendno);
CREATE INDEX f_outboundlotsrldetailhistory_key_idx2 ON dwh.f_outboundlotsrldetailhistory USING btree (oub_loc_key, oub_itm_key);
CREATE INDEX f_outboundlotsrldetailhistory_key_idx3 ON dwh.f_outboundlotsrldetailhistory USING btree (obh_hr_his_key);
CREATE INDEX f_outboundschdetail_key_idx ON dwh.f_outboundschdetail USING btree (oub_loc_key, oub_itm_key);
CREATE INDEX f_outboundschdetail_key_idx1 ON dwh.f_outboundschdetail USING btree (oub_sch_ou, oub_sch_loc_code, oub_outbound_ord, oub_sch_lineno, oub_item_lineno);
CREATE INDEX f_outboundschdetail_key_idx2 ON dwh.f_outboundschdetail USING btree (oub_sch_ou, oub_sch_loc_code, oub_outbound_ord);
CREATE INDEX f_outboundschdetailhistory_key_idx1 ON dwh.f_outboundschdetailhistory USING btree (oub_sch_loc_code, oub_sch_ou, oub_outbound_ord, oub_sch_amendno, oub_sch_lineno, oub_item_lineno);
CREATE INDEX f_outboundschdetailhistory_key_idx2 ON dwh.f_outboundschdetailhistory USING btree (oub_loc_key, oub_itm_key);
CREATE INDEX f_outboundschdetailhistory_key_idx3 ON dwh.f_outboundschdetailhistory USING btree (obh_hr_his_key);
CREATE INDEX f_outboundvasheader_key_idx ON dwh.f_outboundvasheader USING btree (oub_loc_key);
CREATE INDEX f_outboundvasheader_key_idx1 ON dwh.f_outboundvasheader USING btree (oub_ou, oub_loc_code, oub_outbound_ord, oub_lineno);
CREATE INDEX f_packexecheader_key_idx ON dwh.f_packexecheader USING btree (pack_loc_key);
CREATE INDEX f_packexecheader_key_idx1 ON dwh.f_packexecheader USING btree (pack_exec_ou, pack_loc_code, pack_exec_no);
CREATE INDEX f_packexecthudetail_key_idx ON dwh.f_packexecthudetail USING btree (pack_exec_hdr_key, pack_exec_thu_hdr_key, pack_exec_itm_hdr_key, pack_exec_loc_key, pack_exec_thu_key);
CREATE INDEX f_packexecthudetail_key_idx5 ON dwh.f_packexecthudetail USING btree (pack_exec_ou, pack_loc_code, pack_exec_no, pack_thu_id, pack_thu_lineno, pack_thu_ser_no);
CREATE INDEX f_packexecthudetail_key_idx8 ON dwh.f_packexecthudetail USING btree (pack_exec_loc_key, pack_so_no, pack_so_line_no);
CREATE INDEX f_packexecthudetailhistory_key_idx ON dwh.f_packexecthudetailhistory USING btree (pack_exec_thu_dtl_hst_key);
CREATE INDEX f_packexecthudetailhistory_key_idx2 ON dwh.f_packexecthudetailhistory USING btree (pack_exec_hdr_key);
CREATE INDEX f_packexecthudetailhistory_key_idx3 ON dwh.f_packexecthudetailhistory USING btree (pack_exec_loc_key);
CREATE INDEX f_packexecthudetailhistory_key_idx4 ON dwh.f_packexecthudetailhistory USING btree (pack_exec_thu_key);
CREATE INDEX f_packexecthudetailhistory_key_idx5 ON dwh.f_packexecthudetailhistory USING btree (pack_exec_ou, pack_loc_code, pack_exec_no, pack_thu_id, pack_thu_lineno, pack_thu_ser_no);
CREATE INDEX f_packexecthudetailhistory_key_idx6 ON dwh.f_packexecthudetailhistory USING btree (pack_exec_ou, pack_loc_code, pack_exec_no);
CREATE INDEX f_packexecthuheader_key_idx ON dwh.f_packexecthuheader USING btree (pack_exec_hdr_key, pack_exec_loc_key, pack_exec_uom_key, pack_exec_thu_key);
CREATE INDEX f_packexecthuheader_key_idx4 ON dwh.f_packexecthuheader USING btree (pack_exec_ou, pack_exec_loc_code, pack_exec_no, pack_exec_thu_id, pack_exec_thu_sr_no);
CREATE INDEX f_packheader_key_idx1 ON dwh.f_packheader USING btree (pack_location, pack_ou);
CREATE INDEX f_packitemserialdetail_key_idx ON dwh.f_packitemserialdetail USING btree (pack_itm_sl_dtl_loc_key, pack_itm_sl_dtl_itm_hdr_key, pack_itm_sl_dtl_thu_key);
CREATE INDEX f_packplandetail_key_idx ON dwh.f_packplandetail USING btree (pack_loc_code, pack_pln_no, pack_pln_ou, pack_lineno);
CREATE INDEX f_packplandetail_key_idx1 ON dwh.f_packplandetail USING btree (pack_pln_hdr_key, pack_pln_dtl_loc_key, pack_pln_dtl_itm_hdr_key, pack_pln_dtl_thu_key);
CREATE INDEX f_packplanheader_key_idx ON dwh.f_packplanheader USING btree (pack_loc_code, pack_pln_no, pack_pln_ou);
CREATE INDEX f_packplanheader_key_idx1 ON dwh.f_packplanheader USING btree (pack_pln_hdr_loc_key, pack_pln_hdr_date_key, pack_pln_hdr_emp_hdr_key);
CREATE INDEX f_packstoragedetail_key_idx ON dwh.f_packstoragedetail USING btree (pack_location, pack_ou, pack_lineno);
CREATE INDEX f_packstoragedetail_key_idx1 ON dwh.f_packstoragedetail USING btree (pack_storage_dtl_loc_key);
CREATE INDEX f_pcsgateinfodetail_key_idx ON dwh.f_pcsgateinfodetail USING btree (datekey);
CREATE INDEX f_pickempequipmapdetail_key_idx ON dwh.f_pickempequipmapdetail USING btree (pick_loc_code, pick_ou, pick_lineno);
CREATE INDEX f_pickempequipmapdetail_key_idx1 ON dwh.f_pickempequipmapdetail USING btree (pick_emp_eqp_dtl_key_loc_key, pick_emp_eqp_dtl_key_emp_hdr_key, pick_emp_eqp_dtl_key_eqp_key, pick_emp_eqp_dtl_key_zone_key);
CREATE INDEX f_pickingdetail_key_idx ON dwh.f_pickingdetail USING btree (pick_loc_key, pick_itm_key, pick_hdr_key);
CREATE INDEX f_pickingdetail_key_idx1 ON dwh.f_pickingdetail USING btree (pick_loc_code, pick_exec_no, pick_exec_ou, pick_lineno);
CREATE INDEX f_pickingdetail_key_idx2 ON dwh.f_pickingdetail USING btree (pick_loc_key, pick_so_no);
CREATE INDEX f_pickingdetail_key_idx3 ON dwh.f_pickingdetail USING btree (pick_loc_key, pick_so_no, pick_so_line_no);
CREATE INDEX f_pickingheader_key_idx ON dwh.f_pickingheader USING btree (pick_loc_key);
CREATE INDEX f_pickingheader_key_idx1 ON dwh.f_pickingheader USING btree (pick_loc_code, pick_exec_no, pick_exec_ou);
CREATE INDEX f_pickplandetails_key_idx ON dwh.f_pickplandetails USING btree (pick_pln_loc_key, pick_pln_item_key, pick_pln_thu_key, pick_pln_hdr_key);
CREATE INDEX f_pickplandetails_key_idx1 ON dwh.f_pickplandetails USING btree (pick_loc_code, pick_pln_no, pick_pln_ou, pick_lineno);
CREATE INDEX f_pickplanheader_key_idx ON dwh.f_pickplanheader USING btree (pick_pln_loc_key);
CREATE INDEX f_pickplanheader_key_idx1 ON dwh.f_pickplanheader USING btree (pick_loc_code, pick_pln_no, pick_pln_ou);
CREATE INDEX f_pickrulesheader_key_idx ON dwh.f_pickrulesheader USING btree (pick_loc_key);
CREATE INDEX f_pickrulesheader_key_idx1 ON dwh.f_pickrulesheader USING btree (pick_loc_code, pick_ou);
CREATE INDEX f_planningdetail_key_idx ON dwh.f_planningdetail USING btree (plpd_cust_key);
CREATE INDEX f_planningdetail_key_idx1 ON dwh.f_planningdetail USING btree (plpd_ouinstance, plpd_plan_run_no, plpd_plan_unique_id);
CREATE INDEX f_planningheader_key_idx ON dwh.f_planningheader USING btree (plph_loc_key);
CREATE INDEX f_planningheader_key_idx1 ON dwh.f_planningheader USING btree (plph_ouinstance, plph_plan_run_no);
CREATE INDEX f_pogritemdetail_key_idx ON dwh.f_pogritemdetail USING btree (gr_po_loc_key);
CREATE INDEX f_pogritemdetail_key_idx1 ON dwh.f_pogritemdetail USING btree (gr_loc_code, gr_pln_no, gr_pln_ou, gr_lineno);
CREATE INDEX f_poprcoverage_key_idx1 ON dwh.f_poprcoverage USING btree (poprq_poou, poprq_pono, poprq_poamendmentno, poprq_polineno, poprq_scheduleno, poprq_prno, poprq_posubscheduleno, poprq_prlineno, poprq_prou, poprq_pr_shdno, poprq_pr_subsceduleno);
CREATE INDEX f_purchasedetails_key_idx ON dwh.f_purchasedetails USING btree (po_hr_key, po_dtl_cust_key, po_dtl_loc_key, po_dtl_wh_key, po_dtl_uom_key);
CREATE INDEX f_purchasedetails_key_idx1 ON dwh.f_purchasedetails USING btree (poou, pono, poamendmentno, polineno);
CREATE INDEX f_purchaseheader_key_idx ON dwh.f_purchaseheader USING btree (po_loc_key, po_date_key, po_cur_key, po_supp_key);
CREATE INDEX f_purchaseheader_key_idx1 ON dwh.f_purchaseheader USING btree (poou, pono, poamendmentno);
CREATE INDEX f_purchasereceiptheader_key_idx ON dwh.f_purchasereceiptheader USING btree (rcgh_date_key);
CREATE INDEX f_purchasereceiptheader_key_idx1 ON dwh.f_purchasereceiptheader USING btree (rcgh_ouinstid, rcgh_receipt_no);
CREATE INDEX f_purchasereqdetail_key_idx ON dwh.f_purchasereqdetail USING btree (preqm_hr_key, preqm_dtl_wh_key, preqm_dtl_uom_key, preqm_dtl_vendor_key, preqm_dtl_loc_key, preqm_dtl_customer_key);
CREATE INDEX f_purchasereqdetail_key_idx1 ON dwh.f_purchasereqdetail USING btree (prqit_prou, prqit_prno, prqit_lineno);
CREATE INDEX f_purchasereqheader_key_idx ON dwh.f_purchasereqheader USING btree (preqm_hr_curr_key);
CREATE INDEX f_purchasereqheader_key_idx1 ON dwh.f_purchasereqheader USING btree (preqm_prou, preqm_prno);
CREATE INDEX f_putawaybincapacity_key_idx ON dwh.f_putawaybincapacity USING btree (pway_pln_dtl_key, pway_bin_cap_loc_key, pway_bin_cap_itm_hdr_key);
CREATE INDEX f_putawaybincapacity_key_idx1 ON dwh.f_putawaybincapacity USING btree (pway_loc_code, pway_pln_no, pway_pln_ou, pway_lineno);
CREATE INDEX f_putawayempequipmap_key_idx ON dwh.f_putawayempequipmap USING btree (pway_eqp_map_eqp_key, pway_eqp_map_emp_hdr_key, pway_eqp_map_loc_key, pway_eqp_map_zone_key);
CREATE INDEX f_putawayempequipmap_key_idx1 ON dwh.f_putawayempequipmap USING btree (putaway_loc_code, putaway_ou, putaway_lineno);
CREATE INDEX f_putawayexecdetail_key_idx ON dwh.f_putawayexecdetail USING btree (pway_pln_dtl_key, pway_exe_dtl_loc_key, pway_exe_dtl_eqp_key, pway_exe_dtl_stg_mas_key, pway_exe_dtl_emp_hdr_key);
CREATE INDEX f_putawayexecdetail_key_idx1 ON dwh.f_putawayexecdetail USING btree (pway_loc_code, pway_exec_no, pway_exec_ou, pway_pln_no, pway_pln_ou);
CREATE INDEX f_putawayexecserialdetail_key_idx ON dwh.f_putawayexecserialdetail USING btree (pway_exe_dtl_key, pway_exec_serial_dtl_loc_key, pway_exec_serial_dtl_zone_key);
CREATE INDEX f_putawayexecserialdetail_key_idx1 ON dwh.f_putawayexecserialdetail USING btree (pway_loc_code, pway_exec_no, pway_exec_ou, pway_lineno);
CREATE INDEX f_putawayitemdetail_key_idx ON dwh.f_putawayitemdetail USING btree (pway_exe_dtl_key, pway_itm_dtl_itm_hdr_key, pway_itm_dtl_loc_key, pway_itm_dtl_zone_key);
CREATE INDEX f_putawayitemdetail_key_idx1 ON dwh.f_putawayitemdetail USING btree (pway_loc_code, pway_exec_no, pway_exec_ou, pway_exec_lineno, pway_gr_lineno, pway_gr_no);
CREATE INDEX f_putawayplandetail_date_idx ON dwh.f_putawayplandetail USING btree (pway_modified_date, pway_created_date);
CREATE INDEX f_putawayplandetail_key_idx ON dwh.f_putawayplandetail USING btree (pway_pln_dtl_date_key, pway_pln_dtl_loc_key, pway_pln_dtl_stg_mas_key, pway_pln_dtl_emp_hdr_key);
CREATE INDEX f_putawayplandetail_key_idx1 ON dwh.f_putawayplandetail USING btree (pway_loc_code, pway_pln_no, pway_pln_ou);
CREATE INDEX f_putawayplanitemdetail_key_idx ON dwh.f_putawayplanitemdetail USING btree (pway_pln_dtl_key, pway_pln_itm_dtl_itm_hdr_key, pway_pln_itm_dtl_loc_key, pway_pln_itm_dtl_zone_key);
CREATE INDEX f_putawayplanitemdetail_key_idx1 ON dwh.f_putawayplanitemdetail USING btree (pway_loc_code, pway_pln_no, pway_pln_ou, pway_lineno, pway_gr_no, pway_item);
CREATE INDEX f_putawayserialdetail_key_idx ON dwh.f_putawayserialdetail USING btree (pway_pln_dtl_key, pway_serial_dtl_loc_key, pway_serial_dtl_zone_key);
CREATE INDEX f_putawayserialdetail_key_idx1 ON dwh.f_putawayserialdetail USING btree (pway_loc_code, pway_pln_no, pway_pln_ou, pway_lineno);
CREATE INDEX f_rppostingsdtl_key_idx ON dwh.f_rppostingsdtl USING btree (ou_id, serial_no, unique_no, doc_type, tran_ou, document_no, account_code, tran_type);
CREATE INDEX f_rppostingsdtl_key_idx1 ON dwh.f_rppostingsdtl USING btree (rppostingsdtl_curr_key, rppostingsdtl_company_key, rppostingsdtl_datekey, rppostingsdtl_opcoa_key);
CREATE INDEX f_rptacctinfodtl_key_idx ON dwh.f_rptacctinfodtl USING btree (ou_id, tran_no, fb_id, account_code, tran_type, drcr_flag, posting_line_no);
CREATE INDEX f_rptacctinfodtl_key_idx1 ON dwh.f_rptacctinfodtl USING btree (rptacctinfodtl_curr_key, rptacctinfodtl_company_key, rptacctinfodtl_datekey, rptacctinfodtl_opcoa_key);
CREATE INDEX f_sadadjvcrdocdtl_key_idx ON dwh.f_sadadjvcrdocdtl USING btree (ou_id, adj_voucher_no, cr_doc_ou, cr_doc_no, term_no, cr_doc_type);
CREATE INDEX f_sadadjvcrdocdtl_key_idx1 ON dwh.f_sadadjvcrdocdtl USING btree (sadadjvcrdocdtl_curr_key);
CREATE INDEX f_sadadjvdrdocdtl_key_idx ON dwh.f_sadadjvdrdocdtl USING btree (ou_id, adj_voucher_no, dr_doc_ou, dr_doc_type, dr_doc_no, term_no);
CREATE INDEX f_sadadjvdrdocdtl_key_idx1 ON dwh.f_sadadjvdrdocdtl USING btree (sadadjvdrdocdtl_curr_key);
CREATE INDEX f_sadadjvoucherhdr_key_idx ON dwh.f_sadadjvoucherhdr USING btree (ou_id, adj_voucher_no, stimestamp);
CREATE INDEX f_sadadjvoucherhdr_key_idx1 ON dwh.f_sadadjvoucherhdr USING btree (sadadjvoucherhdr_curr_key, sadadjvoucherhdr_vendor_key);
CREATE INDEX f_scdnaccdtl_key_idx ON dwh.f_scdnaccdtl USING btree (tran_type, tran_ou, tran_no, line_no, stimestamp);
CREATE INDEX f_scdnappostingsdtl_key_idx ON dwh.f_scdnappostingsdtl USING btree (tran_type, tran_ou, tran_no, posting_line_no, s_timestamp);
CREATE INDEX f_scdndcnotehdr_key_idx ON dwh.f_scdndcnotehdr USING btree (tran_type, tran_ou, tran_no, ict_flag, ifb_flag);
CREATE INDEX f_sdinappostingsdtl_key_idx ON dwh.f_sdinappostingsdtl USING btree (tran_type, tran_ou, tran_no, posting_line_no, s_timestamp);
CREATE INDEX f_sdinexpensedtl_key_idx ON dwh.f_sdinexpensedtl USING btree (tran_type, tran_ou, tran_no, line_no, s_timestamp);
CREATE INDEX f_sdininvoicehdr_key_idx ON dwh.f_sdininvoicehdr USING btree (tran_type, tran_ou, tran_no, s_timestamp, payment_type, ict_flag, ales_flag, lgt_invoice, mail_sent, allow_auto_cap);
CREATE INDEX f_sidochdr_key_idx ON dwh.f_sidochdr USING btree (tran_ou, tran_type, tran_no);
CREATE INDEX f_silinedtl_key_idx ON dwh.f_silinedtl USING btree (tran_type, tran_ou, tran_no, line_no, ref_doc_no, row_type);
CREATE INDEX f_sinappostingsdtl_key_idx ON dwh.f_sinappostingsdtl USING btree (tran_type, tran_ou, tran_no, posting_line_no, a_timestamp);
CREATE INDEX f_sininvoicehdr_key_idx ON dwh.f_sininvoicehdr USING btree (tran_type, tran_ou, tran_no, "timestamp", tms_flag, gen_from_mntfrght);
CREATE INDEX f_sinitemdtl_key_idx ON dwh.f_sinitemdtl USING btree (tran_type, tran_ou, tran_no, line_no, ipv_flag, epv_flag);
CREATE INDEX f_sinitemdtl_key_idx1 ON dwh.f_sinitemdtl USING btree (si_sinitm_inv_key);
CREATE INDEX f_snpfbpostingdtl_key_idx ON dwh.f_snpfbpostingdtl USING btree (batch_id, ou_id, document_no, account_lineno, account_code, "timestamp");
CREATE INDEX f_snpvoucherdtl_key_idx ON dwh.f_snpvoucherdtl USING btree (curr_key);
CREATE INDEX f_snpvoucherhdr_key_idx ON dwh.f_snpvoucherhdr USING btree (curr_key);
CREATE INDEX f_spypaybatchdtl_key_idx ON dwh.f_spypaybatchdtl USING btree (curr_key, vendor_key);
CREATE INDEX f_spypaybatchhdr_key_idx ON dwh.f_spypaybatchhdr USING btree (curr_key);
CREATE INDEX f_spyprepayvchhdr_key_idx ON dwh.f_spyprepayvchhdr USING btree (vendor_key, curr_key);
CREATE INDEX f_spyvoucherhdr_key_idx1 ON dwh.f_spyvoucherhdr USING btree (ou_id, paybatch_no, voucher_no, "timestamp", line_no, ict_flag);
CREATE INDEX f_stock_lottrackingdaywise_detail_key_idx ON dwh.f_stock_lottrackingdaywise_detail USING btree (stk_loc_key, stk_item_key, stk_customer_key);
CREATE INDEX f_stock_lottrackingdaywise_detail_key_idx1 ON dwh.f_stock_lottrackingdaywise_detail USING btree (stk_ou, stk_location, stk_item, stk_customer, stk_date, stk_lot_no, stk_stock_status);
CREATE INDEX f_stockbalanceseriallevel_key_idx ON dwh.f_stockbalanceseriallevel USING btree (sbs_level_itm_hdr_key, sbs_level_zone_key, sbs_level_wh_key);
CREATE INDEX f_stockbalancestorageunitlotlevel_key_idx ON dwh.f_stockbalancestorageunitlotlevel USING btree (sbl_lot_level_itm_hdr_key, sbl_lot_level_zone_key, sbl_lot_level_wh_key, sbl_lot_level_thu_key);
CREATE INDEX f_stockbalancestorageunitseriallevel_key_idx ON dwh.f_stockbalancestorageunitseriallevel USING btree (sbl_lot_level_itm_hdr_key);
CREATE INDEX f_stockbalancestorageunitseriallevel_key_idx1 ON dwh.f_stockbalancestorageunitseriallevel USING btree (sbs_wh_code, sbs_ouinstid, sbs_item_code, sbs_sr_no, sbs_zone, sbs_bin, sbs_stock_status, sbs_lot_no, sbs_su_serial_no, sbs_thu_serial_no);
CREATE INDEX f_stockbinhistorydetail_key_idx ON dwh.f_stockbinhistorydetail USING btree (stock_loc_key, stock_thu_key, stock_item_key, stock_cust_key);
CREATE INDEX f_stockbinhistorydetail_key_idx1 ON dwh.f_stockbinhistorydetail USING btree (stock_ou, stock_date, stock_location, stock_zone, stock_bin, stock_item, stock_thu_id, stock_su);
CREATE INDEX f_stockbinhistorydetail_key_idx2 ON dwh.f_stockbinhistorydetail USING btree (stock_ou, stock_bin, stock_location, stock_zone, stock_bin_type);
CREATE INDEX f_stockbinhistorydetail_key_idx3 ON dwh.f_stockbinhistorydetail USING btree (bin_dtl_key);
CREATE INDEX f_stockconversiondetail_key_idx ON dwh.f_stockconversiondetail USING btree (stk_con_hdr_key, stk_con_dtl_loc_key, stk_con_dtl_customer_key, stk_con_dtl_itm_hdr_key, stk_con_dtl_zone_key);
CREATE INDEX f_stockconversionheader_key_idx ON dwh.f_stockconversionheader USING btree (stk_con_loc_key, stk_con_date_key);
CREATE INDEX f_stockrejecteddetail_key_idx ON dwh.f_stockrejecteddetail USING btree (rejstk_dtl_loc_key, rejstk_dtl_itm_hdr_key, rejstk_dtl_thu_key);
CREATE INDEX f_stockstoragebalancedetail_key_idx ON dwh.f_stockstoragebalancedetail USING btree (stk_su_loc_key, stk_su_customer_key);
CREATE INDEX f_stockuiditemtrackingdetail_key_idx ON dwh.f_stockuiditemtrackingdetail USING btree (stk_itm_dtl_loc_key, stk_itm_dtl_itm_hdr_key, stk_itm_dtl_customer_key, stk_itm_dtl_date_key, stk_itm_dtl_thu_key);
CREATE INDEX f_stockuidtrackingdetail_key_idx ON dwh.f_stockuidtrackingdetail USING btree (stk_trc_dtl_loc_key, stk_trc_dtl_zone_key, stk_trc_dtl_bin_type_key, stk_trc_dtl_customer_key, stk_trc_dtl_thu_key);
CREATE INDEX f_surfbpostingsdtl_key_idx ON dwh.f_surfbpostingsdtl USING btree (surf_trn_curr_key, surf_trn_company_key);
CREATE INDEX f_surreceiptdtl_key_idx ON dwh.f_surreceiptdtl USING btree (ou_id, receipt_type, receipt_no, refdoc_lineno, tran_type, stimestamp);
CREATE INDEX f_surreceiptdtl_key_idx1 ON dwh.f_surreceiptdtl USING btree (surreceiptdtl_curr_key, surreceiptdtl_opcoa_key);
CREATE INDEX f_surreceipthdr_key_idx ON dwh.f_surreceipthdr USING btree (ou_id, receipt_no, receipt_type, tran_type, stimestamp, ifb_flag);
CREATE INDEX f_surreceipthdr_key_idx1 ON dwh.f_surreceipthdr USING btree (surreceipthdr_curr_key, surreceipthdr_datekey);
CREATE INDEX f_tariffrevcostdetail_key_idx ON dwh.f_tariffrevcostdetail USING btree (tarcd_ouinstance, tarcd_trip_plan_id, tarcd_booking_request, tarcd_unique_id, tarcd_stage_of_derivation, tarcd_buy_sell_type);
CREATE INDEX f_tariffrevcostdetail_key_idx1 ON dwh.f_tariffrevcostdetail USING btree (tarcd_trip_hdr_key);
CREATE INDEX f_tariffrevcostheader_key_idx ON dwh.f_tariffrevcostheader USING btree (tarch_ouinstance, tarch_trip_plan_id, tarch_unique_id, tarch_buy_sell_type, tarch_stage_of_derivation);
CREATE INDEX f_tariffrevcostheader_key_idx1 ON dwh.f_tariffrevcostheader USING btree (tarch_trip_hdr_key);
CREATE INDEX f_tbpvoucherhdr_key_idx ON dwh.f_tbpvoucherhdr USING btree (current_key, company_code, component_name, bu_id, fb_id, fb_voucher_no);
CREATE INDEX f_tcaltranhdr_key_idx ON dwh.f_tcaltranhdr USING btree (tran_no, tax_type, tran_type, tran_ou);
CREATE INDEX f_tenderrequirementdetail_key_idx ON dwh.f_tenderrequirementdetail USING btree (trd_hdr_key);
CREATE INDEX f_tenderrequirementheader_key_idx ON dwh.f_tenderrequirementheader USING btree (trh_date_key);
CREATE INDEX f_tripexecutionplandetail_key_idx ON dwh.f_tripexecutionplandetail USING btree (br_key);
CREATE INDEX f_tripexecutionplandetail_key_idx1 ON dwh.f_tripexecutionplandetail USING btree (plepd_ouinstance, plepd_execution_plan_id, plepd_line_no);
CREATE INDEX f_triplogagentdetail_key_idx ON dwh.f_triplogagentdetail USING btree (plpth_hdr_key);
CREATE INDEX f_triplogagentdetail_key_idx1 ON dwh.f_triplogagentdetail USING btree (tlad_ouinstance, tlad_trip_plan_id, tlad_dispatch_doc_no, tlad_thu_line_no);
CREATE INDEX f_triplogagentdetail_ndx ON dwh.f_triplogagentdetail USING btree (tlad_ouinstance, tlad_trip_plan_id, tlad_dispatch_doc_no);
CREATE INDEX f_triplogagentdetail_ndx3 ON dwh.f_triplogagentdetail USING btree (tlad_ag_ref_doc_no, tlad_trip_plan_id, tlad_ouinstance);
CREATE INDEX f_triplogeventdetail_key_idx ON dwh.f_triplogeventdetail USING btree (plpth_hdr_key);
CREATE INDEX f_triplogeventdetail_key_idx1 ON dwh.f_triplogeventdetail USING btree (tled_ouinstance, tled_trip_plan_id, tled_trip_plan_unique_id);
CREATE INDEX f_triplogeventdetail_key_idx2 ON dwh.f_triplogeventdetail USING btree (tled_actual_date_time);
CREATE INDEX f_triplogexpensedetail_key_idx ON dwh.f_triplogexpensedetail USING btree (tled_ouinstance, tled_trip_plan_id, tled_trip_plan_line_id);
CREATE INDEX f_triplogexpensedocdetail_key_idx ON dwh.f_triplogexpensedocdetail USING btree (tledd_ouinstance, tledd_doc_guid);
CREATE INDEX f_triplogexpenseheader_key_idx ON dwh.f_triplogexpenseheader USING btree (tleh_ouinstance, tleh_report_no, tleh_trip_id, tleh_report_creation_date);
CREATE INDEX f_triplogthudetail_key_idx ON dwh.f_triplogthudetail USING btree (tltd_vendor_key);
CREATE INDEX f_triplogthudetail_key_idx1 ON dwh.f_triplogthudetail USING btree (tltd_trip_plan_id, tltd_thu_line_no, tltd_trip_sequence, tltd_dispatch_doc_no, tltd_ouinstance, tltd_trip_plan_line_id);
CREATE INDEX f_tripododetail_key_idx ON dwh.f_tripododetail USING btree (plpth_hdr_key);
CREATE INDEX f_tripplanningdetail_key_idx ON dwh.f_tripplanningdetail USING btree (plptd_ouinstance, plptd_plan_run_no, plptd_trip_plan_id, plptd_trip_plan_seq, plptd_bk_req_id, plptd_trip_plan_unique_id);
CREATE INDEX f_tripplanningdetail_key_idx1 ON dwh.f_tripplanningdetail USING btree (plpth_hdr_key);
CREATE INDEX f_tripplanningdetail_key_idx2 ON dwh.f_tripplanningdetail USING btree (plptd_ouinstance, plptd_bk_req_id);
CREATE INDEX f_tripplanningdetail_key_idx3 ON dwh.f_tripplanningdetail USING btree (plptd_ouinstance, plptd_trip_plan_id, plptd_trip_plan_seq);
CREATE INDEX f_tripplanningheader_key_idx ON dwh.f_tripplanningheader USING btree (plpth_ouinstance, plpth_trip_plan_id);
CREATE INDEX f_tripplanningheader_key_idx2 ON dwh.f_tripplanningheader USING btree (plpth_trip_plan_date);
CREATE INDEX f_tripplanningheader_key_idx3 ON dwh.f_tripplanningheader USING btree (plpth_trip_plan_datekey);
CREATE INDEX f_tripplanningheader_key_idx4 ON dwh.f_tripplanningheader USING btree (plpth_vehicle_key);
CREATE INDEX f_trippodattachmentdetail_key_idx ON dwh.f_trippodattachmentdetail USING btree (tpad_line_no);
CREATE INDEX f_trippodattachmentdetail_key_idx1 ON dwh.f_trippodattachmentdetail USING btree (tpad_trip_hdr_key);
CREATE INDEX f_trippodattachmentdetail_key_idx2 ON dwh.f_trippodattachmentdetail USING btree (tpad_ouinstance, tpad_trip_id, tpad_dispatch_doc_no);
CREATE INDEX f_trippodattachmentdetail_key_idx3 ON dwh.f_trippodattachmentdetail USING btree (tpad_ouinstance, ((tpad_trip_id)::text), ((COALESCE(tpad_dispatch_doc_no, tpad_doc_no))::text));
CREATE INDEX f_tripresourcescheduledetail_key_idx ON dwh.f_tripresourcescheduledetail USING btree (trsd_vendor_key);
CREATE INDEX f_tripresourcescheduledetail_key_idx1 ON dwh.f_tripresourcescheduledetail USING btree (trsd_ouinstance, trsd_trip_plan_id, trsd_resource_type, trsd_resource_id);
CREATE INDEX f_tripthudetail_key_idx ON dwh.f_tripthudetail USING btree (plttd_thu_key);
CREATE INDEX f_tripthudetail_key_idx1 ON dwh.f_tripthudetail USING btree (plttd_ouinstance, plttd_trip_plan_id, plttd_trip_plan_line_no, plttd_thu_line_no, plttd_dispatch_doc_no);
CREATE INDEX f_tripthudetail_key_idx2 ON dwh.f_tripthudetail USING btree (plttd_thu_id, plttd_ouinstance);
CREATE INDEX f_tripthuserialdetail_key_idx ON dwh.f_tripthuserialdetail USING btree (plttd_trip_thu_key);
CREATE INDEX f_tripthuserialdetail_key_idx1 ON dwh.f_tripthuserialdetail USING btree (plttsd_ouinstance, plttsd_trip_plan_id, plttsd_thu_line_id, plttsd_dispatch);
CREATE INDEX f_tripvendortariffrevcostdetail_key_idx ON dwh.f_tripvendortariffrevcostdetail USING btree (tvtrcd_ouinstance, tvtrcd_trip_plan_id, tvtrcd_booking_request, tvtrcd_unique_id);
CREATE INDEX f_tripvendortariffrevcostdetail_key_idx1 ON dwh.f_tripvendortariffrevcostdetail USING btree (tvtrcd_hdr_key);
CREATE INDEX f_tripvendortariffrevcostheader_key_idx ON dwh.f_tripvendortariffrevcostheader USING btree (tvtrch_ouinstance, tvtrch_trip_plan_id, tvtrch_unique_id, tvtrch_stage_of_derivation);
CREATE INDEX f_vehicleequiplicensedetail_key_idx ON dwh.f_vehicleequiplicensedetail USING btree (vrvel_vendor_key);
CREATE INDEX f_vehicleequipresponsedetail_key_idx ON dwh.f_vehicleequipresponsedetail USING btree (vrve_vendor_key);
CREATE INDEX f_wavedetail_key_idx ON dwh.f_wavedetail USING btree (wave_loc_key, wave_item_key, wave_cust_key, wave_hdr_key);
CREATE INDEX f_wavedetail_key_idx1 ON dwh.f_wavedetail USING btree (wave_lineno, wave_no, wave_loc_code, wave_ou);
CREATE INDEX f_wavedetail_key_idx2 ON dwh.f_wavedetail USING btree (wave_ou, wave_loc_key, wave_cust_key, wave_item_key, wave_so_no);
CREATE INDEX f_wavedetail_key_idx3 ON dwh.f_wavedetail USING btree (wave_loc_key, wave_cust_key, wave_so_no);
CREATE INDEX f_wavedetail_key_idx4 ON dwh.f_wavedetail USING btree (wave_loc_key, wave_so_no);
CREATE INDEX f_wavedetail_key_idx5 ON dwh.f_wavedetail USING btree (wave_so_no, wave_ou);
CREATE INDEX f_waveheader_key_idx ON dwh.f_waveheader USING btree (wave_loc_key);
CREATE INDEX f_waveheader_key_idx1 ON dwh.f_waveheader USING btree (wave_loc_code, wave_no, wave_ou);
CREATE INDEX f_tripplanningheader_key_idx ON stg.stg_tms_pltph_trip_plan_hdr USING btree (plpth_vehicle_id);
CREATE INDEX stg_aplan_acq_proposal_hdr_key_idx2 ON stg.stg_aplan_acq_proposal_hdr USING btree (ou_id, fb_id, financial_year, asset_class_code, currency_code, proposal_number, addnl_entity);
CREATE INDEX stg_at_wms_asn_header_idx1 ON stg.stg_at_wms_asn_header USING btree (wms_asn_ou, wms_asn_location, wms_asn_no);
CREATE INDEX stg_pcsit_rdil_uncontrollable_tbl_idx ON stg.stg_pcsit_rdil_uncontrollable_tbl USING btree (tranou, type, activity, locationcode, invoiceno, invoiceholdtype, invoicedate, guid, remarks);
CREATE INDEX stg_po_poitm_item_detail_key_idx1 ON stg.stg_po_poitm_item_detail USING btree (poitm_pono, poitm_poamendmentno, poitm_polineno, poitm_poou);
CREATE INDEX stg_po_pomas_pur_order_hdr_key_idx1 ON stg.stg_po_pomas_pur_order_hdr USING btree (pomas_pono, pomas_poamendmentno, pomas_poou);
CREATE INDEX stg_po_poprq_poprcovg_detail_key_idx1 ON stg.stg_po_poprq_poprcovg_detail USING btree (poprq_pono, poprq_poamendmentno, poprq_polineno, poprq_scheduleno, poprq_posubscheduleno, poprq_prou, poprq_prno, poprq_prlineno, poprq_pr_shdno, poprq_pr_subsceduleno, poprq_poou);
CREATE INDEX stg_prq_preqm_pur_reqst_hdr_key_idx1 ON stg.stg_prq_preqm_pur_reqst_hdr USING btree (preqm_prno, preqm_prou);
CREATE INDEX stg_prq_prqit_item_detail_idx1 ON stg.stg_prq_prqit_item_detail USING btree (prqit_prno, prqit_lineno, prqit_prou);
CREATE INDEX stg_rct_purchase_hdr_key_idx2 ON stg.stg_rct_purchase_hdr USING btree (rcgh_ouinstid, rcgh_receipt_no);
CREATE INDEX stg_rp_postings_dtl_idx ON stg.stg_rp_postings_dtl USING btree (ou_id, serial_no, unique_no, doc_type, tran_ou, document_no, account_code, tran_type);
CREATE INDEX stg_rpt_acct_info_dtl_idx ON stg.stg_rpt_acct_info_dtl USING btree (ou_id, tran_no, account_code, tran_type, drcr_flag, posting_line_no);
CREATE INDEX stg_sad_adjvoucher_hdr_idx ON stg.stg_sad_adjvoucher_hdr USING btree (ou_id, adj_voucher_no, stimestamp);
CREATE INDEX stg_spy_voucher_hdr_key_idx2 ON stg.stg_spy_voucher_hdr USING btree (ou_id, paybatch_no, voucher_no, line_no, ict_flag);
CREATE INDEX stg_stg_wms_pick_exec_dtl_idx2 ON stg.stg_wms_pick_exec_dtl USING btree (wms_pick_loc_code, wms_pick_exec_no, wms_pick_exec_ou, wms_pick_lineno);
CREATE INDEX stg_sur_receipt_dtl_idx ON stg.stg_sur_receipt_dtl USING btree (ou_id, receipt_type, receipt_no, refdoc_lineno, tran_type);
CREATE INDEX stg_sur_receipt_hdr_idx ON stg.stg_sur_receipt_hdr USING btree (ou_id, receipt_no, receipt_type, tran_type);
CREATE INDEX stg_tms_br_ewaybill_details_key_idx1 ON stg.stg_tms_br_ewaybill_details USING btree (ewbd_br_no, ewbd_ouinstance);
CREATE INDEX stg_tms_brcd_consgt_details_key_idx1 ON stg.stg_tms_brcd_consgt_details USING btree (cd_ouinstance, cd_br_id, cd_line_no);
CREATE INDEX stg_tms_brcsd_consgt_sku_details_key_idx1 ON stg.stg_tms_brcsd_consgt_sku_details USING btree (brcsd_ou, brcsd_br_id, brcsd_thu_line_no, brcsd_sku_line_no);
CREATE INDEX stg_tms_brctd_br_thu_wise_contract_tariff_dtls_key_idx1 ON stg.stg_tms_brctd_br_thu_wise_contract_tariff_dtls USING btree (brctd_ou, brctd_br_id, brctd_tariff_id);
CREATE INDEX stg_tms_brsd_shipment_details_idx ON stg.stg_tms_brsd_shipment_details USING btree (brsd_ouinstance, brsd_br_id);
CREATE INDEX stg_tms_ddh_dispatch_document_hdr_key_idx1 ON stg.stg_tms_ddh_dispatch_document_hdr USING btree (ddh_ouinstance, ddh_dispatch_doc_no);
CREATE INDEX stg_tms_dds_dispatch_document_signature_key_idx1 ON stg.stg_tms_dds_dispatch_document_signature USING btree (dds_ouinstance, dds_trip_id, dds_seqno, dds_dispatch_doc_no);
CREATE INDEX stg_tms_ddtcd_dispatch_document_thu_serial_dtl_key_idx1 ON stg.stg_tms_ddtcd_dispatch_document_thu_serial_dtl USING btree (ddtsd_ouinstance, ddtsd_dispatch_doc_no, ddtsd_thu_line_no, ddtsd_thu_serial_line_no);
CREATE INDEX stg_tms_ddtd_dispatch_document_thu_dtl_key_idx1 ON stg.stg_tms_ddtd_dispatch_document_thu_dtl USING btree (ddtd_ouinstance, ddtd_dispatch_doc_no, ddtd_thu_line_no);
CREATE INDEX stg_tms_ddtsd_dispatch_document_thu_sku_dtl_key_idx1 ON stg.stg_tms_ddtsd_dispatch_document_thu_sku_dtl USING btree (ddtsd_ou, ddtsd_dispatch_doc_no, ddtsd_thu_line_no);
CREATE INDEX stg_tms_pletd_exec_thu_details_idx ON stg.stg_tms_pletd_exec_thu_details USING btree (pletd_ouinstance, pletd_execution_plan_id, pletd_line_no);
CREATE INDEX stg_tms_pletd_exec_thu_details_key_idx2 ON stg.stg_tms_pletd_exec_thu_details USING btree (pletd_ouinstance, pletd_execution_plan_id, pletd_line_no, pletd_dispatch_docno, pletd_thu_line_no);
CREATE INDEX stg_tms_pletsd_exec_thu_serial_details_key_idx2 ON stg.stg_tms_pletsd_exec_thu_serial_details USING btree (pletsd_ouinstance, pletsd_execution_plan_id, pletsd_line_no, pletsd_thu_line_no, pletsd_serial_line_no);
CREATE INDEX stg_tms_plpd_planning_details_key_idx2 ON stg.stg_tms_plpd_planning_details USING btree (plpd_ouinstance, plpd_plan_run_no, plpd_plan_unique_id);
CREATE INDEX stg_tms_plph_planning_hdr_key_idx2 ON stg.stg_tms_plph_planning_hdr USING btree (plph_ouinstance, plph_plan_run_no);
CREATE INDEX stg_tms_plttd_trip_thu_details_key_idx2 ON stg.stg_tms_plttd_trip_thu_details USING btree (plttd_ouinstance, plttd_trip_plan_id, plttd_trip_plan_line_no, plttd_thu_line_no, plttd_dispatch_doc_no);
CREATE INDEX stg_tms_resource_schedule_dtl_idx1 ON stg.stg_tms_resource_schedule_dtl USING btree (trsd_ouinstance, trsd_trip_plan_id, trsd_resource_type, trsd_resource_id);
CREATE INDEX stg_tms_resource_schedule_dtl_idx2 ON stg.stg_tms_resource_schedule_dtl USING btree (trsd_ouinstance, trsd_trip_plan_id);
CREATE INDEX stg_tms_tarcd_tariff_rev_cost_dtl_idx ON stg.stg_tms_tarcd_tariff_rev_cost_dtl USING btree (tarcd_ouinstance, tarcd_trip_plan_id, tarcd_booking_request, tarcd_unique_id, tarcd_stage_of_derivation, tarcd_buy_sell_type);
CREATE INDEX stg_tms_tled_trip_log_event_details_key_idx ON stg.stg_tms_tled_trip_log_event_details USING btree (tled_actual_date_time);
CREATE INDEX stg_tms_tled_trip_log_event_details_key_idx1 ON stg.stg_tms_tled_trip_log_event_details USING btree (tled_ouinstance, tled_trip_plan_id, tled_trip_plan_unique_id);
CREATE INDEX stg_wms_alloc_item_detail_hist_key_idx ON stg.stg_wms_alloc_item_detail_hist USING btree (allc_ouinstid, allc_doc_no, allc_doc_ou, allc_doc_line_no, allc_alloc_line_no);
CREATE INDEX stg_wms_alloc_item_detail_key_idx1 ON stg.stg_wms_alloc_item_detail USING btree (allc_doc_no, allc_doc_ou, allc_doc_line_no, allc_alloc_line_no);
CREATE INDEX stg_wms_asn_add_dtl_key_idx2 ON stg.stg_wms_asn_add_dtl USING btree (wms_asn_pop_asn_no, wms_asn_pop_loc, wms_asn_pop_ou, wms_asn_pop_line_no);
CREATE INDEX stg_wms_asn_detail_h_idx ON stg.stg_wms_asn_detail_h USING btree (wms_asn_ou, wms_asn_location, wms_asn_no, wms_asn_amendno, wms_asn_lineno);
CREATE INDEX stg_wms_asn_header_h_idx ON stg.stg_wms_asn_header_h USING btree (wms_asn_ou, wms_asn_location, wms_asn_no, wms_asn_amendno);
CREATE INDEX stg_wms_bin_dtl_key_idx1 ON stg.stg_wms_bin_dtl USING btree (wms_bin_ou, wms_bin_code, wms_bin_loc_code, wms_bin_zone, wms_bin_type);
CREATE INDEX stg_wms_bin_plan_hdr_key_idx2 ON stg.stg_wms_bin_plan_hdr USING btree (wms_bin_loc_code, wms_bin_pln_no, wms_bin_pln_ou);
CREATE INDEX stg_wms_bin_plan_item_dtl_key_idx2 ON stg.stg_wms_bin_plan_item_dtl USING btree (wms_bin_loc_code, wms_bin_pln_no, wms_bin_pln_lineno, wms_bin_pln_ou);
CREATE INDEX stg_wms_contract_dtl_idx ON stg.stg_wms_contract_dtl USING btree (wms_cont_id, wms_cont_ou);
CREATE INDEX stg_wms_contract_hdr_h_idx ON stg.stg_wms_contract_hdr_h USING btree (wms_cont_id, wms_cont_ou, wms_cont_amendno);
CREATE INDEX stg_wms_draft_bill_exec_dtl_key_idx1 ON stg.stg_wms_draft_bill_exec_dtl USING btree (wms_exec_loc_code, wms_exec_ou, wms_exec_no, wms_exec_stage, wms_exec_line_no);
CREATE INDEX stg_wms_gate_exec_dtl_key_idx1 ON stg.stg_wms_gate_exec_dtl USING btree (wms_gate_loc_code, wms_gate_exec_no, wms_gate_exec_ou);
CREATE INDEX stg_wms_gate_plan_dtl_key_idx1 ON stg.stg_wms_gate_plan_dtl USING btree (wms_gate_loc_code, wms_gate_pln_no, wms_gate_pln_ou);
CREATE INDEX stg_wms_goods_issue_dtl_key_idx2 ON stg.stg_wms_goods_issue_dtl USING btree (wms_gi_no, wms_gi_ou, wms_gi_loc_code, wms_gi_outbound_ord_no, wms_gi_line_no);
CREATE INDEX stg_wms_gr_plan_dtl_key_idx2 ON stg.stg_wms_gr_plan_dtl USING btree (wms_gr_loc_code, wms_gr_pln_no, wms_gr_pln_ou);
CREATE INDEX stg_wms_gr_po_item_dtl_key_idx2 ON stg.stg_wms_gr_po_item_dtl USING btree (wms_gr_loc_code, wms_gr_pln_no, wms_gr_pln_ou, wms_gr_lineno);
CREATE INDEX stg_wms_gr_thu_dtl_key_idx2 ON stg.stg_wms_gr_thu_dtl USING btree (wms_gr_loc_code, wms_gr_pln_no, wms_gr_pln_ou, wms_gr_lineno);
CREATE INDEX stg_wms_inbound_header_h_key_idx2 ON stg.stg_wms_inbound_header_h USING btree (wms_inb_loc_code, wms_inb_orderno, wms_inb_ou, wms_inb_amendno);
CREATE INDEX stg_wms_inbound_header_key_idx2 ON stg.stg_wms_inbound_header USING btree (wms_inb_loc_code, wms_inb_orderno, wms_inb_ou);
CREATE INDEX stg_wms_inbound_item_detail_h_key_idx2 ON stg.stg_wms_inbound_item_detail_h USING btree (wms_inb_loc_code, wms_inb_orderno, wms_inb_lineno, wms_inb_ou, wms_inb_amendno);
CREATE INDEX stg_wms_inbound_item_detail_key_idx2 ON stg.stg_wms_inbound_item_detail USING btree (wms_inb_loc_code, wms_inb_orderno, wms_inb_lineno, wms_inb_ou);
CREATE INDEX stg_wms_inbound_pln_track_dtl_key_idx2 ON stg.stg_wms_inbound_pln_track_dtl USING btree (wms_pln_lineno, wms_pln_ou);
CREATE INDEX stg_wms_inbound_sch_item_detail_key_idx2 ON stg.stg_wms_inbound_sch_item_detail USING btree (wms_inb_loc_code, wms_inb_orderno, wms_inb_lineno, wms_inb_ou);
CREATE INDEX stg_wms_int_ord_bin_dtl_key_idx2 ON stg.stg_wms_int_ord_bin_dtl USING btree (wms_in_ord_location, wms_in_ord_no, wms_in_ord_lineno, wms_in_ord_ou);
CREATE INDEX stg_wms_outbound_doc_detail_key_idx ON stg.stg_wms_outbound_doc_detail USING btree (wms_oub_doc_ou, wms_oub_doc_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_doc_detail_key_idx1 ON stg.stg_wms_outbound_doc_detail USING btree (wms_oub_doc_loc_code, wms_oub_doc_ou);
CREATE INDEX stg_wms_outbound_doc_detail_key_idx2 ON stg.stg_wms_outbound_doc_detail USING btree (wms_oub_doc_loc_code, wms_oub_outbound_ord, wms_oub_doc_lineno, wms_oub_doc_ou);
CREATE INDEX stg_wms_outbound_header_h_key_idx2 ON stg.stg_wms_outbound_header_h USING btree (wms_oub_ou, wms_oub_loc_code, wms_oub_outbound_ord, wms_oub_amendno);
CREATE INDEX stg_wms_outbound_header_key_idx ON stg.stg_wms_outbound_header USING btree (wms_oub_loc_code, wms_oub_ou);
CREATE INDEX stg_wms_outbound_header_key_idx1 ON stg.stg_wms_outbound_header USING btree (wms_oub_cust_code, wms_oub_ou);
CREATE INDEX stg_wms_outbound_header_key_idx2 ON stg.stg_wms_outbound_header USING btree (wms_oub_ou, wms_oub_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_item_detail_h_key_idx2 ON stg.stg_wms_outbound_item_detail_h USING btree (wms_oub_itm_loc_code, wms_oub_itm_ou, wms_oub_outbound_ord, wms_oub_itm_amendno, wms_oub_itm_lineno);
CREATE INDEX stg_wms_outbound_item_detail_idx ON stg.stg_wms_outbound_item_detail USING btree (wms_oub_item_code, wms_oub_itm_ou);
CREATE INDEX stg_wms_outbound_item_detail_idx1 ON stg.stg_wms_outbound_item_detail USING btree (wms_oub_itm_loc_code, wms_oub_itm_ou);
CREATE INDEX stg_wms_outbound_item_detail_idx2 ON stg.stg_wms_outbound_item_detail USING btree (wms_oub_itm_ou, wms_oub_itm_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_item_detail_key_idx2 ON stg.stg_wms_outbound_item_detail USING btree (wms_oub_itm_ou, wms_oub_itm_loc_code, wms_oub_outbound_ord, wms_oub_itm_lineno);
CREATE INDEX stg_wms_outbound_lot_ser_dtl_h_key_idx2 ON stg.stg_wms_outbound_lot_ser_dtl_h USING btree (wms_oub_lotsl_loc_code, wms_oub_lotsl_ou, wms_oub_outbound_ord, wms_oub_lotsl_lineno, wms_oub_lotsl_amendno);
CREATE INDEX stg_wms_outbound_lot_ser_dtl_idx ON stg.stg_wms_outbound_lot_ser_dtl USING btree (wms_oub_lotsl_loc_code, wms_oub_lotsl_ou);
CREATE INDEX stg_wms_outbound_lot_ser_dtl_idx1 ON stg.stg_wms_outbound_lot_ser_dtl USING btree (wms_oub_item_code, wms_oub_lotsl_ou);
CREATE INDEX stg_wms_outbound_lot_ser_dtl_idx3 ON stg.stg_wms_outbound_lot_ser_dtl USING btree (wms_oub_lotsl_ou, wms_oub_lotsl_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_lot_ser_dtl_key_idx2 ON stg.stg_wms_outbound_lot_ser_dtl USING btree (wms_oub_lotsl_loc_code, wms_oub_lotsl_ou, wms_oub_outbound_ord, wms_oub_lotsl_lineno);
CREATE INDEX stg_wms_outbound_sch_dtl_h_key_idx2 ON stg.stg_wms_outbound_sch_dtl_h USING btree (wms_oub_sch_loc_code, wms_oub_sch_ou, wms_oub_outbound_ord, wms_oub_sch_amendno, wms_oub_sch_lineno, wms_oub_item_lineno);
CREATE INDEX stg_wms_outbound_sch_dtl_idx ON stg.stg_wms_outbound_sch_dtl USING btree (wms_oub_sch_loc_code, wms_oub_sch_ou);
CREATE INDEX stg_wms_outbound_sch_dtl_idx1 ON stg.stg_wms_outbound_sch_dtl USING btree (wms_oub_sch_item_code, wms_oub_sch_ou);
CREATE INDEX stg_wms_outbound_sch_dtl_idx3 ON stg.stg_wms_outbound_sch_dtl USING btree (wms_oub_sch_ou, wms_oub_sch_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_sch_dtl_key_idx2 ON stg.stg_wms_outbound_sch_dtl USING btree (wms_oub_sch_ou, wms_oub_sch_loc_code, wms_oub_outbound_ord, wms_oub_sch_lineno, wms_oub_item_lineno);
CREATE INDEX stg_wms_outbound_vas_hdr_idx ON stg.stg_wms_outbound_vas_hdr USING btree (wms_oub_ou, wms_oub_loc_code, wms_oub_outbound_ord);
CREATE INDEX stg_wms_outbound_vas_hdr_idx1 ON stg.stg_wms_outbound_vas_hdr USING btree (wms_oub_loc_code, wms_oub_ou);
CREATE INDEX stg_wms_outbound_vas_hdr_key_idx1 ON stg.stg_wms_outbound_vas_hdr USING btree (wms_oub_ou, wms_oub_loc_code, wms_oub_outbound_ord, wms_oub_lineno);
CREATE INDEX stg_wms_pack_exec_hdr_key_idx2 ON stg.stg_wms_pack_exec_hdr USING btree (wms_pack_loc_code, wms_pack_exec_no, wms_pack_exec_ou);
CREATE INDEX stg_wms_pack_exec_thu_dtl_hist_idx ON stg.stg_wms_pack_exec_thu_dtl_hist USING btree (wms_pack_exec_ou, wms_pack_loc_code, wms_pack_exec_no, wms_pack_thu_id, wms_pack_thu_lineno, wms_pack_thu_ser_no);
CREATE INDEX stg_wms_pack_exec_thu_dtl_hist_idx1 ON stg.stg_wms_pack_exec_thu_dtl_hist USING btree (wms_pack_exec_ou, wms_pack_loc_code, wms_pack_exec_no);
CREATE INDEX stg_wms_pack_exec_thu_dtl_hist_idx2 ON stg.stg_wms_pack_exec_thu_dtl_hist USING btree (wms_pack_exec_ou, wms_pack_loc_code);
CREATE INDEX stg_wms_pack_exec_thu_dtl_hist_idx3 ON stg.stg_wms_pack_exec_thu_dtl_hist USING btree (wms_pack_exec_ou, wms_pack_thu_id);
CREATE INDEX stg_wms_pack_exec_thu_dtl_key_idx2 ON stg.stg_wms_pack_exec_thu_dtl USING btree (wms_pack_exec_ou, wms_pack_loc_code, wms_pack_exec_no, wms_pack_thu_id, wms_pack_thu_lineno, wms_pack_thu_ser_no);
CREATE INDEX stg_wms_pack_exec_thu_hdr_idx_uom ON stg.stg_wms_pack_exec_thu_hdr USING btree (wms_pack_exec_ou, wms_pack_uom);
CREATE INDEX stg_wms_pack_exec_thu_hdr_key_idx2 ON stg.stg_wms_pack_exec_thu_hdr USING btree (wms_pack_exec_ou, wms_pack_loc_code, wms_pack_exec_no, wms_pack_thu_id, wms_pack_thu_sr_no);
CREATE INDEX stg_wms_pack_hdr_key_idx2 ON stg.stg_wms_pack_hdr USING btree (wms_pack_location, wms_pack_ou);
CREATE INDEX stg_wms_pack_plan_dtl_idx ON stg.stg_wms_pack_plan_dtl USING btree (wms_pack_pln_ou, wms_pack_loc_code, wms_pack_pln_no, wms_pack_lineno);
CREATE INDEX stg_wms_pack_plan_dtl_idx1 ON stg.stg_wms_pack_plan_dtl USING btree (wms_pack_pln_ou, wms_pack_loc_code);
CREATE INDEX stg_wms_pack_plan_dtl_idx2 ON stg.stg_wms_pack_plan_dtl USING btree (wms_pack_pln_ou, wms_pack_item_code);
CREATE INDEX stg_wms_pack_plan_dtl_idx3 ON stg.stg_wms_pack_plan_dtl USING btree (wms_pack_pln_ou, wms_pack_thu_id);
CREATE INDEX stg_wms_pack_plan_hdr_idx ON stg.stg_wms_pack_plan_hdr USING btree (wms_pack_loc_code, wms_pack_pln_no, wms_pack_pln_ou);
CREATE INDEX stg_wms_pack_storage_dtl_idx ON stg.stg_wms_pack_storage_dtl USING btree (wms_pack_location, wms_pack_ou, wms_pack_lineno);
CREATE INDEX stg_wms_pick_emp_equip_map_dtl_idx ON stg.stg_wms_pick_emp_equip_map_dtl USING btree (wms_pick_loc_code, wms_pick_ou, wms_pick_lineno);
CREATE INDEX stg_wms_put_exec_item_dtl_key_idx1 ON stg.stg_wms_put_exec_item_dtl USING btree (wms_pway_loc_code, wms_pway_exec_no, wms_pway_exec_ou, wms_pway_exec_lineno);
CREATE INDEX stg_wms_put_exec_serial_dtl_key_idx1 ON stg.stg_wms_put_exec_serial_dtl USING btree (wms_pway_loc_code, wms_pway_exec_no, wms_pway_exec_ou, wms_pway_lineno);
CREATE INDEX stg_wms_put_plan_item_dtl_key_idx1 ON stg.stg_wms_put_plan_item_dtl USING btree (wms_pway_loc_code, wms_pway_pln_no, wms_pway_pln_ou, wms_pway_lineno);
CREATE INDEX stg_wms_put_serial_dtl_key_idx1 ON stg.stg_wms_put_serial_dtl USING btree (wms_pway_loc_code, wms_pway_pln_no, wms_pway_pln_ou, wms_pway_lineno);
CREATE INDEX stg_wms_putaway_bin_capacity_dtl_idx1 ON stg.stg_wms_putaway_bin_capacity_dtl USING btree (wms_pway_loc_code, wms_pway_pln_no, wms_pway_pln_ou, wms_pway_lineno);
CREATE INDEX stg_wms_putaway_emp_equip_map_dtl_key_idx1 ON stg.stg_wms_putaway_emp_equip_map_dtl USING btree (wms_putaway_loc_code, wms_putaway_ou, wms_putaway_lineno);
CREATE INDEX stg_wms_putaway_exec_dtl_key_idx1 ON stg.stg_wms_putaway_exec_dtl USING btree (wms_pway_loc_code, wms_pway_exec_no, wms_pway_exec_ou);
CREATE INDEX stg_wms_putaway_plan_dtl_key_idx1 ON stg.stg_wms_putaway_plan_dtl USING btree (wms_pway_loc_code, wms_pway_pln_no, wms_pway_pln_ou);
CREATE INDEX stg_wms_stock_bin_history_dtl_idx1 ON stg.stg_wms_stock_bin_history_dtl USING btree (wms_stock_ou, wms_stock_bin, wms_stock_location, wms_stock_zone, wms_stock_bin_type, wms_stock_date, wms_stock_item, wms_stock_thu_id, wms_stock_su);
CREATE INDEX stg_wms_stock_bin_history_dtl_idx2 ON stg.stg_wms_stock_bin_history_dtl USING btree (wms_stock_location, wms_stock_ou);
CREATE INDEX stg_wms_stock_bin_history_dtl_idx3 ON stg.stg_wms_stock_bin_history_dtl USING btree (wms_stock_item, wms_stock_ou);
CREATE INDEX stg_wms_stock_bin_history_dtl_idx4 ON stg.stg_wms_stock_bin_history_dtl USING btree (wms_stock_customer, wms_stock_ou);
CREATE INDEX stg_wms_stock_bin_history_dtl_idx5 ON stg.stg_wms_stock_bin_history_dtl USING btree (wms_stock_thu_id, wms_stock_ou);
CREATE INDEX stg_wms_stockbal_su_serial_key_idx2 ON stg.stg_wms_stockbal_su_serial USING btree (sbs_wh_code, sbs_ouinstid, sbs_item_code, sbs_sr_no, sbs_zone, sbs_bin, sbs_stock_status, sbs_lot_no, sbs_su_serial_no, sbs_thu_serial_no);
CREATE INDEX stg_wms_tariff_transport_hdr_idx ON stg.stg_wms_tariff_transport_hdr USING btree (wms_tf_tp_id, wms_tf_tp_ou);
CREATE INDEX wms_asn_detail_idx ON stg.stg_wms_asn_detail USING btree (wms_asn_location, wms_asn_ou);
CREATE INDEX wms_asn_detail_idx1 ON stg.stg_wms_asn_detail USING btree (wms_asn_itm_code, wms_asn_ou);
CREATE INDEX wms_asn_detail_idx2 ON stg.stg_wms_asn_detail USING btree (wms_asn_thu_id, wms_asn_ou);
CREATE INDEX wms_asn_detail_idx3 ON stg.stg_wms_asn_detail USING btree (wms_asn_order_uom, wms_asn_ou);
CREATE INDEX wms_asn_detail_idx4 ON stg.stg_wms_asn_detail USING btree (wms_asn_location, wms_asn_ou, wms_asn_no);
CREATE INDEX wms_asn_header_idx ON stg.stg_wms_asn_header USING btree (wms_asn_location, wms_asn_ou);
CREATE INDEX wms_asn_header_idx1 ON stg.stg_wms_asn_header USING btree (wms_asn_cust_code, wms_asn_ou);
CREATE INDEX wms_asn_header_idx2 ON stg.stg_wms_asn_header USING btree (wms_asn_supp_code, wms_asn_ou);
CREATE INDEX wms_contract_hdr_idx ON stg.stg_wms_contract_hdr USING btree (wms_cont_vendor_id, wms_cont_ou);
CREATE INDEX wms_contract_hdr_idx1 ON stg.stg_wms_contract_hdr USING btree (wms_cont_location, wms_cont_ou);
CREATE INDEX wms_contract_hdr_idx2 ON stg.stg_wms_contract_hdr USING btree (wms_cont_customer_id, wms_cont_ou);
CREATE INDEX wms_oub_orderdate_idx ON stg.stg_wms_outbound_header USING btree (wms_oub_orderdate);
CREATE INDEX f_shipment_details_pick_tmp_ndx1 ON tmp.f_shipment_details_pick_tmp USING btree (ouinstance, ((trip_plan_id)::text), ((br_request_id)::text));
CREATE INDEX f_triplogeventdetail_act_ndx ON tmp.f_triplogeventdetail_act USING btree (tled_ouinstance, tled_trip_plan_id, tled_leg_no);
CREATE INDEX f_triplogeventdetail_pln_ndx ON tmp.f_triplogeventdetail_pln USING btree (tled_ouinstance, tled_trip_plan_id, tled_leg_no);
CREATE INDEX f_triplogthudetail_tmp_ndx ON tmp.f_triplogthudetail_tmp USING btree (tltd_ouinstance, tltd_trip_plan_id, tltd_trip_sequence, tltd_trip_plan_line_id);
