CREATE VIEW default.Tms_Shipment_Dashboard_Info
(
    `shipment_dtl_key` Int64,
    `trip_plan_datekey` Int32,
    `trip_exec_datekey` Int32,
    `ouinstance` Int32,
    `br_request_id` String,
    `br_customer_id` Nullable(String),
    `br_customer_ref_no` Nullable(String),
    `br_status` Nullable(String),
    `service_type` Nullable(String),
    `sub_service_type` Nullable(String),
    `trip_plan_id` String,
    `trip_plan_status` Nullable(String),
    `vehicle_type` Nullable(String),
    `vehicle_id` Nullable(String),
    `agent_id` Nullable(String),
    `agent_resource` Nullable(String),
    `loc` Nullable(String),
    `from_city` Nullable(String),
    `from_state` Nullable(String),
    `to_city` Nullable(String),
    `to_state` Nullable(String),
    `leg_behaviour` String,
    `trip_plan_date` Nullable(DateTime64(6)),
    `trip_plan_end_date` Nullable(DateTime64(6)),
    `trip_plan_seq` Nullable(Int32),
    `dispatch_doc_no` String,
    `dispatch_doc_type` Nullable(String),
    `veh_in_dim_uom` Nullable(String),
    `veh_volume` Nullable(Decimal(38, 6)),
    `planned_tripstart` Nullable(DateTime64(6)),
    `planned_arrived` Nullable(DateTime64(6)),
    `planned_takenover_handedover` Nullable(DateTime64(6)),
    `planned_departed` Nullable(DateTime64(6)),
    `planned_tripend` Nullable(DateTime64(6)),
    `actual_tripstart` Nullable(DateTime64(6)),
    `actual_arrived` Nullable(DateTime64(6)),
    `actual_takenover_handedover` Nullable(DateTime64(6)),
    `actual_departed` Nullable(DateTime64(6)),
    `actual_tripend` Nullable(DateTime64(6)),
    `ontime_pickup_delivery` Int32,
    `shipmentdays` Nullable(Int32),
    `draft_bill_total_value` Nullable(Decimal(38, 8)),
    `draft_bill_approved_date` Nullable(DateTime64(6)),
    `trip_volume` Nullable(Decimal(38, 6)),
    `trip_volume_uom` Nullable(String),
    `createddatetime` DateTime64(6),
    `draft_bill_no` Nullable(String),
    `draft_bill_volume` Nullable(Decimal(38, 8)),
    `draft_bill_contract` Nullable(String),
    `draft_bill_line_status` Nullable(String),
    `podflag` Nullable(Int32),
    `br_invoice_value` Nullable(Decimal(38, 8)),
    `trip_plan_createddate` Nullable(DateTime64(6)),
    `from_pincode` Nullable(String),
    `to_pincode` Nullable(String),
    `expected_datetodeliver` Nullable(DateTime64(6)),
    `ontimedelvry_count` Nullable(Int32),
    `br_key` Nullable(Int64),
    `ship_customer_key` Nullable(Int64),
    `ship_loc_key` Nullable(Int64)
) AS
SELECT *
FROM onesource.f_shipment_details