CREATE VIEW default.wms_div_division_hdr
(
    `wms_div_ou` Nullable(Int32),
    `wms_div_code` Nullable(String),
    `wms_div_desc` Nullable(String),
    `wms_div_status` Nullable(String),
    `wms_div_type` Nullable(String),
    `wms_div_reason_code` Nullable(String),
    `wms_div_user_def1` Nullable(String),
    `wms_div_user_def2` Nullable(String),
    `wms_div_user_def3` Nullable(String),
    `wms_div_timestamp` Nullable(Int32),
    `wms_div_created_by` Nullable(String),
    `wms_div_created_dt` Nullable(DateTime64(6)),
    `wms_div_modified_by` Nullable(String),
    `wms_div_modified_dt` Nullable(DateTime64(6)),
    `etlactiveind` Nullable(Int32),
    `etljobname` Nullable(String),
    `envsourcecd` Nullable(String),
    `datasourcecd` Nullable(String),
    `etlcreatedatetime` Nullable(DateTime64(6)),
    `etlupdatedatetime` Nullable(DateTime64(6))
) AS
SELECT
    div_ou AS wms_div_ou,
    div_code AS wms_div_code,
    div_desc AS wms_div_desc,
    div_status AS wms_div_status,
    div_type AS wms_div_type,
    div_reason_code AS wms_div_reason_code,
    div_user_def1 AS wms_div_user_def1,
    div_user_def2 AS wms_div_user_def2,
    div_user_def3 AS wms_div_user_def3,
    div_timestamp AS wms_div_timestamp,
    div_created_by AS wms_div_created_by,
    div_created_dt AS wms_div_created_dt,
    div_modified_by AS wms_div_modified_by,
    div_modified_dt AS wms_div_modified_dt,
    etlactiveind,
    etljobname,
    envsourcecd,
    datasourcecd,
    etlcreatedatetime,
    etlupdatedatetime
FROM onesource.d_division