CREATE VIEW default.wms_vendor_hdr
(
    `wms_vendor_id` Nullable(String),
    `wms_vendor_ou` Nullable(Int32),
    `wms_vendor_status` Nullable(String),
    `wms_vendor_name` Nullable(String),
    `wms_vendor_payterm` Nullable(String),
    `wms_vendor_reason_code` Nullable(String),
    `wms_vendor_classifcation` Nullable(String),
    `wms_vendor_currency` Nullable(String),
    `wms_vendor_for_self` Nullable(Int32),
    `wms_vendor_created_by` Nullable(String),
    `wms_vendor_created_date` Nullable(DateTime64(6)),
    `wms_vendor_modified_by` Nullable(String),
    `wms_vendor_modified_date` Nullable(DateTime64(6)),
    `wms_vendor_timestamp` Nullable(Int32),
    `wms_vendor_address1` Nullable(String),
    `wms_vendor_address2` Nullable(String),
    `wms_vendor_address3` Nullable(String),
    `wms_vendor_city` Nullable(String),
    `wms_vendor_state` Nullable(String),
    `wms_vendor_country` Nullable(String),
    `wms_vendor_phone1` Nullable(String),
    `wms_vendor_phone2` Nullable(String),
    `wms_vendor_email` Nullable(String),
    `wms_vendor_fax` Nullable(String),
    `wms_vendor_url` Nullable(String),
    `wms_vendor_subzone` Nullable(String),
    `wms_vendor_timezone` Nullable(String),
    `wms_vendor_zone` Nullable(String),
    `wms_vendor_region` Nullable(String),
    `wms_vendor_postal_code` Nullable(String),
    `wms_vendor_agnt_reg` Nullable(String),
    `wms_vendor_agnt_cha` Nullable(String),
    `wms_vendor_carrier_road` Nullable(String),
    `wms_vendor_carrier_rail` Nullable(String),
    `wms_vendor_carrier_air` Nullable(String),
    `wms_vendor_carrier_sea` Nullable(String),
    `wms_vendor_sub_cntrct_veh` Nullable(String),
    `wms_vendor_sub_cntrct_emp` Nullable(String),
    `wms_vendor_lat` Nullable(Decimal(18, 2)),
    `wms_vendor_long` Nullable(Decimal(18, 2)),
    `wms_vendor_reg` Nullable(String),
    `wms_vendor_dept` Nullable(String),
    `wms_vendor_ln_business` Nullable(String),
    `wms_vendor_rcti` Nullable(String),
    `wms_vendor_gen_from` Nullable(String),
    `wms_vendor_group` Nullable(String),
    `wms_vendor_std_contract` Nullable(Int32),
    `wms_vendor_final_bill_stage` Nullable(String),
    `wms_vendor_allwdb_billto` Nullable(Int32),
    `wms_vendor_insrnc_prvdr` Nullable(String),
    `etlactiveind` Nullable(Int32),
    `etljobname` Nullable(String),
    `envsourcecd` Nullable(String),
    `datasourcecd` Nullable(String),
    `etlcreatedatetime` Nullable(DateTime64(6)),
    `etlupdatedatetime` Nullable(DateTime64(6))
) AS
SELECT
    vendor_id AS wms_vendor_id,
    vendor_ou AS wms_vendor_ou,
    vendor_status AS wms_vendor_status,
    vendor_name AS wms_vendor_name,
    vendor_payterm AS wms_vendor_payterm,
    vendor_reason_code AS wms_vendor_reason_code,
    vendor_classifcation AS wms_vendor_classifcation,
    vendor_currency AS wms_vendor_currency,
    vendor_for_self AS wms_vendor_for_self,
    vendor_created_by AS wms_vendor_created_by,
    vendor_created_date AS wms_vendor_created_date,
    vendor_modified_by AS wms_vendor_modified_by,
    vendor_modified_date AS wms_vendor_modified_date,
    vendor_timestamp AS wms_vendor_timestamp,
    vendor_address1 AS wms_vendor_address1,
    vendor_address2 AS wms_vendor_address2,
    vendor_address3 AS wms_vendor_address3,
    vendor_city AS wms_vendor_city,
    vendor_state AS wms_vendor_state,
    vendor_country AS wms_vendor_country,
    vendor_phone1 AS wms_vendor_phone1,
    vendor_phone2 AS wms_vendor_phone2,
    vendor_email AS wms_vendor_email,
    vendor_fax AS wms_vendor_fax,
    vendor_url AS wms_vendor_url,
    vendor_subzone AS wms_vendor_subzone,
    vendor_timezone AS wms_vendor_timezone,
    vendor_zone AS wms_vendor_zone,
    vendor_region AS wms_vendor_region,
    vendor_postal_code AS wms_vendor_postal_code,
    vendor_agnt_reg AS wms_vendor_agnt_reg,
    vendor_agnt_cha AS wms_vendor_agnt_cha,
    vendor_carrier_road AS wms_vendor_carrier_road,
    vendor_carrier_rail AS wms_vendor_carrier_rail,
    vendor_carrier_air AS wms_vendor_carrier_air,
    vendor_carrier_sea AS wms_vendor_carrier_sea,
    vendor_sub_cntrct_veh AS wms_vendor_sub_cntrct_veh,
    vendor_sub_cntrct_emp AS wms_vendor_sub_cntrct_emp,
    vendor_lat AS wms_vendor_lat,
    vendor_long AS wms_vendor_long,
    vendor_reg AS wms_vendor_reg,
    vendor_dept AS wms_vendor_dept,
    vendor_ln_business AS wms_vendor_ln_business,
    vendor_rcti AS wms_vendor_rcti,
    vendor_gen_from AS wms_vendor_gen_from,
    vendor_group AS wms_vendor_group,
    vendor_std_contract AS wms_vendor_std_contract,
    vendor_final_bill_stage AS wms_vendor_final_bill_stage,
    vendor_allwdb_billto AS wms_vendor_allwdb_billto,
    vendor_insrnc_prvdr AS wms_vendor_insrnc_prvdr,
    etlactiveind,
    etljobname,
    envsourcecd,
    datasourcecd,
    etlcreatedatetime,
    etlupdatedatetime
FROM onesource.d_vendor