CREATE VIEW default.wms_customer_hdr
(
    `wms_customer_id` Nullable(String),
    `wms_customer_ou` Nullable(Int32),
    `wms_customer_name` Nullable(String),
    `wms_customer_status` Nullable(String),
    `wms_customer_type` Nullable(String),
    `wms_customer_description` Nullable(String),
    `wms_customer_credit_term` Nullable(String),
    `wms_customer_pay_term` Nullable(String),
    `wms_customer_currency` Nullable(String),
    `wms_customer_reason_code` Nullable(String),
    `wms_customer_address1` Nullable(String),
    `wms_customer_address2` Nullable(String),
    `wms_customer_address3` Nullable(String),
    `wms_customer_city` Nullable(String),
    `wms_customer_state` Nullable(String),
    `wms_customer_country` Nullable(String),
    `wms_customer_postal_code` Nullable(String),
    `wms_customer_timezone` Nullable(String),
    `wms_customer_contact_person` Nullable(String),
    `wms_customer_phone1` Nullable(String),
    `wms_customer_phone2` Nullable(String),
    `wms_customer_fax` Nullable(String),
    `wms_customer_email` Nullable(String),
    `wms_customer_bill_same_as_customer` Nullable(Int32),
    `wms_customer_bill_address1` Nullable(String),
    `wms_customer_bill_address2` Nullable(String),
    `wns_customer_bill_address3` Nullable(String),
    `wms_customer_bill_city` Nullable(String),
    `wms_customer_bill_state` Nullable(String),
    `wms_customer_bill_country` Nullable(String),
    `wms_customer_bill_postal_code` Nullable(String),
    `wms_customer_bill_contact_person` Nullable(String),
    `wms_customer_bill_phone` Nullable(String),
    `wms_customer_bill_fax` Nullable(String),
    `wms_customer_ret_undelivered` Nullable(String),
    `wms_customer_ret_same_as_customer` Nullable(Int32),
    `wms_customer_ret_address1` Nullable(String),
    `wms_customer_ret_address2` Nullable(String),
    `wms_customer_ret_address3` Nullable(String),
    `wms_customer_ret_city` Nullable(String),
    `wms_customer_ret_state` Nullable(String),
    `wms_customer_ret_country` Nullable(String),
    `wms_customer_ret_postal_code` Nullable(String),
    `wms_customer_ret_contact_person` Nullable(String),
    `wms_customer_ret_phone1` Nullable(String),
    `wms_customer_ret_fax` Nullable(String),
    `wms_customer_timestamp` Nullable(Int32),
    `wms_customer_created_by` Nullable(String),
    `wms_customer_created_dt` Nullable(DateTime64(6)),
    `wms_customer_modified_by` Nullable(String),
    `wms_customer_modified_dt` Nullable(DateTime64(6)),
    `wms_customer_BR_valid_prof_id` Nullable(String),
    `wms_customer_payment_typ` Nullable(String),
    `wms_customer_geo_fence` Nullable(Decimal(18, 2)),
    `wms_customer_bill_geo_fence` Nullable(Decimal(18, 2)),
    `wms_customer_bill_longtitude` Nullable(Decimal(18, 2)),
    `wms_customer_bill_latitude` Nullable(Decimal(18, 2)),
    `wms_customer_bill_zone` Nullable(String),
    `wms_customer_bill_sub_zone` Nullable(String),
    `wms_customer_bill_region` Nullable(String),
    `wms_customer_ret_geo_fence` Nullable(Decimal(18, 2)),
    `wms_customer_ret_longtitude` Nullable(Decimal(18, 2)),
    `wms_customer_ret_latitude` Nullable(Decimal(18, 2)),
    `wms_customer_customer_grp` Nullable(String),
    `wms_customer_industry_typ` Nullable(String),
    `wms_allow_rev_protection` Nullable(Int32),
    `wms_customer_invrep` Nullable(String),
    `wms_customer_rcti` Nullable(Int32),
    `wms_customer_gen_from` Nullable(String),
    `wms_customer_bill_Hrchy1` Nullable(String),
    `wms_customer_new_customer` Nullable(Int32),
    `wms_customer_final_bill_stage` Nullable(String),
    `wms_customer_allwdb_billto` Nullable(String),
    `wms_customer_contact_person2` Nullable(String),
    `wms_cus_contact_person2_Email` Nullable(String),
    `etlactiveind` Nullable(Int32),
    `etljobname` Nullable(String),
    `envsourcecd` Nullable(String),
    `datasourcecd` Nullable(String),
    `etlcreatedatetime` Nullable(DateTime64(6)),
    `etlupdatedatetime` Nullable(DateTime64(6))
) AS
SELECT
    customer_id AS wms_customer_id,
    customer_ou AS wms_customer_ou,
    customer_name AS wms_customer_name,
    customer_status AS wms_customer_status,
    customer_type AS wms_customer_type,
    customer_description AS wms_customer_description,
    customer_credit_term AS wms_customer_credit_term,
    customer_pay_term AS wms_customer_pay_term,
    customer_currency AS wms_customer_currency,
    customer_reason_code AS wms_customer_reason_code,
    customer_address1 AS wms_customer_address1,
    customer_address2 AS wms_customer_address2,
    customer_address3 AS wms_customer_address3,
    customer_city AS wms_customer_city,
    customer_state AS wms_customer_state,
    customer_country AS wms_customer_country,
    customer_postal_code AS wms_customer_postal_code,
    customer_timezone AS wms_customer_timezone,
    customer_contact_person AS wms_customer_contact_person,
    customer_phone1 AS wms_customer_phone1,
    customer_phone2 AS wms_customer_phone2,
    customer_fax AS wms_customer_fax,
    customer_email AS wms_customer_email,
    customer_bill_same_as_customer AS wms_customer_bill_same_as_customer,
    customer_bill_address1 AS wms_customer_bill_address1,
    customer_bill_address2 AS wms_customer_bill_address2,
    customer_bill_address3 AS wns_customer_bill_address3,
    customer_bill_city AS wms_customer_bill_city,
    customer_bill_state AS wms_customer_bill_state,
    customer_bill_country AS wms_customer_bill_country,
    customer_bill_postal_code AS wms_customer_bill_postal_code,
    customer_bill_contact_person AS wms_customer_bill_contact_person,
    customer_bill_phone AS wms_customer_bill_phone,
    customer_bill_fax AS wms_customer_bill_fax,
    customer_ret_undelivered AS wms_customer_ret_undelivered,
    customer_ret_same_as_customer AS wms_customer_ret_same_as_customer,
    customer_ret_address1 AS wms_customer_ret_address1,
    customer_ret_address2 AS wms_customer_ret_address2,
    customer_ret_address3 AS wms_customer_ret_address3,
    customer_ret_city AS wms_customer_ret_city,
    customer_ret_state AS wms_customer_ret_state,
    customer_ret_country AS wms_customer_ret_country,
    customer_ret_postal_code AS wms_customer_ret_postal_code,
    customer_ret_contact_person AS wms_customer_ret_contact_person,
    customer_ret_phone1 AS wms_customer_ret_phone1,
    customer_ret_fax AS wms_customer_ret_fax,
    customer_timestamp AS wms_customer_timestamp,
    customer_created_by AS wms_customer_created_by,
    customer_created_dt AS wms_customer_created_dt,
    customer_modified_by AS wms_customer_modified_by,
    customer_modified_dt AS wms_customer_modified_dt,
    customer_br_valid_prof_id AS wms_customer_BR_valid_prof_id,
    customer_payment_typ AS wms_customer_payment_typ,
    customer_geo_fence AS wms_customer_geo_fence,
    customer_bill_geo_fence AS wms_customer_bill_geo_fence,
    customer_bill_longtitude AS wms_customer_bill_longtitude,
    customer_bill_latitude AS wms_customer_bill_latitude,
    customer_bill_zone AS wms_customer_bill_zone,
    customer_bill_sub_zone AS wms_customer_bill_sub_zone,
    customer_bill_region AS wms_customer_bill_region,
    customer_ret_geo_fence AS wms_customer_ret_geo_fence,
    customer_ret_longtitude AS wms_customer_ret_longtitude,
    customer_ret_latitude AS wms_customer_ret_latitude,
    customer_customer_grp AS wms_customer_customer_grp,
    customer_industry_typ AS wms_customer_industry_typ,
    allow_rev_protection AS wms_allow_rev_protection,
    customer_invrep AS wms_customer_invrep,
    customer_rcti AS wms_customer_rcti,
    customer_gen_from AS wms_customer_gen_from,
    customer_bill_hrchy1 AS wms_customer_bill_Hrchy1,
    customer_new_customer AS wms_customer_new_customer,
    customer_final_bill_stage AS wms_customer_final_bill_stage,
    customer_allwdb_billto AS wms_customer_allwdb_billto,
    customer_contact_person2 AS wms_customer_contact_person2,
    cus_contact_person2_email AS wms_cus_contact_person2_Email,
    etlactiveind,
    etljobname,
    envsourcecd,
    datasourcecd,
    etlcreatedatetime,
    etlupdatedatetime
FROM onesource.d_customer